### ISSUE TITLE
Door Lock controls

### ISSUE THREAD

**Issue by holdestmade** [fuatakgun/kia_uvo#10]
Can you add the lock and unlock commands to the lock ?

**Comment by fuatakgun** [comment]
Yes, i am on it. Problem with lock and unlock, kia doesn't generate a response immediately and response arrives with push notification over google cloud messaging.

The response can be negative or positive, so you car might receive and process your message or generate a failure. To receive this response, i am looking at options;
- subscribing google cloud messaging notifications
- polling command status to find out status

I am closer to the second one, still investigating

**Comment by holdestmade** [comment]
Ok, I see. I think the status update would work ? FYI, Bluelinky does get a confirmation message, not sure how they do it.

**Comment by fuatakgun** [comment]
I will double check bluelinky implementation

**Comment by fuatakgun** [comment]
should be implemented here: https://github.com/fuatakgun/kia_uvo/commit/f8c1c6474ff8fdf61e372238ae5d450dfd1d36b9
it is still a bit buggy, needs improvement

**Comment by holdestmade** [comment]
Only the `binary_sensor` is still showing and not a lock entity ?

**Comment by fuatakgun** [comment]
again my bad, commit has been merged, please refresh with latest code.
it is locking/unlocking with data will not be updated immediately.

**Comment by holdestmade** [comment]
The lock works fine but never updates the status
I tried unlocking and immediately calling the update service and it updated right away, not sure what delay you are using ?

**Comment by fuatakgun** [comment]
So, i have implemented 10 seconds waiting time because when i send a lock/unlock command, i am receiving a response as 'command delivered' but not 'command executed'. If you get the latest code, you can see that the state will be updated in 10 seconds after sending the command

**Comment by fuatakgun** [comment]
please get the latest version, it should be all fixed.

**Comment by holdestmade** [comment]
Thanks, nearly works. When unlocking, the state is updating but when locking, the state will not update, only with a force refresh

Also noted that if I do more than 2 locks/unlocks, it fails with a Duplicate request error from Kia

**Comment by fuatakgun** [comment]
because `lock`/`unlock`/`force_update` is time consuming, they are not happening immediately.
I will extend `force_update` request to 3 seconds after sending `lock` request.
and if it fails, it will try again in 30 seconds for 5 times

**Comment by fuatakgun** [comment]
get latest version, error will be gone.

I am not sure why lock/unlock is behaving weird. It is same for me when I am using UVO app.

Can you check your experience with UVO app and let me know if it is different?

**Comment by anthonyangel** [comment]
With the Uvo app I need to specify my PIN in order to carry out any remote actions on the vehicle (e.g. lock/unlock, or turning on the AC), does that need to be implemented here?

**Comment by fuatakgun** [comment]
interestingly no, I did not find any actual requirement to get;
- location data
- lock/unlock
- get latest data

I do not know why we are forced to use PIN here. So far, it works fine for me without PIN

**Comment by holdestmade** [comment]
> get latest version, error will be gone.
> 
> I am not sure why lock/unlock is behaving weird. It is same for me when I am using UVO app.
> 
> Can you check your experience with UVO app and let me know if it is different?

Yes UVO is similar, seems to be limited to how many times in succession you can perform lock/unlock

**Comment by fuatakgun** [comment]
let me know if we can resolve this

**Comment by holdestmade** [comment]
> interestingly no, I did not find any actual requirement to get;
> 
> * location data
> * lock/unlock
> * get latest data
> 
> my car does not support remote start/stop, i will try and send this command over API and share my findings.
> 
> I do not know why we are forced to use PIN here. So far, it works fine for me without PIN

In bluelinky nodered, in the config you have to add Brand (Kia or Hyundai) and PIN

**Comment by fuatakgun** [comment]
> > interestingly no, I did not find any actual requirement to get;
> > 
> > * location data
> > * lock/unlock
> > * get latest data
> > 
> > my car does not support remote start/stop, i will try and send this command over API and share my findings.
> > I do not know why we are forced to use PIN here. So far, it works fine for me without PIN
> 
> In bluelinky nodered, in the config you have to add Brand (Kia or Hyundai) and PIN

I know, still, I am not able to find a need for asking for PIN.

**Comment by holdestmade** [comment]
All seems to work now, with approx 10 secs delay for update
