### ISSUE TITLE
add heated seats

### ISSUE THREAD

**Issue by Jasring** [fuatakgun/kia_uvo#120]
I would like to see the status of the seat heating (and for some versions of this car there will also be ventilation but I don't have that)
In the data field these are the fields indicating the seat heating:

```
seatHeaterVentState:
frSeatHeatState
flSeatHeatState
rlSeatHeatState
rrSeatHeatState
```

For me only the front seats are heated but there is also an option for this car for the backseats.

**Comment by fuatakgun** [comment]
We need full data dump not part of it

**Comment by Jasring** [comment]
hope this will do:
`vehicle_data: 
vehicleLocation:
  coord:
    lat: xx.453697
    lon: x.909028
    alt: 0
    type: 0
  head: 226
  speed:
    value: 0
    unit: 0
  accuracy:
    hdop: 10
    pdop: 10
  time: '20211114134249'
vehicleStatus:
  airCtrlOn: false
  engine: false
  doorLock: true
  doorOpen:
    frontLeft: 0
    frontRight: 0
    backLeft: 0
    backRight: 0
  trunkOpen: false
  airTemp:
    value: 01H
    unit: 0
    hvacTempType: 1
  defrost: false
  lowFuelLight: false
  acc: false
  hoodOpen: false
  steerWheelHeat: 0
  sideBackWindowHeat: 0
  dte:
    value: 153
    unit: 1
  tirePressureLamp:
    tirePressureLampAll: 0
  seatHeaterVentState:
    frSeatHeatState: 2
    flSeatHeatState: 2
    rlSeatHeatState: 2
    rrSeatHeatState: 2
  battery:
    batSoc: 100
    batState: 0
    sjbDeliveryMode: 1
    batSignalReferenceValue:
      batWarning: 0
    powerAutoCutMode: 0
  lampWireStatus:
    stopLamp:
      stopLampStatus: false
      leftLamp: false
      rightLamp: false
    headLamp:
      headLampStatus: false
      leftLowLamp: false
      rightLowLamp: false
      leftHighLamp: false
      rightHighLamp: false
      leftBifuncLamp: false
      rightBifuncLamp: false
    turnSignalLamp:
      turnSignalLampStatus: false
      leftFrontLamp: false
      rightFrontLamp: false
      leftRearLamp: false
      rightRearLamp: false
  windowOpen:
    frontLeft: 0
    frontRight: 0
    backLeft: 0
    backRight: 0
  smartKeyBatteryWarning: false
  fuelLevel: 18
  washerFluidStatus: false
  breakOilStatus: false
  time: '20211114134250'
  frontWindowHeat: 0
odometer:
  value: 6361.7
  unit: 1

vehicle_name: TUCSON
friendly_name: TUCSON Data`

**Comment by cdnninja** [comment]
@Jasring  are you able to test the PR I created to confirm it works for you?
