### ISSUE TITLE
bug: USA needs to handle 0xLOW value for temperature and currently doesn't

### ISSUE THREAD

**Issue by dahlb** [fuatakgun/kia_uvo#127]
```
Logger: homeassistant.util.logging
Source: util/logging.py:105
First occurred: November 10, 2021, 6:47:13 AM (33 occurrences)
Last logged: 8:52:27 AM

Exception in update when dispatching 'kia_uvo_update_0': () Traceback (most recent call last): File "/config/custom_components/kia_uvo/KiaUvoEntity.py", line 21, in update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in _async_write_ha_state state = self._stringify_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in _stringify_state if (state := self.state) is None: File "/config/custom_components/kia_uvo/sensor.py", line 100, in state return self.vehicle.kia_uvo_api.get_temperature_range_by_region()[int(value, 16)] ValueError: invalid literal for int() with base 16: '0xLOW'
```

this is to separate @tchoward reported bug in https://github.com/fuatakgun/kia_uvo/issues/88 as it wasn't handled in the initial implementation that has been merged and handled most use cases

@cdnninja been a while since I used github but you can assign this to me if that's possible, I just wrote it up so I wouldn't forget.  I'll try to have a fix in a pr this week.

**Comment by cdnninja** [comment]
This also looks to apply to the Hyundai USA version so ideally fixing both.  Not sure the Hyundai one throws an exception though.

**Comment by dahlb** [comment]
fixed in https://github.com/fuatakgun/kia_uvo/pull/139 for kia and Hyundai once I figure out the new lint issues

**Comment by tchoward** [comment]
Looks like this is fixed; I am no longer seeing the issue.

**Comment by dahlb** [comment]
Merged fix
