### ISSUE TITLE
CAN KonaEV 2020 set to ICE

### ISSUE THREAD

**Issue by trueppp** [fuatakgun/kia_uvo#146]
I'm getting this message in the logs, 

2021-11-16 15:27:20 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Engine type set VEHICLE_ENGINE_TYPE.IC

I'm guessing this is why All EV entities are showing as unavailable?

**Comment by trueppp** [comment]
In force update response, parameters are there

Received forced vehicle data {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'status': {'lastStatusDate': '20211116153356', 'airCtrlOn': False, 'engine': False, 'doorLock': True, 'doorOpen': {'frontLeft': 0, 'frontRight': 0, 'backLeft': 0, 'backRight': 0}, 'trunkOpen': False, 'airTempUnit': 'C', 'airTemp': {'value': '00H', 'unit': 0}, 'defrost': False, 'acc': False, 'evStatus': {'batteryCharge': False, 'batteryStatus': 29, 'batteryPlugin': 0, 'remainTime2': {'etc1': {'value': 0, 'unit': 1}, 'etc2': {'value': 0, 'unit': 1}, 'etc3': {'value': 0, 'unit': 1}, 'atc': {'value': 0, 'unit': 1}}, 'drvDistance': [{'rangeByFuel': {'gasModeRange': {'value': 0.0, 'unit': 1}, 'evModeRange': {'value': 104.0, 'unit': 1}, 'totalAvailableRange': {'value': 104.0, 'unit': 1}}, 'type': 2}]}, 'hoodOpen': False, 'transCond': True, 'steerWheelHeat': 0, 'sideBackWindowHeat': 0, 'dte': {}, 'tirePressureLamp': {'tirePressureLampAll': 0}, 'battery': {'batSoc': 87, 'batState': 0, 'batSignalReferenceValue': {}}, 'remoteIgnition': True, 'seatHeaterVentInfo': {}, 'sleepModeCheck': False, 'lampWireStatus': {'headLamp': {}, 'stopLamp': {}, 'turnSignalLamp': {}}, 'windowOpen': {}, 'engineRuntime': {}}}}

**Comment by cdnninja** [comment]
Has this ever detected correctly for you?    My initial impression is that the logic should work since you have evStatus.  I may need to had debug to it.

**Comment by trueppp** [comment]
Detected correctly once, then stopped after

**Comment by trueppp** [comment]
Reinstalled, it detected EV correctly, then switched to ICE after start climate call

**Comment by Kevr0n228** [comment]
the parameters in the force_update that were posted look to be exactly the same as what I'd get out of my 2019 Kona EV -are there particular entities that should be available for EVs that you're not seeing @trueppp?

**Comment by cdnninja** [comment]
@trueppp  Do you have a log of the same data but not for a force update but rather when it switches to ICE?  I am wondering if Hyundai isn't giving the data in one of the updates.  It would default to ICE if that occurred.

**Comment by trueppp** [comment]
As the car Type is detected as ICE, every EV entity is showing as unavailable in HA (EV Battery, Charging, Range etc)

**Comment by cdnninja** [comment]
@Kevr0n228  is it working correctly for you?  @trueppp  let me know when you get these logs as well.

**Comment by cdnninja** [comment]
Please re-open if you see this again or have the logs needed to debug it.

**Comment by Kevr0n228** [comment]
Sorry for the late response, but yes it is working properly for me.
