### ISSUE TITLE
nothing chamged. same error while login in

### ISSUE THREAD

**Issue by HMvdZijden** [fuatakgun/kia_uvo#147]
Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:169
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 21:30:00 (1 occurrences)
Last logged: 21:30:00

kia_uvo Exception in kia_uvo login : can only concatenate str (not "NoneType") to str - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/config_flow.py", line 154, in async_step_user self.token = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 108, in login ) = self.get_access_token() File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 312, in get_access_token "grant_type=authorization_code&redirect_uri=https%3A%2F%2F" TypeError: can only concatenate str (not "NoneType") to str

**Comment by cdnninja** [comment]
Do you have a Kia in the EU? If so this is duplicate to #79.

**Comment by fuatakgun** [comment]
merging into here: https://github.com/fuatakgun/kia_uvo/issues/79
