### ISSUE TITLE
Github Actions Release

### ISSUE THREAD

**Issue by cdnninja** [fuatakgun/kia_uvo#155]
I have setup a release workflow in my own fork that does automatic version numbering and release notes.   This can be viewed here: https://github.com/cdnninja/kia_uvo/releases

Currently I am running it a bit different than how semantic release wants in that it runs twice a week and builds from it(wed and sun).  Where as semantic wants it to do a release for each commit.    We can also manually run the workflow if we want to release something quickly. 

I am looking for feedback and thoughts around this.   This would allow people within HACS to select the version but also communicate changes.   The key to this working well is that all commits / PRs following the semantic release.  More details here: https://github.com/semantic-release/semantic-release

Essentially your PR needs to be the change, ideally listing region and brand impacted.  

Key things to know:

1. PRs need to follow the naming scheme.  
2. End users won't get the new commit until a release occurs.  This is good and bad.  Anyone with contribute status can create an urgent release. 
3. Version numbers are decided based on fix, feat, or breaking changes.  As per the above link. 

Theory is once implemented we only touch it when we want a build asap.

**Comment by cdnninja** [comment]
![image](https://user-images.githubusercontent.com/6373468/142300426-6b8958a2-4dc8-446f-a786-2bdde5965757.png)

**Comment by dahlb** [comment]
seems a great way to introduce stability for those that want it ;)

**Comment by cdnninja** [comment]
@dahlb  @fuatakgun release is now running twice a week.   I have run it manually to build version 1.0.   We should be able to ask users what version they are on now.   I will watch this over the next bit to ensure it runs correctly.  

As a reminder if you want to not follow the release in HACS you need to choose to do that.  So for bug fixes they won't hit users right away for an issue.  We can manually build when required or increase frequency of builds.
