### ISSUE TITLE
Error add integration

### ISSUE THREAD

**Issue by simille83** [fuatakgun/kia_uvo#165]
After updating the server restart the integration doesn't load so I tried to reinstall it from scratch but when I add it in Home Assistant I get the error "unable to load configuration flow" with the following error in the Home LOG Assistant
2021-11-19 22:47:13 ERROR (MainThread) [homeassistant.config_entries] An error occurred while loading the configuration flow for kia_uvo integration: no module named 'bs4'

**Comment by cdnninja** [comment]
@fuatakgun  this is EU Kia e-Niro from https://github.com/fuatakgun/kia_uvo/issues/161#issuecomment-974498647

**Comment by cdnninja** [comment]
Could you edit your manifest.json file with line 7 being:

`  "requirements": ["push_receiver==0.1.1", "curlify", "bs4"],`

**Comment by simille83** [comment]
> Could you edit your manifest.json file with line 7 being:
> 
> ` "requirements": ["push_receiver==0.1.1", "curlify", "bs4"],`

Ok, it worked...thanks
