### ISSUE TITLE
replace request with HA preferred lib https://docs.aiohttp.org/en/stable/client.html

### ISSUE THREAD

**Issue by dahlb** [fuatakgun/kia_uvo#173]
saw today that HA prefers api calls to use an async library like aiohttp instead of request's sync implementation, I'll reimplement Kia USA

**Comment by dahlb** [comment]
https://developers.home-assistant.io/docs/api_lib_auth ("Home Assistant is written in async, but is able to work with synchronous libraries too. We prefer async libraries")

**Comment by fuatakgun** [comment]
As a side note, this is a very good architectural change but will not have any impact in performance or usability.

**Comment by dahlb** [comment]
I added this for best practices and because I think I'll enjoy learning a new useful library.  This academically does have performance impact, but I barely care about that edge case. :)

**Comment by dahlb** [comment]
had to revert the shim solution I made using run_coroutine_threadsafe due to deadlock created during interval updating invocations using different threading model then the other update invocations.  Threading seems inconsistent vs 


https://developers.home-assistant.io/docs/asyncio_working_with_async
