### ISSUE TITLE
Error when reading location of 2020 Hyundai Santa Fe

### ISSUE THREAD

**Issue by tucknology** [fuatakgun/kia_uvo#178]
**Region and Brand of car**
USA, Hyundai Santa Fe 2020

**Describe the bug**
I noticed this error in my `homeassistant.log` file, and there is no location reported in hassio. 

**Debug logs if an error occurred**
```
2021-11-24 10:03:47 ERROR (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Exception in update : 'vehicleLocation' - traceback: Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/Vehicle.py", line 64, in update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kia_uvo/Vehicle.py", line 129, in set_geocoded_location
    self.vehicle_data["vehicleLocation"][
KeyError: 'vehicleLocation'
```

**Expected behavior**
Maybe you need to handle the case where the `vehicleLocation` key isn't supplied?

**Screenshots**
<img width="474" alt="image" src="https://user-images.githubusercontent.com/19787615/143292718-58e4d343-8a90-4fd3-8fb1-608567db40c8.png">

**Comment by cdnninja** [comment]
Make sure geocoded location is disabled for now.   Once we have the data from the car I would think we can fix this one as well.  The Hyundai USA integration has received the least amount of work so far.

**Comment by cdnninja** [comment]
Are you able to replace the contents of your  HyundaiBlueLinkAPIusa.py file with the following?  Home Assistant will need to be restarted after.  This should resolve location.  

https://raw.githubusercontent.com/fuatakgun/kia_uvo/db2d2b957256fe1c8af01ae38acc3347eac75d1a/custom_components/kia_uvo/HyundaiBlueLinkAPIUSA.py

**Comment by tucknology** [comment]
Yes that fixed it, and I see the tire pressures now too. Awesome!

One detail about the location: it is about 50 miles off, and I think it might be because the gps coordinates are being rounded to the nearest integer. If it's possible to handle the value as a double or float the precision would improve.

I'm happy to help trying additional improvements, let me know what other data I can share. Thanks for this improvement!

**Comment by cdnninja** [comment]
Interesting!  Was the raw data in your integers?  The integration itself doesn't touch the GPS data from a rounding perspective.  Sounds like you know what you are doing so feel free to drop a PR at any point.  This is made of a few of us who started contributing to this.
