### ISSUE TITLE
Action Tracking left unfinished

### ISSUE THREAD

**Issue by dahlb** [fuatakgun/kia_uvo#187]
Hey @cdnninja sorry to say I'm leaving this project. It isn't moving at the pace I need. I need a stable integration for my kia in order to keep my car warm as the weather is already too cold for my toddler at the playground, and I am tired of leaving my car running for hours and assuming I'll track it down if it is stolen ...

The Action Tracking feature is not fully implemented which affects the USA and Canada implementations. I suggest you do one of the following to fix that.

either

1) revert 47ca3a1796910d2b6532b28673e06a9dae0f1c03 that would allow the integration's internal state to remain consistent but leaves the results of the api in a fire and forget with parallel action services failing with only HA logs to identify why they didn't work

2) merge https://github.com/fuatakgun/kia_uvo/pull/183 making any changes you want in a copy of the branch, this would allow the integration to fully handle the prevention of parallel action calls with script feedback and consistent internal state.

If you have any questions please @ me and I'll do my best to explain as I can

**Comment by fuatakgun** [comment]
thanks for summary @dahlb . If we do not take any quick action on this, is there a side effect or negative impact on users?

**Comment by fuatakgun** [comment]
apparently, he was serious on this: https://github.com/fuatakgun/kia_uvo/discussions/185#discussioncomment-1725639
it was his last interaction.

@cdnninja , do you know if we have to take any quick action on this?

**Comment by cdnninja** [comment]
I am thinking we close it.  It seems to work fine on my end.
