### ISSUE TITLE
On initial setup config: kia_uvo - Exception in update : 'evStatus' 

### ISSUE THREAD

**Issue by cdatwood** [fuatakgun/kia_uvo#189]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**Region and Brand of car**
Region: USA
Brand: KIA

**Describe the bug**
After initial install and setup configuration completion, integration fails when trying to start due to exception status in its update payload for evStatus. 

```
Logger: custom_components.kia_uvo.Vehicle
Source: custom_components/kia_uvo/Vehicle.py:81
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 9:43:24 AM (1 occurrences)
Last logged: 9:43:24 AM

kia_uvo - Exception in update : 'evStatus' - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update self.vehicle_data = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoAPIUSA.py", line 268, in get_cached_vehicle_status "atc": vehicle_status["evStatus"]["remainChargeTime"][0]["timeInterval"] KeyError: 'evStatus'
```

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.m

**To Reproduce**
1. Install from HACS
2. Go to Configuration -> Integrations, add UVO integration
3. Configure with username/password
4. See error in error log when add on attempts to start

**Expected behavior**

Should run and offer me the correct devices and entities

**Comment by cdnninja** [comment]
What version?  Could you try one older version?

**Comment by cdnninja** [comment]
Could you please try the code in https://github.com/fuatakgun/kia_uvo/pull/190 and see if it solves it?

**Comment by cdatwood** [comment]
@cdnninja I just made the file modification, let me spin it up and see if that corrects it. And for version, I was using the 1.2.0 branch from HACS.

**Comment by cdnninja** [comment]
Sounds good. Let me know once confirmed and I'll merge this fix.

**Comment by cdnninja** [comment]
I have merged this.  Please comment if it isn't resolved.
