### ISSUE TITLE
kia_uvo Exception in kia_uvo login

### ISSUE THREAD

**Issue by alexfd** [fuatakgun/kia_uvo#193]
Hello,
release 1.1.1 on  HA Core 2021.5.1. Filling in the account details, with Europe and Kia. I get this message: "Login failed into Kia Uvo / Hyundai Bluelink Servers. Please use official Kia Uvo app to logout and log back in and try again!"
And in the server logs I get:
```
ERROR (MainThread) [custom_components.kia_uvo.config_flow] kia_uvo Exception in kia_uvo login : unsupported operand type(s) for |: 'dict' and 'dict' - traceback: Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 106, in login
    self.authorization_code = self.get_authorization_code_with_redirect_url()
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 228, in get_authorization_code_with_redirect_url
    parsed_url = urlparse(response["redirectUrl"])
KeyError: 'redirectUrl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 155, in async_step_user
    self.token = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 108, in login
    self.authorization_code = self.get_authorization_code_with_form()
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 236, in get_authorization_code_with_form
    self.cookies = self.cookies | response.cookies.get_dict()
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
```
Anything I can try?

**Comment by alexfd** [comment]
I just purposely used an invalid password and the error message is the same. However when logging in to eu-account.kia.com or UVO app with same credentials, it works.
Password was reset two days ago...

**Comment by cdnninja** [comment]
Looks like you have an older version of python running.  This repo requires version 3.9 or later.   

What platform or method are you running home assistant on?

**Comment by alexfd** [comment]
I'm running it in docker, here's the docker-compose file:
```
version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:2021.5.1
```
docker exec home-assistant python -V
Python 3.8.9

Hmpf, I'll investigate which newer image has a 3.9.
Thanks for the help.

**Comment by cdnninja** [comment]
That version is 6 months old.   Lots has changed since. I would encourage you to go to latest.

**Comment by fuatakgun** [comment]
you are right @cdnninja , dict union operand is added in Python 3.9.

https://www.python.org/dev/peps/pep-0584/

**Comment by cdnninja** [comment]
@fuatakgun  Any option to adjust this code to support older python? I think this is the only item that needs 3.9 today in our code base.

**Comment by fuatakgun** [comment]
Yes there is, but next release of home assistant (2022.1) will be fully on python 3.9 and it is unavoidable for both security and performance perspective

**Comment by cdnninja** [comment]
Probably not worth changing if that's the case.  Let's close this one off.

**Comment by alexfd** [comment]
Appreciate your input guys, will update on my side no point changing code.

**Comment by fuatakgun** [comment]
Please keep us updated with outcome

**Comment by alexfd** [comment]
Success, is working after update. 🎉
