### ISSUE TITLE
Config not working right

### ISSUE THREAD

**Issue by HMvdZijden** [fuatakgun/kia_uvo#194]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
EU/Kia E-Niro

**Describe the bug**
The blackout start and end time in configuration are not saved properly.
fi. I set start time on 23 save open again it sits on 11, looks like 24 h mode is not supported
also:
Setting the checkbox off won't work on both cherkboxes.

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.m

**To Reproduce**
1. Go to config
2. Click on checkbox
3. Click on submit
3. Goto config again
4. checkbox is on

**Expected behavior**

**Screenshots**
![Schermafdruk 2021-12-01 14 42 28](https://user-images.githubusercontent.com/7892828/144245279-4cf25a35-07d3-462c-8102-2e6d62ddcea1.png) 23 start 5 stop
![Schermafdruk 2021-12-01 14 46 21](https://user-images.githubusercontent.com/7892828/144245936-fadbafd5-958d-466a-8a30-73448d1a9a80.png)  11 start 3 stop
![Schermafdruk 2021-12-01 14 50 26](https://user-images.githubusercontent.com/7892828/144246257-612fe9cb-623f-4a14-b974-314e055b9a73.png) checkboxes off (submit and config again.
![Schermafdruk 2021-12-01 14 52 12](https://user-images.githubusercontent.com/7892828/144246497-d5547890-189b-461d-96ad-f7efc7857c41.png)

Additional context**

**Comment by fuatakgun** [comment]
it is actually working and saving all the information. Background lines are showing default values and positions are showing saved values.

**Comment by fuatakgun** [comment]
and checkboxes does not matter actually :)

**Comment by fuatakgun** [comment]
hmmm, there is something weird, you are right, sorry for jumping into conclusion too fast

**Comment by fuatakgun** [comment]
I confirm that the values you put there are saved correctly but there is something wrong in presentation layer (ui)

**Comment by cdnninja** [comment]
I have noticed a few odd UI issues ever since the latest HA release.   The setup screen has text overlap etc. Not sure that is us or a HA bug.

**Comment by fuatakgun** [comment]
I also could not find the root cause but something is definitely weird on rendering part
