### ISSUE TITLE
Force Update time delta

### ISSUE THREAD

**Issue by badguy99** [fuatakgun/kia_uvo#20]
Only a minor thing, but the readme says the force update happens ever 2 hours. But currently the const for FORCE_SCAN_INTERVAL  is currently 240 minutes - so 4 hours. So I'm not sure if the const should be reduced to 120 mins or the readme updated?

**Comment by fuatakgun** [comment]
Thanks for raising this. My observations are like this;
- when car is in parking state, it is not updating its status regularly, so we need force update. For me, the most valuable data is charging rate on this stage.
- when car is moving, it is updating values regularly, so we don't need force update. For me, the most valuable data here is range/location.

Given all these, i was thinking that if car is not home, have 4 hours of force update interval but when car is back at home, have 2 hours of force intervals.

Please let me know what you think on this.

Lastly, you are right about conflict between readme and actual implementation.

**Comment by badguy99** [comment]
I was going to say it would be good if we could update every 30 minutes when charging. But then realized it could take up to 4 hours for the force update, to realise we've started charging in the first place >.<
I wonder how often we could hit force update before the servers get annoyed. Even updating hourly outside of blackout period doesn't seem too bad. That is only going to be 15 times a day, which isn't much really. But it depends on impact to car charge level by having it update more often, and limits imposed by Kia servers I guess.

**Comment by fuatakgun** [comment]
Makes sense, according to this page (not official), we can have 200 requests per day.

https://github.com/Hacksore/bluelinky/wiki/API-Rate-Limits

On the other hand, i have read in some forum pages that some users received a warning from Kia about excessive usage and threatening to shutting down the account, which we don't want to reach in any point.

Best is to create an integration options so user can adjust blackout hours, update and force update intervals. What do you think?

**Comment by badguy99** [comment]
That sounds good.

**Comment by m4n63** [comment]
Just chipping in on this, as it seems in my logs that the integration queries the service every 10 minutes.. 
```
2021-04-27 14:45:52 DEBUG (MainThread) [custom_components.kia_uvo] kia_uvo - Decide to make a force call 12 22 6
2021-04-27 14:55:52 DEBUG (MainThread) [custom_components.kia_uvo] kia_uvo - Decide to make a force call 12 22 6
2021-04-27 15:05:52 DEBUG (MainThread) [custom_components.kia_uvo] kia_uvo - Decide to make a force call 13 22 6
2021-04-27 15:15:52 DEBUG (MainThread) [custom_components.kia_uvo] kia_uvo - Decide to make a force call 13 22 6
2021-04-27 15:25:52 DEBUG (MainThread) [custom_components.kia_uvo] kia_uvo - Decide to make a force call 13 22 6
2021-04-27 15:35:52 DEBUG (MainThread) [custom_components.kia_uvo] kia_uvo - Decide to make a force call 13 22 6
```

**Comment by fuatakgun** [comment]
please get the latest code changes and let me know if it works for you.

**Comment by m4n63** [comment]
Update went fine for me, and log indicates it took my new custom values as expected:
```
DEBUG (MainThread) [custom_components.kia_uvo.config_flow] kia_uvo user input in option flow : {'unit_of_measurement': 1, 'scan_interval': 31, 'force_scan_interval': 121, 'no_force_scan_hour_start': 23, 'no_force_scan_hour_finish': 8}

```
So looking good here..

**Comment by fuatakgun** [comment]
> Update went fine for me, and log indicates it took my new custom values as expected:
> ```
> DEBUG (MainThread) [custom_components.kia_uvo.config_flow] kia_uvo user input in option flow : {'unit_of_measurement': 1, 'scan_interval': 31, 'force_scan_interval': 121, 'no_force_scan_hour_start': 23, 'no_force_scan_hour_finish': 8}
> 
> ```
> So looking good here..
> 
> 

Can you also try with lower values to be sure that they are effective?

**Comment by m4n63** [comment]
you mean something like this?
`kia_uvo user input in option flow : {'unit_of_measurement': 1, 'scan_interval': 29, 'force_scan_interval': 119, 'no_force_scan_hour_start': 23, 'no_force_scan_hour_finish': 8}`
will leave it running and see how it performs over the next couple of hours..

**Comment by fuatakgun** [comment]
closing this, please open if needed
