### ISSUE TITLE
Authentication without pasting in Username/Password

### ISSUE THREAD

**Issue by henrikbjorn** [fuatakgun/kia_uvo#200]
Personally I am not at all fund of entering my Password when I need an Extension or other 3rdparty app to authenticate against a service. Especially when the Hyundai login is a OAuth authentication solution.

So my feature request is for the Integration to use a normal OAuth 2.0 authentication flow.

**Comment by fuatakgun** [comment]
Hey, i checked for this and Hyundai or Kia don't allow third party access to use their oauth flow. 

If you can find a path forward, i would be more than happy to remove our dependency on all these stuff.

**Comment by henrikbjorn** [comment]
Have you tried writing to Bluelink or Hyundai? It seems that there are some services that deliver "efficient charging" that integrates with the cars.

**Comment by fuatakgun** [comment]
Nope, can you initiate this discussion and we can move further together?

**Comment by fuatakgun** [comment]
Resolving due to inactivity
