### ISSUE TITLE
climate not starting on my 2021 Kona Electric

### ISSUE THREAD

**Issue by zadigre** [fuatakgun/kia_uvo#215]
I have a 2021 Kona Electric. 
I'm in Canada.
the integration is loading fine. 
all sensor data are available. 
I can unlock/lock my doors through the integration with the service calls. 
but when I try to use the start_climate or stop_climate services, it does nothing.  

I don't see any error in the log... 
2021-12-20 08:41:49 DEBUG (SyncWorker_8) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - Received Pin validation response <Response [200]>
2021-12-20 08:41:52 DEBUG (SyncWorker_8) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - Received start_climate response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}}

I used this to start the service:
service: kia_uvo.start_climate
data:
  Temperature: 19
  Defrost: true
  Heating: true
  Duration: 10

I tried without or without duration. 
I also tried with/without defrost or heating. 

so it looks like Bluelink is receiving the command... but car doesn't react to this command.

I'm available to test if you want to diagnose this problem. 

(and thank you for your work on this integration and Eufy Security integration!)

**Comment by fuatakgun** [comment]
let's track this over here: https://github.com/fuatakgun/kia_uvo/issues/214
if you think they are not related, please comment back here

**Comment by zadigre** [comment]
ok will do. 
I wasn't sure because this thread was talking about 1.2.6... and your integration latest version is 1.2.4
I guess it will be updated in the next few version?
