### ISSUE TITLE
Exception kia_uvo login : 'redirectUrl'

### ISSUE THREAD

**Issue by kees1987** [fuatakgun/kia_uvo#22]
Hi,

Thanks for this integration, it looks promising!
I tried to install it, unfortunately it crashes after entering the login information with following exception:

ERROR (MainThread) [custom_components.kia_uvo.config_flow] kia_uvo Exception in kia_uvo login : 'redirectUrl'

Regards,

Kees

**Comment by fuatakgun** [comment]
Hi, 

Two possibilities ahead;
- assuming you are located in EU, you are using legacy UVO account, not yet migrated to Kia Account type. If that's the case, you can logout from UVO app, try to login again and migrate your account. 
- you are not located in Europe, so you are not using EU servers. If that's the case, you can help me to add the functionality to support other regions.

**Comment by kees1987** [comment]
Thanks!
I was not aware KIA was migrating accounts. Mine was not yet migrated.
After I did the migration everything works fine.

Kees

**Comment by Tailor4** [comment]
Hi,

Nice integration, congratulations,

I own two Kia cars with UVA (KIA connect soon) and everything works fantastic on Niro Car but the integration did not even detect Sorento Car. This is surprising since I started to use the integration with Sorento and after a while, we got the Niro car. Previously, integration was fine with Sorento,

Is there any issue/incompatibilty if you have 2 cars under the same account? could it be a problem of diferent servers from one car to the other?

Thank you!

BR

**Comment by dahlb** [comment]
@Tailor4 two cars are not currently supported, see https://github.com/fuatakgun/kia_uvo/issues/93

**Comment by Ricks88** [comment]
Hi, 

Today I created a new KIA Connect account. (inside of the kia connect app) i can login into the app and the website from kia connect.
But i can not login to the HA integration. Tried logging out and in again.
Error stays:
"Login failed into Kia Uvo / Hyundai Bluelink Servers. Please use official Kia Uvo app to logout and log back in and try again!"

**Comment by cdnninja** [comment]
Please open a new issue with region and brand detailed.  Please also confirm you have a car on your account.

**Comment by Ricks88** [comment]
> Please open a new issue with region and brand detailed. Please also confirm you have a car on your account.

Oops i did not added a car yet, maybe thats the problem for now..

**Comment by jjvandenberg** [comment]
Hi,
mine doesn't show zero (0,0) but an old ODO meter value from the past. i fixed it by adding an extra template var :

template:
  - sensor:
      - name: "kilometer_totaal"
        state: >
            {% if states.sensor.kilometer_totaal.state <  states.sensor.ev6_odometer.state %}
              {{ states.sensor.ev6_odometer.state | float }}
            {% endif %}
        state_class: total_increasing
        unit_of_measurement: km
        device_class: distance
        icon: mdi:speedometer

You can force un update from the couch by remote starting the car and after a few seconds pull an update. 
This wil give you the currrent odo meter settings. then turn of the car with the remote.
