### ISSUE TITLE
Start Climate Control

### ISSUE THREAD

**Issue by Symbiot78** [fuatakgun/kia_uvo#226]
In the bluelink app we can start and stop climate control.

this would be a very nice feature to add.

**Comment by cdnninja** [comment]
That is supported today with the start_climate and stop_climate service commands.

**Comment by Symbiot78** [comment]
That's fantastic news. 
when you say service commands.. where would you find/use those (sorry if it's obvious to everyone but me)
![Skærmbillede 2021-12-30 210137](https://user-images.githubusercontent.com/3314249/147784543-d1a755a4-ed17-44f4-8a72-aa046d6fb928.png)

**Comment by Symbiot78** [comment]
step 1. read documentation properly
step 2. find out that services are under "developer tools".
step 3. feel like a lump :-)

**Comment by cdnninja** [comment]
All good! You can also tie this to any automation.  like google assistant!

**Comment by spacecowboy** [comment]
Still, it would be nice to have these show up under Controls in the screenshot. Now it's a bit of a pain to setup up even a button to call these services

**Comment by fuatakgun** [comment]
if you go to developer tools and select kia_uvo.start_climate service, you can see all variables and their description there and you can generate example yaml code to use inside automation or button.

![Screenshot_2022-01-04-22-24-44-286_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/11085566/148125820-a6021edd-6f7d-4208-8654-cd0eb514498e.jpg)

**Comment by Symbiot78** [comment]
> Still, it would be nice to have these show up under Controls in the screenshot. Now it's a bit of a pain to setup up even a button to call these services

It would be nice.. but it literally takes 30 seconds to create a button to call the service.

**Comment by spacecowboy** [comment]
> > Still, it would be nice to have these show up under Controls in the screenshot. Now it's a bit of a pain to setup up even a button to call these services
> 
> It would be nice.. but it literally takes 30 seconds to create a button to call the service.

Depends on how familiar you are with HomeAssistant.

Why does door unlock get special treatment? That's pretty much the last action I'd want to take. Handling climate and charging seems far more useful.

**Comment by fuatakgun** [comment]
There are some existing entity types in home assistant light switches, switches, locks, location etc. if we can use them for representation, they receive special treatment as door lock :-) but trust me, there is nothing we can represent car climate options now :-)

Or we have to create a new entity type as climate control (?) and we can have a special treatment for it too.

On the other hand, thermostat (climate) might be half representing it but not all.

**Comment by spacecowboy** [comment]
Anyway, this is hardly the integrations fault. Which is great work btw.

It's more of a complaint against HomeAssistant's complexity and badly organised documentation.
