### ISSUE TITLE
Please, create integration for Hyundai Bluelink Brazil

### ISSUE THREAD

**Issue by valsesia** [fuatakgun/kia_uvo#228]
Could you please create the integration for Hyundai Brasil cars as well? I have a new Crete with the Bluelink system built in.

**Comment by cdnninja** [comment]
Is this something you could help with?  The key for this is someone needs to sniff the traffic to get us how it connects and the endpoints.

**Comment by cdnninja** [comment]
@valsesia Is this something you would be interested in helping us through?

**Comment by cdnninja** [comment]
Since non of us have access to a car in Brazil I will close this for now.  Please comment if you or others could assist in getting us the data we need.
