### ISSUE TITLE
Error login

### ISSUE THREAD

**Issue by williamgeurts** [fuatakgun/kia_uvo#23]
Hi, thanks for inventing this integration. I tried it but I get this message in the logging during integration (after entering username and password):
Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:46 
Integration: Kia Uvo (documentation) 
First occurred: 10:01:22 PM (3 occurrences) 
Last logged: 10:03:14 PM

kia_uvo Exception in kia_uvo login : 'redirectUrl'

I login from Nederland. Can you help me?

William

**Comment by fuatakgun** [comment]
Hey William please take a look at this, you might be having the same issue. https://github.com/fuatakgun/kia_uvo/issues/22

**Comment by williamgeurts** [comment]
Thanks, thats loves the issue. Great job Fuatakgun
