### ISSUE TITLE
Bluelink Location Requires Pin

### ISSUE THREAD

**Issue by nswint** [fuatakgun/kia_uvo#232]
Does the. bluelinkServicePin or Pin Token need to be added to retrieve the location?  It worked in previous version but   v1.2.0 I believe was the last that worked.

This error originated from a custom integration.

Logger: custom_components.kia_uvo.HyundaiBlueLinkAPIUSA
Source: custom_components/kia_uvo/HyundaiBlueLinkAPIUSA.py:282 
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues) 
First occurred: January 2, 2022, 11:59:25 AM (2 occurrences) 
Last logged: 12:32:15 PM

kia_uvo - Unable to get vehicle location: {'errorSubCode': 'C400_1', 'systemName': 'IDM', 'functionName': 'validatePIN', 'errorSubMessage': 'Missing Fields: blueLinkServicePin or pinToken', 'errorMessage': 'Please check to see that all required fields are populated and try again.', 'errorCode': 400, 'serviceName': 'CheckCustomerUserPin'}

**Comment by cdnninja** [comment]
Could you revert version and let us know what version still works?

**Comment by cdnninja** [comment]
@nswint I wanted to follow up to see if you plan to check the previous version?

**Comment by cdnninja** [comment]
Closing since no response.  Please let us know if this is ongoing.
