### ISSUE TITLE
After update: Setup failed for kia_uvo: Integration not found.

### ISSUE THREAD

**Issue by maartenhendrix** [fuatakgun/kia_uvo#238]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
EU Kia eniro

**Describe the bug**
After update to latest release (1.3.0) I get integration not found. 

**Debug logs if an error occurred**
Logger: homeassistant.setup
Source: setup.py:153 
First occurred: 10:36:26 AM (1 occurrences) 
Last logged: 10:36:26 AM

Setup failed for kia_uvo: Integration not found.

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.m

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by maartenhendrix** [comment]
Rolling back to 1.2.7 makes it work again

**Comment by fuatakgun** [comment]
We recently added a new feature which is available inside HA in recent versions (not sure).

What is your HA version?

**Comment by maartenhendrix** [comment]
I’m also running ha 2021.12.8 hacs 1.19.1

**Comment by maartenhendrix** [comment]
I updated again and now it work so might have been a glitch.
Thanks for your help.

**Comment by fuatakgun** [comment]
Edit: it is an issue coming from HACS and seems to be resolved.

https://github.com/hacs/integration/issues/2437
