### ISSUE TITLE
Last Update: 

### ISSUE THREAD

**Issue by williamgeurts** [fuatakgun/kia_uvo#24]
Hi,
I get an Invalid Timestamp in the last update field. I attach screen dumps to show the values.
![lastupdate](https://user-images.githubusercontent.com/34502921/116716923-9b643d80-a9d8-11eb-90c8-38d070c4fa48.jpg)

A dump of 2 screens:
1. The Frontend UI showing Invalid Timestamp
2. The data from binary_sensor.niroev20_data

![last_update_1](https://user-images.githubusercontent.com/34502921/116717963-c307d580-a9d9-11eb-831c-9997a00489a5.jpg)
The data from sensor.niroev20_last_update

Is it my setup, the local parameter or ....

**Comment by m4n63** [comment]
I have a similar experience in my setup *sometimes*. Not able to find a pattern so far (right now it shows fine for me)
![image](https://user-images.githubusercontent.com/58000142/116723216-8dfe8180-a9df-11eb-8870-3743ac2162c7.png)

Also experience that the API sometimes returns 0 when my EV battery is full instead  of 100, so it could be that the UVO API is a bit inconsistent at times perhaps.

**Comment by williamgeurts** [comment]
Both the App and Safari.

Met vriendelijke groet,

William Geurts

**Comment by badguy99** [comment]
I get the same on my iphone with the app and on Safari, but it is fine with Firefox and Chrome on Windows 10. So I think it may be related to webkit handling of the dates.

**Comment by fuatakgun** [comment]
I believe the issue is about missing 'T' letter between time and time zone. I have never had similar issue myself about invalid timestamp but i will try to fix this using this as an example.

https://community.home-assistant.io/t/entities-format-date-invalid/192529/3

**Comment by badguy99** [comment]
It is, I just used the set state in the developer tools to confirm - you get a few seconds to check before it reverts to not having it.

**Comment by fuatakgun** [comment]
Thanks @badguy99  for the fix. @williamgeurts can you please check latest version and let us know the results?

**Comment by williamgeurts** [comment]
Hi, Yes the date is fixed. It show 25 minutes ago (at this moment). Thanks for the quick fix and in general for making this great integration. Great job. 



Met vriendelijke groet,

William Geurts
