### ISSUE TITLE
Use "EV Battery" for device instead of "Car Battery" for EVs

### ISSUE THREAD

**Issue by henrikbjorn** [fuatakgun/kia_uvo#240]
I think the title says it all.

When using the integration with an EV such as IONIQ 5, the device shows battery as 88% which is the 12v battery and not the EV battery, which is way more interesting for EV cars.

**Comment by fuatakgun** [comment]
and there is no way to resolve this :) home assistant is picking itself to decide the `probable related battery` sensor.

I believe it was not meant to be two different battery sensors for a given device but here we have.

**Comment by henrikbjorn** [comment]
> and there is no way to resolve this :) home assistant is picking itself to decide the `probable related battery` sensor.
> 
> I believe it was not meant to be two different battery sensors for a given device but here we have.

It dosen't just chose the first returned battery sensor for the integration?

**Comment by fuatakgun** [comment]
We earlier tried to rename sensors to change orders and it didn't help.

**Comment by cdnninja** [comment]
> > and there is no way to resolve this :) home assistant is picking itself to decide the `probable related battery` sensor.
> > I believe it was not meant to be two different battery sensors for a given device but here we have.
> 
> It dosen't just chose the first returned battery sensor for the integration?

It does - alphabetically.  Mentioned here: https://github.com/fuatakgun/kia_uvo/issues/54#issuecomment-919913851

Only real fix would be a bug to the Home Assistant core team I believe.  Maybe renaming locally will fix it for you though?

**Comment by fuatakgun** [comment]
this is not working anymore, at least, in my machine.

@henrikbjorn , have you tried this?

**Comment by henrikbjorn** [comment]
> this is not working anymore, at least, in my machine.
> 
> @henrikbjorn , have you tried this?

Does not work for me.

**Comment by hmmbob** [comment]
Ah, I was just about to create a new issue for this.

Just adding a screenshot for reference:

![image](https://user-images.githubusercontent.com/33529490/194053977-6b83266a-abad-49db-af39-27ba5a65934e.png)

**Comment by hmmbob** [comment]
Ok, I did find a way to force this, but it isn't necessarily pretty.... HA [uses the `device_class: battery` as the selection criteria for the battery sensor](https://github.com/home-assistant/frontend/blob/2015da8fd2441882b352af1666133833fafaa856/src/data/entity_registry.ts#L67-L75) in the top right of the device panel. We can't communicate to HA to use a specific sensor for this (in this case: which of the 2 to use), but we can influence how many battery sensors we provide to HA to select from... By having the 12V battery not having the battery device class, only 1 sensor with this device_class will be present.

So from this:

https://github.com/fuatakgun/kia_uvo/blob/bbeebeb70cee1c357f634c01e63ab388efc3d97d/custom_components/kia_uvo/sensor.py#L271-L281

to this:

```py
    INSTRUMENTS.append(
        (
            "carBattery",
            "Car Battery",
            "vehicleStatus.battery.batSoc",
            PERCENTAGE,
            "mdi:car-battery",
            None,
            None,
        )
    )
```
Runs fine here! As you can see in below screenshot, HA now does select the correct entity automatically:
![image](https://user-images.githubusercontent.com/33529490/194061756-0dd8b3d7-8be7-43b5-8c57-4ff13e2b7a09.png).

I am not sure if this also influences they way are displayed for vehicles without an EV battery (are any of those supported by this component?). If IC-only vehicles _are_ supported by this component, probably this sensor might need to be wrapped in an if-statement or so, as this will be the only battery the vehicle has and so it is no problem using it ;-)

```py
 if vehicle.engine_type is VEHICLE_ENGINE_TYPE.IC:
```

**Comment by cdnninja** [comment]
IC engines are supported by this integration so would need to handle this.  Are you able to try test out an if statement and if you can get it working on the EV side drop a PR? Ideally do this on the 2.0 branch so we don't loose this enhancement.

**Comment by hmmbob** [comment]
PR for master branch is ready - for 2.0 I couldn't see how to differentiate between vehicle engine types? Looks like `VEHICLE_ENGINE_TYPE` is no longer a constant?

**Comment by cdnninja** [comment]
> 

It is located here. https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/tree/master/hyundai_kia_connect_api  the vehicle file has an engine type and a constant file I believe.

**Comment by hmmbob** [comment]
I had a look, but no clue on how to make this work in the new code of 2.0.

**Comment by hmmbob** [comment]
Thinking about this a bit more.... We could opt to make the generic battery a sensor with BATTERY deviceclass for all vehicle types, as there is no way for normal users to influence that state of charge anyway. As in: why should we present it as the device battery? 

All EV vehicles need to show the EV battery anyways, and for the IC variant I actually do not really see the added value of having the 12V battery percentage as device battery info.

**Comment by cdnninja** [comment]
Only value would be if someone has automations that alert on any low battery.   It would auto include the car.  This is a pretty edge use case though.    It is unfortunate HA doesn't allow us to set the default battery.  The other reason would be if we ever try to get into a default integration.  They are pretty strict on following rules but we tried that once already without much progress.  Custom is how this integration will most likely remain.   

I am good with this adjustment you suggest of just changing the type. Are you able to drop PRs for it for both versions?

**Comment by hmmbob** [comment]
Sure.

#406 
#409
