### ISSUE TITLE
New sensors to be added

### ISSUE THREAD

**Issue by marian-gavornik** [fuatakgun/kia_uvo#242]
**Is your feature request related to a problem? Please describe.**
I am missing some sensors, which are being fetched in data sensor, but can not be used

**Describe the solution you'd like**
Enhance the integration to add following sensors: 
  smartKeyBatteryWarning
  fuelLevel
  washerFluidStatus
  breakOilStatus

Example from log: 
  smartKeyBatteryWarning: false
  fuelLevel: 22
  washerFluidStatus: false
  breakOilStatus: false

**Describe alternatives you've considered**
No alternative I am aware of.

**Comment by fuatakgun** [comment]
Please share your full data attribute.

**Comment by marian-gavornik** [comment]
Hello @fuatakgun , 
here you are as requested: 

vehicle_data: 
vehicleLocation:
  coord:
    lat: 48.074664
    lon: 17.279314
    alt: 0
    type: 0
  head: 146
  speed:
    value: 0
    unit: 0
  accuracy:
    hdop: 0
    pdop: 0
  time: '20220111141818'
  geocodedLocation:
    place_id: 112335879
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: way
    osm_id: 39857332
    lat: '48.07468214042268'
    lon: '17.279306481474197'
    display_name: >-
      Lipová, Jánošíková, Dunajská Lužná, okres Senec, Bratislavský kraj, 900
      42, Slovensko
    address:
      road: Lipová
      suburb: Jánošíková
      city_district: Jánošíková
      village: Dunajská Lužná
      county: okres Senec
      state: Bratislavský kraj
      postcode: 900 42
      country: Slovensko
      country_code: sk
    boundingbox:
      - '48.0737011'
      - '48.0753992'
      - '17.2769635'
      - '17.2798572'
vehicleStatus:
  airCtrlOn: false
  engine: false
  doorLock: true
  doorOpen:
    frontLeft: 0
    frontRight: 0
    backLeft: 0
    backRight: 0
  trunkOpen: false
  airTemp:
    value: 00H
    unit: 0
    hvacTempType: 1
  defrost: false
  lowFuelLight: false
  acc: false
  hoodOpen: false
  steerWheelHeat: 0
  sideBackWindowHeat: 0
  dte:
    value: 685
    unit: 1
  tirePressureLamp:
    tirePressureLampAll: 0
  seatHeaterVentState:
    frSeatHeatState: 2
    flSeatHeatState: 2
    rlSeatHeatState: 2
    rrSeatHeatState: 2
  battery:
    batSoc: 100
    batState: 0
    sjbDeliveryMode: 1
    batSignalReferenceValue:
      batWarning: 0
    powerAutoCutMode: 2
  lampWireStatus:
    stopLamp:
      stopLampStatus: false
      leftLamp: false
      rightLamp: false
    headLamp:
      headLampStatus: false
      leftLowLamp: false
      rightLowLamp: false
      leftHighLamp: false
      rightHighLamp: false
      leftBifuncLamp: false
      rightBifuncLamp: false
    turnSignalLamp:
      turnSignalLampStatus: false
      leftFrontLamp: false
      rightFrontLamp: false
      leftRearLamp: false
      rightRearLamp: false
  windowOpen:
    frontLeft: 0
    frontRight: 0
    backLeft: 0
    backRight: 0
  smartKeyBatteryWarning: false
  fuelLevel: 100
  washerFluidStatus: false
  breakOilStatus: false
  sleepModeCheck: false
  time: '20220111141821'
  remoteWaitingTimeAlert:
    remoteControlAvailable: 1
    remoteControlWaitingTime: 168
    elapsedTime: '06:43:48'
  systemCutOffAlert: 0
  tailLampStatus: 0
  hazardStatus: 0
odometer:
  value: 15231.5
  unit: 1

**Comment by cdnninja** [comment]
What is break oil status?   At first I thought Brake fluid but that would be terrible wording in the API.  Is it actually oil status?

**Comment by cdnninja** [comment]
@marian-gavornik  Could you give the above pull request code a try? You will manually need to edit the files in your local install.

**Comment by marian-gavornik** [comment]
Hello @cdnninja , 
all is working as expected! 
Thank you very much. Will be this included in update?
![Snímka obrazovky 2022-01-12 o 21 38 18](https://user-images.githubusercontent.com/96845407/149217954-37cf47a7-47cb-4b2b-9600-e5811faac8e1.png)

**Comment by marian-gavornik** [comment]
> What is break oil status? At first I thought Brake fluid but that would be terrible wording in the API. Is it actually oil status?

I believe that this is indication of low oil level. But can not confirm

**Comment by cdnninja** [comment]
> > What is break oil status? At first I thought Brake fluid but that would be terrible wording in the API. Is it actually oil status?
> 
> 
> 
> I believe that this is indication of low oil level. But can not confirm 

Any way in app to check for this? If we don't know what it is I don't know the value of adding it.

**Comment by cdnninja** [comment]
Merged the other sensors.  Let me know if you have details on oil and can add later.  Otherwise I can close this.

**Comment by cdnninja** [comment]
I will close for now.  Please reopen if you find more detail.
