### ISSUE TITLE
I can't add repository

### ISSUE THREAD

**Issue by ThibautBascoulergue** [fuatakgun/kia_uvo#250]
Hello,

I want to add this addon but i have an error.
![image](https://user-images.githubusercontent.com/42678960/149548831-b9502a4e-82b7-419c-b3fc-d8eba7132123.png)

Thx.

**Comment by cdnninja** [comment]
It is listed as a default repo in HACS.  Please make sure you are using HACS and not the add on section.

**Comment by fuatakgun** [comment]
The screenshot is from add-on store page.
