### ISSUE TITLE
Sensor FuelLevel: wrong device class of DEVICE_CLASS_TEMPERATURE

### ISSUE THREAD

**Issue by ericvb** [fuatakgun/kia_uvo#252]
Latest version of the integration: 1.4.0
EU region
Hyundai Santa Fe plugin Hybride

Home Assistant Statistics tab in Developer Tools is complaining about the sensor Fuel Level.
```
The unit ('%') of this entity doesn't match a unit of device class 'temperature'.

Unsupported unit
The unit of your entity is not a supported unit for the device class of the entity, temperature.
Statistics can not be generated until this entity has a supported unit.

If this unit was provided by an integration, this is a bug. Please report an issue.

If you have set this unit yourself, and want to have statistics generated, make sure the unit matches the device class. The supported units are documented in the developer documentation.
```

The error is related to this enhancement : https://github.com/fuatakgun/kia_uvo/pull/244
The code was added on 14 january in the file sensor.py.
```
    INSTRUMENTS.append(
        (
            "fuelLevel",
            "Fuel Level",
            "vehicleStatus.fuelLevel",
            PERCENTAGE,
            "mdi:fuel",
            DEVICE_CLASS_TEMPERATURE,
            SensorStateClass.MEASUREMENT,
        )
```
The problem when I read the HA development docs https://developers.home-assistant.io/docs/core/entity/sensor/#available-device-classes, I don't see a corresponding device class...
Setting None then?

**Comment by fuatakgun** [comment]
Hood catch, thanks, we should not define a device class for this
