### ISSUE TITLE
Region Europe missing

### ISSUE THREAD

**Issue by fwestenberg** [fuatakgun/kia_uvo#254]
Thanks for this integration, I would love to use it. Unfortunately I cannot logon to the Hyundai Bluelink server (it works in the Bluelink app). I am located Europe, which region should I choose? 

![IMG_20220117_084628](https://user-images.githubusercontent.com/47930023/149728652-6f21905e-b7dc-4074-9aac-794b9c2d2779.jpg)

**Comment by fuatakgun** [comment]
This is the wrong integration, please uninstall this and install Kia Uvo / Hyundai Bluelink from HACS.

**Comment by fwestenberg** [comment]
My mistake! I didn't realize there are two repositories. I just switched to your one! Thanks!
