### ISSUE TITLE
Range by EV no longer works

### ISSUE THREAD

**Issue by tobiasbrage** [fuatakgun/kia_uvo#255]
From one day to another the "Range by EV" entity stopped working and just shows 0 and the message "0 Not Applicable".

**Comment by cdnninja** [comment]
Which region and brand? 

Could we get the data entity contents with masked personal info like location?

**Comment by tobiasbrage** [comment]
Sorry, Hyundai And EU region.

![Skærmbillede 2022-01-17 kl  20 58 16](https://user-images.githubusercontent.com/78112590/149830835-f82066d8-0d5e-4b3b-86d0-3f5100239a29.png)

**Comment by tobiasbrage** [comment]
It works now. I uninstalled the integrations completely and downloaded an earlier version where it still didn't work. I then updated the integration through HACS once again and suddenly it worked.
I don't know if the Hyundai servers were down or responding with wrong data from the API but I guess I'll make a custom server with some math calculating the range by the vehicle based on the outside temperature just in case it stops working again.

**Comment by tobiasbrage** [comment]
The error started occurring again.

**Comment by fuatakgun** [comment]
Please dump your data sensor here from developer tools page, we need details of api response, which is captured there.

**Comment by Symbiot78** [comment]
@tobiasbrage  - try running the "force update" service_call. it could be bluelink acting up (lots of post on Danish FB pages about unstable bluelink)
also.. is your sensor-screenshot cropped? you're missing a bunch of sensor data (tire pressure for each wheel) or is this list just your curated list of info? have you updated to latest version?

**Comment by tobiasbrage** [comment]
Thanks for commenting.
It's been working without any issues since my last comment over a day ago.
I'm hoping it was just the BlueLink servers acting up, my BlueLink profile picture disappeared around the same time period.

Is it just a rest API? If so can anyone share the url so I can have a look at the API myself?

**Comment by fuatakgun** [comment]
@tobiasbrage , we need your data dump when issue happens again.

**Comment by tobiasbrage** [comment]
Will do, thanks.

**Comment by fuatakgun** [comment]
![image](https://user-images.githubusercontent.com/11085566/150117770-e3e9d771-bc92-4948-ac96-a7587f38ae64.png)
