### ISSUE TITLE
Entity not available error

### ISSUE THREAD

**Issue by pfish3r** [fuatakgun/kia_uvo#256]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
EMEA - Kia

**Describe the bug**
after a recent update the none binary sensors are not available.  I have disabled, delete, reinstalled plug in etc

**Debug logs if an error occurred**
Logger: homeassistant.setup
Source: setup.py:316
First occurred: 17 January 2022, 17:27:17 (1 occurrences)
Last logged: 17 January 2022, 17:27:17

Unable to prepare setup for platform kia_uvo.sensor: Platform not found (cannot import name 'SensorStateClass' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)).

**Screenshots**

![2022-01-19_11-31-29](https://user-images.githubusercontent.com/77079294/150122557-748ddcc1-96d8-432a-83e2-69fa7180777a.png)

**Comment by fuatakgun** [comment]
Your home assistant version should be old
