### ISSUE TITLE
Add percentage power left in battery

### ISSUE THREAD

**Issue by Symbiot78** [fuatakgun/kia_uvo#258]
pretty much as title.

Add the percentage of power left on the car. (kidda like the guess-o-meter feature request.

**Comment by cdnninja** [comment]
Please provide the region, brand and data entity of your car.  I thought battery percentage was already a sensor so this may be a bug.

**Comment by Symbiot78** [comment]
sry.. :
Europe/DK
Hyundai Ioniq 5
Not sure what you mean by data entity?

I think it actually did have percentage in the first version I installed a few weeks ago.. but unsure.

**Comment by cdnninja** [comment]
Data from the data sensor when you browse to developer tools and states tab.  This is the raw API response.

**Comment by Symbiot78** [comment]
this is the output.
I removed geolocation stuff - but everything else is there.

`
vehicle_data:
  vehicleLocation:
    coord:
      lat: xx.969533
      lon: x.637092
      alt: 0
      type: 0
    head: 271
    speed:
      value: 0
      unit: 0
    accuracy:
      hdop: 0
      pdop: 0
    time: '20220121062732'
    vehicleStatus:
    airCtrlOn: true
    engine: true
    doorLock: true
    doorOpen:
      frontLeft: 0
      frontRight: 0
      backLeft: 0
      backRight: 0
    trunkOpen: false
    airTemp:
      value: 18H
      unit: 0
      hvacTempType: 1
    defrost: false
    acc: true
    evStatus:
      batteryCharge: false
      batteryStatus: 67
      batteryPlugin: 0
      remainTime2:
        etc1:
          value: 36
          unit: 1
        etc2:
          value: 440
          unit: 1
        etc3:
          value: 130
          unit: 1
        atc:
          value: 0
          unit: 1
      drvDistance:
        - rangeByFuel:
            evModeRange:
              value: 208
              unit: 1
            totalAvailableRange:
              value: 208
              unit: 1
          type: 2
      reservChargeInfos:
        reservChargeInfo:
          reservChargeInfoDetail:
            reservInfo:
              day:
                - 0
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
              time:
                time: '0810'
                timeSection: 0
            reservChargeSet: true
            reservFatcSet:
              defrost: false
              airTemp:
                value: 12H
                unit: 0
              airCtrl: 0
              heating1: 0
        offpeakPowerInfo:
          offPeakPowerTime1:
            starttime:
              time: '1200'
              timeSection: 0
            endtime:
              time: '0600'
              timeSection: 0
          offPeakPowerFlag: 2
        reserveChargeInfo2:
          reservChargeInfoDetail:
            reservInfo:
              day:
                - 0
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
              time:
                time: '0700'
                timeSection: 0
            reservChargeSet: false
            reservFatcSet:
              defrost: false
              airTemp:
                value: 12H
                unit: 0
              airCtrl: 0
              heating1: 0
        reservFlag: 0
        ect:
          start:
            day: 0
            time:
              time: '0000'
              timeSection: 0
          end:
            day: 0
            time:
              time: '0000'
              timeSection: 0
        targetSOClist:
          - targetSOClevel: 90
            dte:
              rangeByFuel:
                evModeRange:
                  value: 336
                  unit: 1
                totalAvailableRange:
                  value: 336
                  unit: 1
              type: 2
            plugType: 1
          - targetSOClevel: 90
            dte:
              rangeByFuel:
                evModeRange:
                  value: 336
                  unit: 1
                totalAvailableRange:
                  value: 336
                  unit: 1
              type: 2
            plugType: 0
      chargePortDoorOpenStatus: 2
      batteryPreconditioning: false
    ign3: true
    hoodOpen: false
    steerWheelHeat: 0
    sideBackWindowHeat: 0
    tirePressureLamp:
      tirePressureLampAll: 0
      tirePressureLampFL: 0
      tirePressureLampFR: 0
      tirePressureLampRL: 0
      tirePressureLampRR: 0
    battery:
      batState: 1
      sjbDeliveryMode: 1
      batSignalReferenceValue:
        batWarning: 65
      powerAutoCutMode: 2
    lampWireStatus:
      stopLamp:
        stopLampStatus: false
        leftLamp: false
        rightLamp: false
      headLamp:
        headLampStatus: false
        leftLowLamp: false
        rightLowLamp: false
        leftHighLamp: false
        rightHighLamp: false
        leftBifuncLamp: false
        rightBifuncLamp: false
      turnSignalLamp:
        turnSignalLampStatus: false
        leftFrontLamp: false
        rightFrontLamp: false
        leftRearLamp: false
        rightRearLamp: false
    smartKeyBatteryWarning: false
    washerFluidStatus: false
    breakOilStatus: false
    sleepModeCheck: false
    time: '20220121062733'
    remoteWaitingTimeAlert:
      remoteControlAvailable: 1
      remoteControlWaitingTime: 168
      elapsedTime: '00:00:00'
    systemCutOffAlert: 0
    tailLampStatus: 0
    hazardStatus: 0
  odometer:
    value: 7161.8
    unit: 1
vehicle_name: IONIQ 5
friendly_name: IONIQ 5 Data
`

**Comment by fuatakgun** [comment]
You should already have a sensor as ev_battery as your data has this information

**Comment by cdnninja** [comment]
@Symbiot78  any update?

**Comment by Symbiot78** [comment]
yes.
found it under entities. 
It was just not added automatically to my overview and didn't think to look for it under the integration/entities.

As far as I know I did not remove it from the overview dashboard and I am 100% sure it used to be there.

**Comment by cdnninja** [comment]
Awesome - let us know if you have other issues.
