### ISSUE TITLE
Error installation prevents services from being set up

### ISSUE THREAD

**Issue by tomlittle** [fuatakgun/kia_uvo#259]
I have semi-successfully installed the integration. The message :
  _The following integrations and platforms could not be set up:
  kia_uvo.sensor
  Please check your config and logs._
appears after the installation.

Checking the log provides some detail:
  _Logger: homeassistant.setup
  Source: setup.py:316
  First occurred: 20 January 2022, 14:48:38 (1 occurrences)
  Last logged: 20 January 2022, 14:48:38
  Unable to prepare setup for platform kia_uvo.sensor: Platform not found (cannot import name 'SensorStateClass' from 'homeassistant.components.sensor' (/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/sensor/__init__.py))._

I am running 2021.11.5 installed as Home Assistant Core.

Any ideas?

Thanks,
Tom

**Comment by fuatakgun** [comment]
You have to update your home assistant at least December release

**Comment by tomlittle** [comment]
Thanks for the quick response! I'll do that, re-install and let you know how it goes.Tomorrow, probably.

**Comment by tomlittle** [comment]
It worked, thanks again. The upgrade is causing other problems, but nothing to do with the Kia integration. Great stuff!
