### ISSUE TITLE
Failed to set up 

### ISSUE THREAD

**Issue by yonigold1** [fuatakgun/kia_uvo#262]
Hello ive had this plugin working for a while and just this morning i woke up and saw that it says:
<img width="287" alt="Screen Shot 2022-01-22 at 1 20 26 PM" src="https://user-images.githubusercontent.com/34217684/150650797-7fbba7dc-7d3e-459c-b07f-c5ed459a8452.png">
 ive tried everything to fix it (Reinstall, redownload from hacs, log out and log in, and rebooting my host machine, and restoring a backup from a time that it did work) nothing has fixed it. 

If someone could help me that would be greatly appreciated.

**Comment by fuatakgun** [comment]
We need first error logs, if they are not helpful than debug logs.

**Comment by yonigold1** [comment]
These are the logs let me know if you need anything else :)
<img width="821" alt="Screen Shot 2022-01-22 at 3 43 13 PM" src="https://user-images.githubusercontent.com/34217684/150654750-e38495ad-171b-4b19-8e48-d3bc2b75de90.png">
<img width="1295" alt="Screen Shot 2022-01-22 at 3 43 29 PM" src="https://user-images.githubusercontent.com/34217684/150654756-a78fb1e6-a22b-40ca-8aa0-361e38cac6af.png">

**Comment by fuatakgun** [comment]
What is region and brand?

**Comment by yonigold1** [comment]
Canada and a Hyundai Santa Fe 2019

**Comment by cdnninja** [comment]
Could you enable debug logging and post the logs from prior to this error?  This typically means something went wrong grabbing the car details.

**Comment by yonigold1** [comment]
How do i enable debug logging? Im a bit of a noob lol

**Comment by cdnninja** [comment]
Very bottom of the page here: https://github.com/fuatakgun/kia_uvo

**Comment by yonigold1** [comment]
i've just discovered that my bluelink app isn't working either so i think it has to do with bluelink or it's an issue with my car. I'm going to call bluelink tomorrow and see what the issue is.

**Comment by fuatakgun** [comment]
Thanks for update, good luck with that
