### ISSUE TITLE
Integration "Failed to set up"

### ISSUE THREAD

**Issue by Adams-Scott** [fuatakgun/kia_uvo#267]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
USA - Kia - Niro EV

**Describe the bug**
The integration fails on startup. The integration on the integration page says "Failed to setup, check the logs".

I wish I could give a more exact time frame, but this has been happening for at least a couple of weeks. It used to work wonderfully.

**Debug logs if an error occurred**
I've enabled verbose logging.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/kia_uvo/__init__.py", line 217, in async_setup_entry
    await update(dt_util.utcnow())
  File "/config/custom_components/kia_uvo/__init__.py", line 206, in update
    datetime.now(local_timezone) - vehicle.last_updated
TypeError: can't subtract offset-naive and offset-aware datetimes
```

```
kia_uvo - Exception in update : 'distanceToEmpty' - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update self.vehicle_data = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoAPIUSA.py", line 282, in get_cached_vehicle_status vehicle_status["dte"] = vehicle_status["distanceToEmpty"] KeyError: 'distanceToEmpty'
```

**To Reproduce**
1. Install addon via hacs
2. Add integration via gui
3. :(

**Additional context**
I've tried:
- Restarting
- Removing the integration, removing the addon, then adding it back.
- Using an older version (1.2.7)
- Verifying the password is correct. I've tried using a bogus password and the integration catches it.

I can create a test HA instance to see if I still have the issue, but I thought I would post here first.

This may be related to #264.

Thanks for any help you can provide!

**Comment by cdnninja** [comment]
Since you have an EV it looks like you don’t have distance to empty reported.  Should be a quick fix on our end.  

I’ll write a fix later tonight.

**Comment by Adams-Scott** [comment]
Great! I'm not in any rush so take your time. Thanks!

**Comment by cdnninja** [comment]
Could you manually copy the modified file in #268 to test the fix?  If it works I will merge to the latest release.

**Comment by Adams-Scott** [comment]
It worked! The integration loads and I don't have any error messages in the log. Thank you!

**Comment by cdnninja** [comment]
Great to hear!  This change has been merged and will be in this weekends release.
