### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by eximo84** [fuatakgun/kia_uvo#289]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**

UK
Hyundai Ioniq Electric

**Describe the bug**

No idea - see below.  Just appeared after update of HA and this integration.

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.m

kia_uvo - Exception in update : string indices must be integers - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update self.vehicle_data = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 431, in get_cached_vehicle_status return response["resMsg"]["vehicleStatusInfo"] TypeError: string indices must be integers

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by fuatakgun** [comment]
Please check existing open issues.
