### ISSUE TITLE
FEAT: grab consumption data

### ISSUE THREAD

**Issue by Symbiot78** [fuatakgun/kia_uvo#290]
Is is at all possible to gather consumption reports / data?

in my ioniq 5 I can get an overview of each trip.. I drove 100km - spent 10kwh etc etc.

I haven't seen it in the 'data' sensor but maybe it's there and I missed it? or it's possible to grab in another way?

not sure if it's part of bluelink at all.

**Comment by fuatakgun** [comment]
I am interested spending time on this, but I dont think if HA is an useful environment to store this data. Do you have any advice about how to represent this data?

**Comment by Symbiot78** [comment]
hi.
I am no HA expert.. not even a novice :)
but in my imagination I would do the following.

have attributes for at least:

date
miles/km driven
kwh spent

every trip would have this.. so for each trip even on the same day.

information would be logged in influxdb or similar

I would then represent it in an apex chart 

of course this requires the user to actually log the data in a db somewhere.. all depending on how much data (time) the API call would provide. 

I am unsure how far back the car keeps the data. depends on the make/model as well.

**Comment by nilrog** [comment]
I am interested in this too (also have an Ioniq 5).

I found in the Bluelink app you can see the daily energy consumption/average/distance/recuperation, and a total, and a daily average. And it shows one graph of what I think is energy consumption only. But it doesn't look like you can access any historical data from the app.
So the data is definitely in the cloud. 

So if we could figure out how to access that data and make it available in HA you can then push it to influxdb, or another db of choice, if you want to keep more data than what the history in HA keeps. And then make fancy graphs or whatever with it :)

**Comment by fuatakgun** [comment]
Correct me if i am wrong, but you can put sensor data to influxdb via history right. Soz you record every changes of interested sensors and store in influxdb. How is it going to work with these historical records as they are not sensors, they are individual entries in history. Interested to learn and deliver this but i am not sure about implementation

**Comment by nilrog** [comment]
Yes, you can tell HA which sensors to log to influxdb and you will have your own long-time history available in influxdb.

I think a good start would be if we can find out if it is possible to get this data as regular sensors. I have so far no knowledge about what is available through the API though, apart from what you expose in the **data-sensor**. I just reflected over what you can see in the Bluelink app. Trying to push historical data into HA is not the right thing to do, I think.

The data I can see in the app is equivalent to this (with made-up sensor names). Some of this I think you can find in the data already present in this integration. All of these could be sensors, including those under driving history since they would just be updating the total, and the user can push them to influxdb to get real history.

```
energy_consumption_day (kWh)
average_consumption_day (km/kWh)
driving_distance_day (kW)
recuperation_day (kWh)

energy_usage_day: (%)
  - driving
  - electronic
  - climate
  - battery_care
```

And these are shown as driving history:
```
energy_consumption_total (kWh)
average_consumption_total (km/kWh)
driving_distance_total (kW)
recuperation_total (kWh)

energy_consumption_daily_average (kWh)
average_consumption_daily_average (km/kWh)
driving_distance_daily_average (kW)
recuperation_daily_average (kWh)
```

And on top of that you have what @Symbiot78 mentioned above, that is presented in the car display when you are done driving.

> have attributes for at least:
> 
> date
> miles/km driven
> kwh spent

**Comment by povlhp** [comment]
I wrote the calls in issue #282.
Here in Denmark we still get bad data from the server, sometimes making things unusable. Often it says <2km/kWh. Looks like inflated kWh spent.  This may have something to do with language settings, but my status is as below. Form drvhistory.

405224 Wh, 702km
702/405.224 = 1.73km/kWh.  -  App shows same bad data.
Car trip screen says 4.7 km/kWh.

Shorter drives are usually OK - but there are very bad measurements in between. Not sure you have it in your app ? Some people say it might be units related.

```
    "drivingInfoDetail": [
      {
        "drivingPeriod": 0,
        "drivingDate": "20220209",
        "totalPwrCsp": 4299,
        "motorPwrCsp": 3242,
        "climatePwrCsp": 517,
        "eDPwrCsp": 540,
        "batteryMgPwrCsp": 0,
        "regenPwr": 2256,
        "calculativeOdo": 23  // 4.299kWh for 23km is OK
      },
      {
        "drivingPeriod": 0,
        "drivingDate": "20220203",
        "totalPwrCsp": 72150,
        "motorPwrCsp": 70290,
        "climatePwrCsp": 1030,
        "eDPwrCsp": 830,
        "batteryMgPwrCsp": 0,
        "regenPwr": 4222,
        "calculativeOdo": 43  // 72.150 kWh for 43km is just completely off
      },
      {
        "drivingPeriod": 0,
        "drivingDate": "20220131",
        "totalPwrCsp": 74887,
        "motorPwrCsp": 72119,
        "climatePwrCsp": 1658,
        "eDPwrCsp": 930,
        "batteryMgPwrCsp": 180,
        "regenPwr": 4214,
        "calculativeOdo": 55  // 74.887 kWh for 55km is just off.
      },
```

tripinfo does not have info on power consumed.
There is nowhere I can see how many kWh has been charged/discharged total like I can with ODB2. If we had those numbers and odometer, we could calculate ourself

```
{
  "retCode": "S",
  "resCode": "0000",
  "resMsg": {
    "tripPeriodType": 1,
    "offset": 1,
    "dayTripList": [
      {
        "tripDay": "20220209",
        "dayTripCnt": 3,
        "tripDrvTime": 53,
        "tripIdleTime": 13,
        "tripDist": 23,
        "tripAvgSpeed": 35.7,
        "tripMaxSpeed": 76,
        "tripList": [
          {
            "tripTime": "070632",
            "tripDrvTime": 42,
            "tripIdleTime": 12,
            "tripDist": 19,
            "tripAvgSpeed": 42,
            "tripMaxSpeed": 76
          },
          {
            "tripTime": "061534",
            "tripDrvTime": 6,
            "tripIdleTime": 1,
            "tripDist": 2,
            "tripAvgSpeed": 32,
            "tripMaxSpeed": 53
          },
          {
            "tripTime": "060838",
            "tripDrvTime": 5,
            "tripIdleTime": 0,
            "tripDist": 2,
            "tripAvgSpeed": 33,
            "tripMaxSpeed": 57
          }
        ]
      }
    ]
  },
  "msgId": "3...ba"
}
```

**Comment by nilrog** [comment]
> tripinfo does not have info on power consumed.

That is true in the app I have also (Bluelink). You can only see Time, Distance, Avg.Speed, Top.Speed there.

Looking at Energy Consumption it can show that data. But it probably is like you say that it comes from the "Driving history" data. They do show totals in the app, so it must come from somewhere in the API.

As for noticing bad data, it seems that in Bluelink I can only see today's data. Not details about any older day. There is only a table at the bottom that shows "something". And there is nothing to tap on that reveals more data.

Here is a screenshot from the energy consumption screen in my app that better shows what I tried to describe above.
[Energy consumption screenshot](https://nilrogsplace.se/__uploads__/ioniq5_energy_consumption.jpg)

**Comment by rsegers** [comment]
I was unaware of this issue, but had the same idea and added some code. It is now in this PR: #308 

It adds two sensors: average consumption and total consumptions. A few attributes are available as well, so you can make some awesome graphs using InfluxDB.

**Comment by Symbiot78** [comment]
@fuatakgun  -  have you had any success doing this? perhaps integrating the PR from @rsegers ?

**Comment by cdnninja** [comment]
This was merged so closing this out.

**Comment by Symbiot78** [comment]
@cdnninja - sorry if I'm a putz but the 2 new sensors.. I don't see them in the integration.
I am on 2.0.36
tried redownloading
no change.

also I do not quite understand why I have unavailable sensors and 2 similar?

![image](https://user-images.githubusercontent.com/3314249/204127198-0378e08f-7584-4666-9fea-05b06dec4344.png)

**Comment by cdnninja** [comment]
The feature isn't in to 2.X beta branch yet.  1.8 does have it.   It is something I need to merge.  Some really great prep work has been done that can take this further   It won't visually look like this but here is what could be possible: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/139

Could you open a new issue for any missing sensors under the beta branch?  Should be a quick fix for the missing sensors.
