### ISSUE TITLE
Get vehicle location failed

### ISSUE THREAD

**Issue by holdestmade** [fuatakgun/kia_uvo#309]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
EU KIA

**Describe the bug**
Error in log about location failed

**Debug logs if an error occurred**
```
This error originated from a custom integration.

Logger: custom_components.kia_uvo.KiaUvoApiEU
Source: custom_components/kia_uvo/KiaUvoApiEU.py:495
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 0:50:23 pm (4 occurrences)
Last logged: 2:20:27 pm

kia_uvo - Get vehicle location failed
```

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.m

**Additional context**
Only happened since latest update to v1.5.1

Downgrading to v1.5.0 and nothing in logs but, on HA startup, this integration takes 118s to startup

**Comment by cdnninja** [comment]
Are you able to enable debug logs and post them?

**Comment by holdestmade** [comment]
Sorry I forgot all about this, I found it was not related to this integration, I was not able to connect to my account with my app after months of it working fine. I had to log out in my car and redo the whole process but it is now working again
