### ISSUE TITLE
Request: add geocoded location to location

### ISSUE THREAD

**Issue by ManCaveMedia** [fuatakgun/kia_uvo#31]
If possible it would be nice if a geocoded location was added tot the location. That way you could add the current address of the car to a dashboard or to a notification.

**Comment by badguy99** [comment]
This might do what you want - https://github.com/michaelmcarthur/GoogleGeocode-HASS

**Comment by fuatakgun** [comment]
thanks @badguy99 , apparently this is a totally different area of expertise, each user needs to create a Google Maps API account and to make it work.  

I will take a look at this 3 year old API: https://github.com/DenisCarriere/geocoder

**Comment by fuatakgun** [comment]
Apparently, i was wrong, it was not a hard requirement but nice to have to include API account, i will continue checking on this

**Comment by badguy99** [comment]
Yeah, I remember looking at it a while back. That's why I was thinking the OP might have been ok using the other components to pull in the coordinates from your component and convert them.

**Comment by fuatakgun** [comment]
please get latest code base, you will get a separate entity as geocoded location, feel free to resolve
Important: your email address will be sent to OpenStreetMap as caller and they might engage with you over your email address in case of excessive usage. For more information: https://nominatim.org/release-docs/develop/api/Reverse/#other
```If you are making large numbers of request please include an appropriate email address to identify your requests. ```

**Comment by fuatakgun** [comment]
feel free to resolve

**Comment by ManCaveMedia** [comment]
Thanks for adding this.
I noticed the number is not present (street/road is the most detail you get). Is this something that can be added?
Would be very helpfull!

**Comment by m4n63** [comment]
> 
> 
> please get latest code base, you will get a separate entity as geocoded location, feel free to resolve
> Important: your email address will be sent to OpenStreetMap as caller and they might engage with you over your email address in case of excessive usage. For more information: https://nominatim.org/release-docs/develop/api/Reverse/#other
> `If you are making large numbers of request please include an appropriate email address to identify your requests. `

This is a nice feature, but I don't think it should be sending out email addresses by default, this should imo be a configurable setting that you can enable if you are ok with sending out your email address to a 3rd party.

**Comment by ManCaveMedia** [comment]
Added a solution in my previous comment....

**Comment by fuatakgun** [comment]
> Added a solution in my previous comment....
> 
> Also:
> For the state of the geocoded location sensor, it would be nice if the address format was the same as the standard geocoded location sensors.
> 
> For me it's: "road house_number, postcode city, country"
> But I believe that's location/settings dependent.

Thanks for deep dive, if you want you can create a PR or i can fix it. Up to you

**Comment by fuatakgun** [comment]
> > 
> > 
> > please get latest code base, you will get a separate entity as geocoded location, feel free to resolve
> > Important: your email address will be sent to OpenStreetMap as caller and they might engage with you over your email address in case of excessive usage. For more information: https://nominatim.org/release-docs/develop/api/Reverse/#other
> > `If you are making large numbers of request please include an appropriate email address to identify your requests. `
> 
> This is a nice feature, but I don't think it should be sending out email addresses by default, this should imo be a configurable setting that you can enable if you are ok with sending out your email address to a 3rd party.
> 
> 

Fair point, let's work on it

**Comment by ManCaveMedia** [comment]
> > Added a solution in my previous comment....
> > Also:
> > For the state of the geocoded location sensor, it would be nice if the address format was the same as the standard geocoded location sensors.
> > For me it's: "road house_number, postcode city, country"
> > But I believe that's location/settings dependent.
> 
> Thanks for deep dive, if you want you can create a PR or i can fix it. Up to you

I'm not a 'real' developer and on mobile. So please go ahead.
Love the work and am just trying to do something back...

**Comment by ManCaveMedia** [comment]
Maybe this could help with getting the correct address format:
https://opencagedata.com/demo

I have no idea how this is done in HA with the default device_trackers.

**Comment by fuatakgun** [comment]
> > > please get latest code base, you will get a separate entity as geocoded location, feel free to resolve
> > > Important: your email address will be sent to OpenStreetMap as caller and they might engage with you over your email address in case of excessive usage. For more information: https://nominatim.org/release-docs/develop/api/Reverse/#other
> > > `If you are making large numbers of request please include an appropriate email address to identify your requests. `
> > 
> > 
> > This is a nice feature, but I don't think it should be sending out email addresses by default, this should imo be a configurable setting that you can enable if you are ok with sending out your email address to a 3rd party.
> 
> Fair point, let's work on it

please get latest codebase to configure this, by default, it is false.

**Comment by fuatakgun** [comment]
closing this, please reopen if needed

**Comment by badguy99** [comment]
I had assumed, if I didn't tick the include email address for geo-location, it wouldn't get the geolocation data at all, but it still does. Is there a way to completely disable passing location data to the third party?

**Comment by fuatakgun** [comment]
That is also a fair point, let me take a look to disable sensor

**Comment by danieldotnl** [comment]
First of all: great awesome work fuatakgun! I tried to create something like this as well but gave up due to the horrible api.

I do agree with badguy99, sending data to third parties without explicitly mentioning this to your user should really be a no no in combination with home assistant.
Looking at this from a distance, I don't really understand why this functionality needs to be in the kia_uvo plugin. I think this plugin (but of course it's yours, so you can do whatever you want :) ) should focus on unlocking the data from our Kia's which is otherwise inaccessible to use in home assistant.
Interpreting this information, like reverse geocoding the coordinates, distracts from the core. There are other plugins which can do this for the users that desire this, and they probably do it much better because it's their core focus.
E.g. look at: https://github.com/custom-components/places

Just my 2 cents, keep up the great work!

**Comment by fuatakgun** [comment]
> First of all: great awesome work fuatakgun! I tried to create something like this as well but gave up due to the horrible api.
> 
> I do agree with badguy99, sending data to third parties without explicitly mentioning this to your user should really be a no no in combination with home assistant.
> Looking at this from a distance, I don't really understand why this functionality needs to be in the kia_uvo plugin. I think this plugin (but of course it's yours, so you can do whatever you want :) ) should focus on unlocking the data from our Kia's which is otherwise inaccessible to use in home assistant.
> Interpreting this information, like reverse geocoding the coordinates, distracts from the core. There are other plugins which can do this for the users that desire this, and they probably do it much better because it's their core focus.
> E.g. look at: https://github.com/custom-components/places
> 
> Just my 2 cents, keep up the great work!
> 

Thanks for feedback, i am fine to discuss if we should include geocode resolution inside this API but I do not agree on having no explicit mention. I have updated readme file to be sure that users are getting up to date information when they decide to update. So, it was each individual's decision to update latest codebase to receive it.

I am more inclined to have this functionality work as an opt-in way rather than default, which should be fine to eliminate concerns. 

Please let me know what you think with this.

**Comment by m4n63** [comment]
My vote for this would be to either of
1. Leave the geocode out completely
2. Have it as a checkbox option that when checked, queries the geocode using the email of the user (and when not checked, does not query the geocode at all)

**Comment by danieldotnl** [comment]
You are right, my statement was a bit too blunt. It's in the readme and of course it is not like you are deliberately misleading users. However, when I update from HACS, I'm quickly scanning the changelog but not usually not re-reading the readme, so I missed it.

Anyway, I think geocoding can be achieved by other means and it's not core to this plugin. Feel free to disagree, then opt-in is the next best option.
Thanks!

**Comment by fuatakgun** [comment]
please get latest update to enable/disable the geocode location entity, by default it will be disabled.

I agree it is not serving as the main part of the plugin, on the other hand, we can all be happy with final solution :)
