### ISSUE TITLE
Support for US Accounts

### ISSUE THREAD

**Issue by BlackandBlue1908** [fuatakgun/kia_uvo#32]
In the US and would love to use this integration on my Kia Sorrento. I won't be much use in help developing but would be happy to test and provide any helpful logs etc. Let me know.

**Comment by fuatakgun** [comment]
Give me couple of days, I will add basic support to communicate with US servers but I need your help on this to finalize, as I will not be able to test it myself.

**Comment by BlackandBlue1908** [comment]
> Give me couple of days, I will add basic support to communicate with US servers but I need your help on this to finalize, as I will not be able to test it myself.

Awesome, happy to help in any way I can!

**Comment by fuatakgun** [comment]
I had a look at Bluelinky codebase to understand how US servers are operating and they are totally different between each other, so developing blindly is out of discussion :-)

My proposal;
- i will guide you through hacking local UVO app to dump network traffic between your app and UVO servers.
- you can share these traffic with me so i can update codebase accordingly.
- you should update your password later on as it will be captured in network traffic.

Let me know what you think

**Comment by BlackandBlue1908** [comment]
> I had a look at Bluelinky codebase to understand how US servers are operating and they are totally different between each other, so developing blindly is out of discussion :-)
> 
> My proposal;
> - i will guide you through hacking local UVO app to dump network traffic between your app and UVO servers.
> - you can share these traffic with me so i can update codebase accordingly.
> - you should update your password later on as it will be captured in network traffic.
> 
> Let me know what you think

Happy to give it a shot!

**Comment by danielntamasi** [comment]
Same here, happy to get involved.

**Comment by fuatakgun** [comment]
starting on this here: https://github.com/fuatakgun/kia_uvo/wiki/How-to-reverse-engineer-app-traffic-on-Android-phone

**Comment by danielntamasi** [comment]
fyi: unfortunately i only have an iphone, i can't work on Android.

**Comment by BlackandBlue1908** [comment]
I think I have an old android Somewhere, I'll try and get this info this week.

**Comment by fuatakgun** [comment]
apparently, whole flow is unknown for US by bluelinky repository, so I am not able to receive any help from existing ones. When you give it a try, please share your findings here.

**Comment by cdnninja** [comment]
@BlackandBlue1908  does the USA version have a web version?  If so may be able to help get this going.
