### ISSUE TITLE
Only control option is Door Lock

### ISSUE THREAD

**Issue by WilcoSnel** [fuatakgun/kia_uvo#328]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Europe, Hyundai Kona 2021

**Describe the bug**
Cannot control the entire car the way others can control their cars. Not the same options as BlueLink itself has like controlle air conditioning, defroster, etc. Only control option is Door Lock. 

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.m

[KONAHISTORY.csv](https://github.com/fuatakgun/kia_uvo/files/8647652/KONAHISTORY.csv)

**To Reproduce**

**Expected behavior**
There should be more controls available if I understand other users.

**Screenshots**

**Additional context**

On the home assistant forum fuatakgun said "I would say create a GitHub issue and dump your data sensor attributes into it. we had noticed slight differences between API responses for different cars and models.". I hope I added this correctly in the CSV. If not, please let me know.

**Comment by cdnninja** [comment]
The other options are via the developer services menu or automations.  Have you tried these menus?

**Comment by cfliesser** [comment]
Hello, I am having the same issue. What do you mean by the developer services menu or automations? Where are these menus located exactly?
