### ISSUE TITLE
Support configurable distance unit (km vs miles)

### ISSUE THREAD

**Issue by fuatakgun** [fuatakgun/kia_uvo#33]
Source: https://community.home-assistant.io/t/kia-uvo-integration-pre-alpha/297927/19

**Comment by fuatakgun** [comment]
@holdestmade , please get the latest codebase and visit 'Configure' page under Integrations to set desired distance unit.
I had to default to KMs until it is configured.

**Comment by imellor** [comment]
This appears to be brokern in v 2.3.1.
![image](https://user-images.githubusercontent.com/53119550/209585998-6d267c7c-9411-4a69-afb1-3c8c95976143.png)

**Comment by cdnninja** [comment]
This is now on the sensors themselves using the built in home assistant feature. https://github.com/Hyundai-Kia-Connect/kia_uvo/discussions/502
