### ISSUE TITLE
Info on how to install/use for those of us that are not blessed with 'nerd' abilities

### ISSUE THREAD

**Issue by Jens5395** [fuatakgun/kia_uvo#330]
It would be really nice if there was some kind of write-up available to help those of us that do not know the secret handshake on how to get this integration going. I installed via HACS and see the integration on my Home Assistant dashboard but I have no idea how to make it display or do anything.

**Comment by cdnninja** [comment]
Have you already added the integration where you enter your username and password?

**Comment by Jens5395** [comment]
All I did was install the integration via HACS and then added the Kia 
Uvo / Hyundai Bluelink update display to the dashboard. No username or 
password prompt was encountered.

**Comment by cdnninja** [comment]
Go to the integrations page and add in the bottom right like built in integrations.  It will prompt for login.

**Comment by Jens5395** [comment]
Success (mostly) .... got the integration going (sort of). Car battery 
state is shown at 84% but EV battery shows as zero,  Range by EV is 
shown at 0 km.

I added the location of the car to the dashboard but all I get is 'home' 
as location. If I dig deeper I get Lat and Lon .... how do I display 
location on a map though? I used to do this via node-red but that setup 
broke on me about a week ago with no idea what is happening or how to 
fix it - point being that I displayed the car location on a map which is 
much more useful than lat and lon.

Thanks for your help!!!

**Comment by Jens5395** [comment]
An update - the EV battery charge and range eventually updated to the 
correct amount. I suspect the car needed to be turned on for those to 
report.

I am still wondering how I can display the location of the car on a map. 
I would also like to know if there is a way to update the data 
(specifically location) on a manual basis. Currently the car is shown as 
being at home but it is not in fact at home. Can I manually initiate an 
update to report the current location?

**Comment by cdnninja** [comment]
It uses a standard device tracker device type so any maps in home assistant should work.  I can’t say I have personally used this. 

As for commands, yes if you go into the developer menu and services tab you will find a few services offered by this integration. One being force update.

**Comment by Jens5395** [comment]
I have found that if I go to the 'map' tab, I get the location of the 
car. The map location is updated on occasion although I have not been 
able to figure out what causes the position update. The integration is 
set to scan every 5 minutes (it doesn't seem to) and a scan is forced 
every 200 minutes (I tried every 15 minutes but that didn't seem to make 
a difference). The only way I can update the car position on command is 
by restarting HA.

If I go to the 'Developer tools' tab and select the location entity in 
the 'current entities', I get a 'set state' button on the bottom of the 
entities. I also get a button to the right of the 'set state' button 
which seems (based on the icon) to be a 'force update' button. Neither 
of the two buttons actually update the location of the car on the map. 
If I restart HA, the map location updates.

Any help on how to force a location update (not involving restarting HA) 
would be greatly appreciated!

**Comment by Jens5395** [comment]
WooHooo - found what you were trying to tell me !!!!  Something else is 
currently broken and I get a location unavailable message but I think I 
am getting closer!


Thanks!


Jens

**Comment by cdnninja** [comment]
Check logs for errors.  You may have maxed out the api calls to Kia Hyundai. At which point 24 hours will have to pass.  You can tell by trying to use the app as well. 

Location won't be real time on this as your shouldnt poll too often.
