### ISSUE TITLE
Support for India

### ISSUE THREAD

**Issue by snishok** [fuatakgun/kia_uvo#337]
**Is your feature request related to a problem? Please describe.**
I live in India.

**Describe the solution you'd like**
It would be great to add support for India.

Please let me know if anything is required from my end.

**Comment by cdnninja** [comment]
Are you able to reference the Australia issue and provide me the same details in this thread? 

I will need someone to sniff the traffic.   If you have any experience with python happy to also receive help.

**Comment by cdnninja** [comment]
Does this still interest you?

**Comment by snishok** [comment]
Hi, 
There is no web app for India so I am trying to get data from the mobile app. 
trying to get data without rooting the mobile.

**Comment by PrathikGopal** [comment]
+1 - need coverage for INDIA 

I’ll see if I can capture endpoint url traffic from the app.

**Comment by cdnninja** [comment]
I am closing.  Please come back and report details of the API if interested.

**Comment by cdnninja** [comment]
Thanks to @nishant713  this has been added to the master branch.  Next release will include it.
