### ISSUE TITLE
Integration selecting non-default/second vehicle

### ISSUE THREAD

**Issue by JonAgra** [fuatakgun/kia_uvo#338]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
USA - Hyundai

**Describe the bug**
After configuring the integration and logging in, the wrong vehicle from the account is selected to add to HA. I have my primary vehicle set up as the default on owners.hyundaiusa.com, and I have a secondary vehicle that is _shared_ with me from someone else's account (I was added as a secondary driver from the other person's account.)
After logging in to the integration, the secondary vehicle is selected and added to HA, and my primary vehicle is not added to HA at all.

**Debug logs if an error occurred**
N/A

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.m

**To Reproduce**
1. Install the integration from HACS
2. Go to Devices and Services in HA Settings
3. Add integration
4. Search for "Hyundai" and select the Kia Uvo / Hyundai Bluelink integration
5. Enter username, password, select "USA" and "Hyundai" and submit.
6. Integration is added and user is prompted to set an area for the newly added device that was discovered, which in my case, is the secondary vehicle on my account. This is the only vehicle I'm presented with, and I am not presented with the default vehicle.

**Expected behavior**
Follow steps to reproduce as seen above, except be presented with the default/primary vehicle on the MyHyundai account, OR be presented with BOTH vehicles on my account.

**Screenshots**
![MyHyundai](https://user-images.githubusercontent.com/6026858/181920235-087c35eb-e60f-48e7-a61f-d8ebd0f87d92.PNG)
![HA](https://user-images.githubusercontent.com/6026858/181920244-fb114f24-7b42-4a2d-bda3-bd434daad637.PNG)

**Additional context**
I understand the integration only fetches values for the first car. The issue is that the correct car, from the screenshots above, is the 2022 Elantra. This was the first car on my account and is set as the default/primary vehicle in my account. The 2016 Sonata Hybrid is a secondary vehicle that is _shared_ from another user's account (i.e. they added me as a secondary driver from within their MyHyundai account.)

**Comment by cdnninja** [comment]
The code looks at the first car returned in the list.   We don't control the order that we are given.  

A new version of this integration exists just isn't complete.  It supports multiple cars. It's listed as externalAPI as a branch and has issues open for version 2.0.  You could give that version a go.  It isn't fully featured though.

**Comment by cdnninja** [comment]
Closing as this part of the two car issue.  v2. Supports this.
