### ISSUE TITLE
Request: Add vehicle name as attribute

### ISSUE THREAD

**Issue by ManCaveMedia** [fuatakgun/kia_uvo#34]
The vehicle name that's set in UVO is part of the friendly name of all entities. However, it's not add as an attribute, so it's not possible to dynamically add it to your lovelace setup (ie. Markdown).
It would be nice if it was an attribute of the data entity too.

**Comment by fuatakgun** [comment]
Let me check it, looks easy

**Comment by fuatakgun** [comment]
please get latest code, you will receive a new attribute called `vehicle_name` under `data` entity.

example usage `{{ states.binary_sensor.niro_data.attributes.vehicle_name }}`

**Comment by fuatakgun** [comment]
resolving this, open if needed
