### ISSUE TITLE
Stop charging service problem

### ISSUE THREAD

**Issue by marcvandam2** [fuatakgun/kia_uvo#342]
Car used:
Kia E-niro from 2021

**Describe the bug**
If I call service to stop charging ( kia_uvo.stop_charge ), that works. The car directly reacts by stopping the charging. But after a few seconds charging is continued again.  :( 

Now if I use the Kia Connect app and press "Stop charging" there it stops charging (and stays that way) 

I'm a developer, so I can assist.

**Comment by mmooren94** [comment]
Hi, same problem here. Same car, europe model.

Found out that if i set the charing times (offpeak) with the UVO app. Than the home assistant stop service will work correctly.

Thanks in advance.

**Comment by cdnninja** [comment]
Best way to debug this would be to capture the API commands from the app and compare to what our logs state we are sending.   Could also try bluelinky to see if it has the same issue. If not can compare payloads.

**Comment by cdnninja** [comment]
Which region?  We will most likely need to sniff the traffic to compare your native app to the payload we send.   

Debug logging of our integration posts the payload to logs.  Sniffing depends on region.

**Comment by cdnninja** [comment]
Could you compare your payload to blue linky or the app?  I am not in EU so will need someone else to provide the correct info to see where we go wrong.
