### ISSUE TITLE
Location Entity failing to Geocode / Unknown

### ISSUE THREAD

**Issue by SQLSamulski** [fuatakgun/kia_uvo#348]
`vehicleLocation:
geocodedLocation:
error:
code: 400
message: Floating-point number expected for parameter 'lat'
odometer:
unit: 3
value: '1385'`

When reviewing the vehicle data for the location attribute, lat and long are both floats that reflect the location of the vehicle.

2022 Hyundai Ioniq 5 AWD Limited

**Comment by cdnninja** [comment]
What country is this in?  Any other log data available? Does normal location work?

**Comment by SQLSamulski** [comment]
USA. I Uninstalled and reinstalled the integration and it is working now.
