### ISSUE TITLE
Failed to set up after last OS 9.0 upgrade

### ISSUE THREAD

**Issue by Ruzo** [fuatakgun/kia_uvo#356]
Integration failed right after upgrading HA OS to 9.0

**Debug logs if an error occurred**
```
This error originated from a custom integration.

Logger: custom_components.kia_uvo.Vehicle
Source: custom_components/kia_uvo/Vehicle.py:81
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 5:23:09 PM (1 occurrences)
Last logged: 5:23:09 PM

kia_uvo - Exception in update : 'vehicleStatus' - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update self.vehicle_data = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/HyundaiBlueLinkAPIUSA.py", line 173, in get_cached_vehicle_status vehicle_status["vehicleStatus"] = response["vehicleStatus"] KeyError: 'vehicleStatus'


This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/kia_uvo/__init__.py:207
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 5:23:09 PM (1 occurrences)
Last logged: 5:23:09 PM

Error setting up entry xxxxxxxxxxx@gmail.com for kia_uvo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/kia_uvo/__init__.py", line 218, in async_setup_entry
    await update(dt_util.utcnow())
  File "/config/custom_components/kia_uvo/__init__.py", line 207, in update
    datetime.now(local_timezone) - vehicle.last_updated
TypeError: can't subtract offset-naive and offset-aware datetimes
```

**To Reproduce**
Upgrade HA OS to 9.0

**Comment by cdnninja** [comment]
To confirm your Hyundai app works? This looks like the api didn’t respond correctly at the time of boot. On Sep 15, 2022, at 3:39 PM, Richard Rouzeau ***@***.***> wrote:﻿
Integration failed right after upgrading HA OS to 9.0
Debug logs if an error occurred
This error originated from a custom integration.

Logger: custom_components.kia_uvo.Vehicle
Source: custom_components/kia_uvo/Vehicle.py:81
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 5:23:09 PM (1 occurrences)
Last logged: 5:23:09 PM

kia_uvo - Exception in update : 'vehicleStatus' - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update self.vehicle_data = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/HyundaiBlueLinkAPIUSA.py", line 173, in get_cached_vehicle_status vehicle_status["vehicleStatus"] = response["vehicleStatus"] KeyError: 'vehicleStatus'


This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/kia_uvo/__init__.py:207
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 5:23:09 PM (1 occurrences)
Last logged: 5:23:09 PM

Error setting up entry ***@***.*** for kia_uvo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/kia_uvo/__init__.py", line 218, in async_setup_entry
    await update(dt_util.utcnow())
  File "/config/custom_components/kia_uvo/__init__.py", line 207, in update
    datetime.now(local_timezone) - vehicle.last_updated
TypeError: can't subtract offset-naive and offset-aware datetimes

To Reproduce
Upgrade HA OS to 9.0

**Comment by Ruzo** [comment]
> To confirm your Hyundai app works? This looks like the api didn’t respond correctly at the time of boot.

Hi, yes. I did opened the official app and can confirm that it works.

**Comment by cdnninja** [comment]
Could you enable debug logs and post them if this is still occuring?

**Comment by Ruzo** [comment]
I've just updated Supervisor and Core and now it works ¯\_(ツ)_/¯.

Thanks a lot for looking into it.

**Comment by cdnninja** [comment]
Same error still after a reload? If so enable debug logs and provide those.  On Sep 17, 2022, at 3:45 PM, Richard Rouzeau ***@***.***> wrote:﻿

To confirm your Hyundai app works? This looks like the api didn’t respond correctly at the time of boot.

Hi, yes. I did opened the official app and can confirm that it works.
