### ISSUE TITLE
Outdoor temperature?

### ISSUE THREAD

**Issue by rindlerblabla** [fuatakgun/kia_uvo#361]
Would it be possible somehow to get the outdoor temperature as a sensor in HA?

Am using HA to set a heating schedule and what settings the automation is using (heating, defrost and so on) depend on the outdoor temperature where the car is parked.

Am situated in EU and haven't managed to find a website for Kia connect/uvo where it is possible to login, they just refer to the mobile app so haven't been able to see what data is available.

**Comment by cdnninja** [comment]
Please check in the native app. If not in your app it isn't something we can support.

**Comment by cdnninja** [comment]
I would encourage you to use home assistant for this though as you can pull weather and I assume could use the last location of the car for this.

**Comment by rindlerblabla** [comment]
![Screenshot_20220924-160502_Kia Connect.jpg](https://user-images.githubusercontent.com/28257974/192102327-1098ebd4-ae40-48b2-b2ed-5a3d69f6bda9.jpg)

It is shown in the native app. If using this temperature I don't have to set up different sensors depending on in which city the car is parked.

**Comment by cdnninja** [comment]
Let us know if the data shows up in the app for your car.  If not we can’t get the data.  On Sep 22, 2022, at 3:17 AM, rindlerblabla ***@***.***> wrote:﻿
Would it be possible somehow to get the outdoor temperature as a sensor in HA?
Am using HA to set a heating schedule and what settings the automation is using (heating, defrost and so on) depend on the outdoor temperature where the car is parked.
Am situated in EU and haven't managed to find a website for Kia connect/uvo where it is possible to login, they just refer to the mobile app so haven't been able to see what data is available.

**Comment by rindlerblabla** [comment]
See the post above. That is a screenshot from the EU Kia connect app, where the temperature is available. Or could I provide the information in some better way?

**Comment by SondreNjaastad** [comment]
Hi!
Context;
I'm one of the developers of Bluelinky, that this integration is built upon. 

As far as i can remember from working with bluelinky, any outside temperature sensors is not exposed to the car API, and the temperature you is in the app is just weather data from a weather API. Its not measured temperature

**Comment by rindlerblabla** [comment]
@SondreNjaastad Thanks for your reply! Am also guessing that the temperature is from some weather resource, however it is accurate information whether the automation should heat the car or not. But if it it's not possible to catch that data I have to set up different temperature sensors in HA and somehow switch which sensor I rely on depending on the car location.

**Comment by rindlerblabla** [comment]
Am now using the car's device tracker attribute long/lat together with a rest sensor catching the actual temperature from the national weather service, similar to what is described here https://community.home-assistant.io/t/get-current-temperature-for-my-cars-location/396051 so am closing this issue.
