### ISSUE TITLE
The integration reverts to old cached data after a while 

### ISSUE THREAD

**Issue by julianbenjamin** [fuatakgun/kia_uvo#364]
**Region and Brand of car**
US, Hyundai Tucson Hybrid 2022

**Describe the bug**
While the car is charging the information was correct. But then it reverted to a prior cached data. 

**Debug logs if an error occurred**

This error originated from a custom integration.

Logger: custom_components.kia_uvo.Vehicle
Source: custom_components/kia_uvo/Vehicle.py:81
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 9:13:55 PM (2 occurrences)
Last logged: 9:58:55 PM

kia_uvo - Exception in update : 'vehicleStatus' - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update self.vehicle_data = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/HyundaiBlueLinkAPIUSA.py", line 172, in get_cached_vehicle_status vehicle_status["vehicleStatus"] = response["vehicleStatus"] KeyError: 'vehicleStatus'

**Expected behavior**
It should show the latest status

**Comment by cdnninja** [comment]
Does your native app show the same thing when this occurs?  The above error is stating that Kia/Hyundai isn't responding correctly.

**Comment by julianbenjamin** [comment]
You're right; the app is showing the same thing.  Reverts to old data until the next morning.

I wonder if I'm being too aggressive with the frequency of checks.  I'll close this for now.  Thanks.
