### ISSUE TITLE
v1.8.0 update leads to repeated log message "Unable to parse drivingInfo"

### ISSUE THREAD

**Issue by TazUk** [fuatakgun/kia_uvo#365]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
EU en-GB UK
Kia Stonic 2021
Non-EV 

**Describe the bug**
After updating to v1.8.0 from v1.7.2 repeated log messages in HA:

```
This error originated from a custom integration.

Logger: custom_components.kia_uvo.KiaUvoApiEU
Source: custom_components/kia_uvo/KiaUvoApiEU.py:459
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 11:17:14 (4 occurrences)
Last logged: 12:47:05

Unable to parse drivingInfo

```
Downgrading to v1.7.2 resolves with no loss of functionality

**Debug logs if an error occurred**

Not in a position to obtain logs currently, however this appears to be related to addition of code block
```
        try:
            response["resMsg"]["vehicleStatusInfo"][
                "drvhistory"
            ] = self.get_driving_info(token)
        except:
            _LOGGER.warning("Unable to get drivingInfo")
```
to KiaUvoApiEU.py
Related to PR #308?

**To Reproduce**
1. Have non-EV
2. Upgrade to v1.8.0
3. Restart HA
 
**Expected behavior**
No additional warning messages for non-EV cars

**Screenshots**
N/A

**Additional context**
No apparent loss of functionality however significant amount of warning messages in logs that cannot be resolved by the user (4 messages in 90 minutes).

**Comment by cdnninja** [comment]
I have created a PR that should close this.   This is just a warning that it can't get EV details.

**Comment by TazUk** [comment]
I suspected as much but thank you
