### ISSUE TITLE
Unchecked charge limit sets limit to 90%

### ISSUE THREAD

**Issue by richy58729** [fuatakgun/kia_uvo#370]
**Region and Brand of car**
Region is EU, brand is Kia, model is e-Niro MY22

**Describe the bug**
When using the set_charge_limits service (BTW, thanks for this service, opens up new possibilities!), an unchecked limit (doesn't matter if it's DC or AC) sets the limit in the UI to 90%, but after calling the service, the unchecked charge limit is also set to 90% in reality. If you uncheck both limits (which is of course nonsense if you don't check anything, but I did it just for the sake of testing), both limits will be set to 90% in reality (checked in the Kia Connect app BTW, not in the car itself).

**To Reproduce**
1. Go to 'Developer Tools &rarr; Services'
1. Look up the service 'kia_uvo: set_charge_limits'
1. Make sure DC or AC is unchecked (or both are)
1. Click on 'Call Service'
1. Look at 'Set charging limits' in the Kia Connect app and the unchecked limit is set to 90%, or use the 'kia_uvo: update' service and see the targetSOClevel for plugType 0 or 1 (or both) is set to 90.

**Expected behavior**
An unchecked limit should not change the limit in reality.

**Comment by cdnninja** [comment]
I don't have an EV so makes it hard to confirm.  Could you check if the mobile app lets you set a single one of these?  If it shows both regardless does it just default the value to what it currently is set to?

**Comment by richy58729** [comment]
As soon as I tap _Set charging limits_ in the Kia Connect app,
![Screenshot_2022-10-07-06-44-41-14_8c1be1e5aae6d26dc95284741c49c73b](https://user-images.githubusercontent.com/1909971/194773453-186cbc61-aaf3-44e9-870d-0e5e4c6e3ccd.jpg)

the app queries the current charging limits. and then I see the current limits, which I can change and tap _Send to car_.
![Screenshot_2022-10-07-06-44-58-03_8c1be1e5aae6d26dc95284741c49c73b](https://user-images.githubusercontent.com/1909971/194773469-82462418-cb2f-4f0d-8429-759bf2812f0c.jpg)

So no, you can't set a single limit, but both. And yes, it defaults to the current charging limits.

**Comment by cdnninja** [comment]
In the home assistant gui we can't set dynamic defaults.   So how I am thinking we handle this is when the box is unchecked query for the current value and pass that.   If both are unchecked just cancel the request.   

Thoughts?

**Comment by richy58729** [comment]
# UI
I think it would be best, if it's possible, to first query the current values, then show sliders for both without checkboxes and pass both values (so the same behavior as the Kia Connect app). You have to query the current values anyway.

If it's not possible to show sliders in HA without checkboxes, then yes, if a value is unchecked, pass the queried current value and don't do anything if both are unchecked.

# YAML
If the service is called from YAML, check if both values are in the service call and pass them. If no value at all is in the service call, don't do anything at all. If one of the values is not in the service call, query the current values and pass the missing value.

**Comment by cdnninja** [comment]
Due to home assistant limitations the UI in the call service screen can't have anything dynamic in it.  So I can make tweaks like remove the check boxes but I can't query the value and place the correct value into the GUI.

**Comment by richy58729** [comment]
Okay, I get it. Then yes, what you're suggesting sounds like the best thing to do (and thus no tweaks like removing the checkboxes).

**Comment by cdnninja** [comment]
Could you test out my PR?

**Comment by richy58729** [comment]
A little help here, please, as I have never done this before...

So I downloaded and installed GitHub Desktop, then cloned this repo, and checked out your PR to my cloned repo. Then, I backed up folder _custom_components/kia_uvo_ from HA and copied over the folder _custom_components/kia_uvo_ from the cloned repo to HA, overwriting all files. I then restarted HA.

Are these steps the way to do this?

First, I had just made a copy of _custom_components/kia_uvo/Vehicle.py_ to make a backup of it and copied/pasted the changes in your PR, but then realized that maybe the changes in your PR were dependent on changes in the master branch, because when I tried changing a charge limit, nothing happened. However, after doing the above steps (so replacing the whole custom component from the master branch), the result was the same.

So, to reiterate: it looks like no charge limit at all is changed if I only set one of the two charge limits and leave the other unchecked. When I set both charge limits, it works just fine.
I do have some experience with coding, just not with Python, but isn't line 243 in Vehicle.py the reason of this behavior?

`if ac_limit is not None and dc_limit is not None`

This code looks to me like both charge limits have to be checked, so if only one is checked, the code from lines 244 until 255 isn't executed at all and thus the targetSOClevel of either charge limit is never retrieved at all. But, it could also be that I just don't understand Python and I'm being ignorant...

If I **am** on the right track however, I think that deleting line 243 would be the solution.

**Comment by cdnninja** [comment]
Exact right approach.   You can also enable debug logging if needed.  

In this case I think you may be right on that line. The intent on that is to not make an api call if nothing is set.  I think it should be an or not an and?

**Comment by richy58729** [comment]
#378 First time creating a PR, so I hope I'm doing it correctly...

**Comment by cdnninja** [comment]
Is that one working for you locally? If so I can go ahead and merge it.

**Comment by richy58729** [comment]
Well, not quite...

I enabled debugging and noticed the following errors:
```
[custom_components.kia_uvo.sensor] skipping sensor for missing data, key:vehicleStatus.evStatus.targetSOC.1.targetSOClevel
[custom_components.kia_uvo.sensor] skipping sensor for missing data, key:vehicleStatus.evStatus.targetSOC.0.targetSOClevel
[custom_components.kia_uvo.sensor] skipping sensor for missing data, key:vehicleStatus.evStatus.targetSOC.1.dte.rangeByFuel.totalAvailableRange.value
[custom_components.kia_uvo.sensor] skipping sensor for missing data, key:vehicleStatus.evStatus.targetSOC.0.dte.rangeByFuel.totalAvailableRange.value
[custom_components.kia_uvo.sensor] skipping sensor for missing data, key:lastService.value
[custom_components.kia_uvo.sensor] skipping sensor for missing data, key:nextService.value
[custom_components.kia_uvo.sensor] skipping sensor for missing data, key:vehicleLocation.geocodedLocation.display_name
```

The _targetSOClevel_ variables were of course important to make the _set_charge_limits_ service in HA actually work (which it still didn't after your patch), but I noticed they have the same hierarchical path as the _totalAvailableRange_ variables (both starting with _vehicleStatus.evStatus.targetSOC_) and in the _binary\_sensor.e\_niro\_data_ entity in the Developer Tools in HA I could deduce the right path, which isn't _vehicleStatus.evStatus.targetSOC_, but _vehicleStatus.evStatus.reservChargeInfos.targetSOClist_.
I first changed some code in _Vehicle.py_, but saw some other errors and noticed I also had to change some code in _sensor.py_.

After that, the _targetSOClevel_ variables were filled with the correct charge limit I could also see in the Kia Connect app. But... and that's where my description in the pull request comes from, in the code in _Vehicle.py_ I introduced some extra debug logging (because setting the charge limits **still** didn't work) and saw that the _ac_limit_ and _dc_limit_ variables in def _set_charge_limits_ still aren't filled with the correct value, but with _None_, and that baffles me, because the path _self.vehicle_data.get_ uses, is now the correct path... But that must have to do with my inexperience with Python, which is why I'm turning to you. So, do you have a clue why _ac_limit_ and _dc_limit_ are still _None_?

Mind you, I haven't paid any attention to the errors about _lastService.value_, _nextService.value_ and _vehicleLocation.geocodedLocation.display_name_ because they aren't important for setting the charge limits, but I can already tell you that in the _binary\_sensor.e\_niro\_data_ entity, I don't see anything with the word 'service' in it (so I guess that's not a thing in my model e-Niro), but after setting a checkmark next to _Enable Geolocation Entity using OpenStreetMap_ in the configuration of the integration, I **do** see the _vehicleLocation.geocodedLocation_ attribute.

**Comment by cdnninja** [comment]
You are rocking it! Thanks for doing this.   Really appreciate it.  

A few things.  I think the reason ac_limit and dc were returning none is you were using .get vs get_child_value.  I switched it in hopes that solves it. 

As for skipping sensors. That isn't always a bad thing.  That is how we gracefully skip items not in the data. All cars, regions and years offer different sensors. 

Could you retest #377?

**Comment by richy58729** [comment]
I was utterly confused with how to get your changes to my working directory with GitHub Desktop... Whatever I did, I didn't succeed. I finally just deleted my complete fork and working directory and recloned the repo again. Pffff.......

Concerning skipping sensors, calling the lines in the logging about skipping sensors 'errors' was a badly chosen word. They are just that, mentioning that some sensors are skipped. At least the first four were interpreted as errors by me, because the path to _targetSOC_ wasn't working. I just hope that it isn't the case that some models e-Niro use _vehicleStatus.evStatus.targetSOC_ as the path and some other models _vehicleStatus.evStatus.reservChargeInfos.targetSOClist_, because then my changes would fix those sensors for me, but break those sensors for others and that would be unfortunate.

But back to the code.

Well, I had only changed the path to _targetSOClevel_, the call to _self.vehicle\_data.get_ was code that was already written which I didn't change... Anyway, you changing it to _self.vehicle\_data.get\_child\_value_ broke the _set\_charge\_limits_ def completely:

```
2022-10-24 03:57:01.274 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'dict' object has no attribute 'get_child_value'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/config/custom_components/kia_uvo/__init__.py", line 111, in async_handle_set_charge_limits
await vehicle.set_charge_limits(ac_limit, dc_limit)
File "/config/custom_components/kia_uvo/Vehicle.py", line 251, in set_charge_limits
dc_limit = self.vehicle_data.get_child_value(
AttributeError: 'dict' object has no attribute 'get_child_value'
2022-10-24 03:57:01.289 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548251993712] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 648, in handle_execute_script
await script_obj.async_run(msg.get("variables"), context=context)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
self._handle_exception(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
raise exception
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/config/custom_components/kia_uvo/__init__.py", line 111, in async_handle_set_charge_limits
await vehicle.set_charge_limits(ac_limit, dc_limit)
File "/config/custom_components/kia_uvo/Vehicle.py", line 251, in set_charge_limits
dc_limit = self.vehicle_data.get_child_value(
AttributeError: 'dict' object has no attribute 'get_child_value'
```

So I guess that's not the way to go... ;)

**Comment by cdnninja** [comment]
@richy58729  mistake on my part.  I corrected it.  Could you retry?  Could you also confirm the new sensor paths are working for you?

**Comment by richy58729** [comment]
Yes, that's it! Works like a charm.

I have tested it as follows (so you know I've tested it thoroughly enough:
- Setting only the AC value (which was changed, while the DC value stayed the same).
- Setting only the DC value (which was changed, while the AC value stayed the same).
- Setting both the AC and DC value (which were both changed).
- Setting no value at all (nothing happens, so silently ignored, as expected and as designed).

Now I see your fix, it's of course quite logical that in this case, if you're reading a child value, you have to go one step up in the chain...

Nice catch!

**Comment by richy58729** [comment]
And oh yeah, regarding the sensor paths (because you asked a second question), they show the correct values:
- sensor.e_niro_target_capacity_of_charge_ac
- sensor.e_niro_target_capacity_of_charge_dc
- sensor.e_niro_target_range_of_charge_ac
- sensor.e_niro_target_range_of_charge_dc

Although the last two sensors are a bit redundant, as they both show the same value (in my case currently 357 km).
But, what is really strange, they are 1 km above the sensors _sensor.e_niro_range_by_ev_ and _sensor.e_niro_range_total_, which currently show 356 km... Okay, riiiiiiiiiiiiiiiiight...
