### ISSUE TITLE
Integration not starting on 2022.10.0/1

### ISSUE THREAD

**Issue by afxefx** [fuatakgun/kia_uvo#371]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
USA Hyundai Sonata

**Describe the bug**
Integration fails to start after reboot of HA 2022.10.1.  Don't recall this occurring prior to 2022.10 update.  Two errors are logged on HA start and listed below.

**Debug logs if an error occurred**
First error:
`kia_uvo - Exception in update : 'vehicleStatus' - traceback: Traceback (most recent call last): File "/home/homeassistant/.homeassistant/custom_components/kia_uvo/Vehicle.py", line 56, in update self.vehicle_data = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/home/homeassistant/.homeassistant/custom_components/kia_uvo/HyundaiBlueLinkAPIUSA.py", line 172, in get_cached_vehicle_status vehicle_status["vehicleStatus"] = response["vehicleStatus"] KeyError: 'vehicleStatus'`

Second error:
```
Traceback (most recent call last):
  File "/srv/homeassistant/venv_3.9.7/lib/python3.9/site-packages/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/homeassistant/.homeassistant/custom_components/kia_uvo/__init__.py", line 218, in async_setup_entry
    await update(dt_util.utcnow())
  File "/home/homeassistant/.homeassistant/custom_components/kia_uvo/__init__.py", line 207, in update
    datetime.now(local_timezone) - vehicle.last_updated
TypeError: can't subtract offset-naive and offset-aware datetimes
```

**To Reproduce**
1. Reboot HA

**Expected behavior**
Integration to start.

**Screenshots**

**Additional context**
Reloading the integration after some time allows it to load properly.

**Comment by NigelVanHattum** [comment]
I had to reload the integration, it seems to be working again.

**Comment by cdnninja** [comment]
This error means the server didn't respond with a car.   It handles it okay once running but doesn't do well on first start since it doesn't know what entities to create.
