### ISSUE TITLE
Feature requests?

### ISSUE THREAD

**Issue by PierreLevres** [fuatakgun/kia_uvo#38]
thanks for your integration. I switched from Domoticz, where I used my own plugin using a python version of the BlueLinky API-wrapper. In HA I am using a node-red/MQTT interface with the Bluelinky api-wrapper. In the BlueLinky api-wrapper a few more information requests and controls of the car are available (also in node red) such as: 
- also for Hyundai cars Kona/Ioniq
- setting AC temperature
- getting and setting charge limits
- start and stop charging
- getting trip-reports
- send destination to car

Also in the implementation of BLuelinky vs you integration I see a few differences:
Getting a unique stamp header, every time it is run
A pin code (giving a control token, expiring every 10 minutes) in the UVO-app is needed for the actions on the car and a daily refresh of an access token is implemented. I don't see that pin implemented in your code.

In my python lib and node-red implementation I also added the possibility to plan a route by ABRP (including charging stations) and send it to the car.
I see you mentioning BlueLinky in the reactions here. Are you also familiar with the discord forum on Bluelinky, i didn't find your account name?
Do you have a wishlist in which I can contribute?

**Comment by fuatakgun** [comment]
thanks for detailed feedback, it is welcome. let's walk through items one by one;
- enabling this for Hyundai cars: I will write a guide to reverse engineer applications on android phones and volunteers can share their traffic logs with me so I can update the library with other brands/regions. You cannot believe how different US and EU implementations at the backend.
- there is a service created already to start/stop car with climate. as I do not own a EV one (rather PHEV), I am not able to test it myself and looking for volunteers to understand what is missing. Please join over here: https://github.com/fuatakgun/kia_uvo/issues/39
- charge limits: https://github.com/fuatakgun/kia_uvo/issues/40
- charging actions: https://github.com/fuatakgun/kia_uvo/issues/41
- trip reports: https://github.com/fuatakgun/kia_uvo/issues/42
- send destination: https://github.com/fuatakgun/kia_uvo/issues/43

I will follow these individual requests over their specific issue. Do you have any idea how we can model these entities in home assistant? What type of entities would be appropriate?

Regarding to PIN, it was not needed in my case, I do not understand why it is required in app. We just login here and use the token for 1 day, login again and fetch another token. 

Regarding to wish list, we can follow these by individual issues, makes sense to you?

**Comment by PierreLevres** [comment]
groet,

Peter

> On 23 May 2021, at 21:41, fuatakgun ***@***.***> wrote:
> 
> 
> thanks for detailed feedback, it is welcome. let's walk through items one by one;
> 
> enabling this for Hyundai cars: I will write a guide to reverse engineer applications on android phones and volunteers can share their traffic logs with me so I can update the library with other brands/regions. You cannot believe how different US and EU implementations at the backend.
There is no need for a guide to reverse engineer. In the BlueLinky libs, it has already been done, as I have done in my domoticz python plugin. Also for Hundai and Kia in Canada, Also for Hyundai in the USA it has been done. 
For europe: have a look at the the code in https://github.com/Hacksore/bluelinky/blob/develop/src/constants/europe.ts <https://github.com/Hacksore/bluelinky/blob/develop/src/constants/europe.ts> and https://github.com/PierreLevres/BlUVO/blob/master/bluvo_lib.py <https://github.com/PierreLevres/BlUVO/blob/master/bluvo_lib.py>

**Comment by fuatakgun** [comment]
hi Peter, with latest kia update, we had failed because of stamp mismatch, on the other hand, this stamp (latest) is not included in bluelinky. Do you know the reasoning behind having this list? I see that there is always a possibility to break down when Kia updated its stamp.

**Comment by PierreLevres** [comment]
BlueLinky is mimicing the app. So behaving very closely. A random stamp is introduced so people dont use the same stamp.

**Comment by fuatakgun** [comment]
Resolving this issue
