### ISSUE TITLE
v2.0 Adds AC/DC Charging number sensors for ICE

### ISSUE THREAD

**Issue by cdnninja** [fuatakgun/kia_uvo#384]
@jwefers  Any chance you are able to take a look at this since you wrote the code so can test on your car?  I am starting to get back into getting this version to market.    This file doesn't handle the situation where those charging values don't exist.  As such adds to ICE cars: 

https://github.com/fuatakgun/kia_uvo/blob/externalAPI/custom_components/kia_uvo/number.py

Ideally like in the sensors.py file we only add sensors that have data.  This way it works for any region/car.

**Comment by jwefers** [comment]
i mentioned elsewhere i am out of till EOY, but i found lately that my mind goes to "i should get back on this", so yes, i could take a look and contribute a bit more.

@cdnninja one big question i currently have is: do you want all the features that went into externalAPI backported to master or rather bring forward all the features from master into externalAPI, which is supposed to become v2.0?

**Comment by cdnninja** [comment]
@jwefers awesome.   Yes.  Goal is to get feature parity on 2.0.  By doing the releases in beta 2.0 we now have enough testers to do this.  So I'm also encouraging any new features go 2.0 only.
