### ISSUE TITLE
2.0 cannot initialize

### ISSUE THREAD

**Issue by Symbiot78** [fuatakgun/kia_uvo#385]
![CE8B83F7-571E-42C1-B016-357F02892B5A](https://user-images.githubusercontent.com/3314249/198712702-0fc84520-031e-4579-b8c6-40595fad9316.jpeg)

2022-10-28 21:02:05.926 ERROR (MainThread) [custom_components.kia_uvo.coordinator] Unexpected error fetching kia_uvo data: name 'location' is not defined

**Comment by cdnninja** [comment]
Are you able to add the detailed logging?  How to do so is outlined in the bottom of this: 

https://github.com/fuatakgun/kia_uvo/tree/v2.0

**Comment by cdnninja** [comment]
As well which region/brand do you use?

**Comment by smartkrskrab** [comment]
![ScreenShot_20221028214839](https://user-images.githubusercontent.com/50077227/198730413-4b609e4a-e39f-41af-a067-9a231eede27e.png)
UK v2.0.1

**Comment by cdnninja** [comment]
This error is a rather common EU error.   It means the API isn't responding right now.  Typically a restart after some time passes resolves it.   The old integration had this same issue.  We may need to find a way to handle this.

**Comment by Symbiot78** [comment]
> 

Hi .. I am in Europe.
I tried the update version. And ended with same error as @smartkrskrab . This is the first time I've seen that error.

**Comment by Symbiot78** [comment]
@cdnninja - can it in any way be related to the kia/hyundai servers looking for headers coming from mobile devices?

In another integration where there's cloud communication we found that headers with mobile data made a big difference.. 


`def __init__(self):
    self.session = requests.Session()
    headers = {'User-Agent': 'Dalvik/2.1.0 (Linux; U; Android'}
    self.session.headers.update(headers)`

**Comment by holdestmade** [comment]
Different error, v2.0.1

```
Logger: custom_components.kia_uvo.coordinator
Source: custom_components/kia_uvo/coordinator.py:104
Integration: Kia Uvo / Hyundai Bluelink ([documentation](https://github.com/fuatakgun/kia_uvo), [issues](https://github.com/fuatakgun/kia_uvo/issues))
First occurred: 11:19:23 am (98 occurrences)
Last logged: 0:55:22 pm

Unexpected error fetching kia_uvo data: expected string or bytes-like object
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/kia_uvo/coordinator.py", line 81, in _async_update_data
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 104, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 88, in check_and_refresh_token
    self.initialize()
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 51, in initialize
    self.update_all_vehicles_with_cached_state()
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 58, in update_all_vehicles_with_cached_state
    self.update_vehicle_with_cached_state(self.get_vehicle(vehicle_id))
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 61, in update_vehicle_with_cached_state
    self.api.update_vehicle_with_cached_state(self.token, vehicle)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 319, in update_vehicle_with_cached_state
    self.get_last_updated_at(get_child_value(state, "vehicleLocation.time")),
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 165, in get_last_updated_at
    m = re.match(r"(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})", value)
  File "/usr/local/lib/python3.10/re.py", line 190, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

**Comment by Symbiot78** [comment]
@cdnninja - I’ll admit I’ve restarted my HA maybe 12 times today over that last 6 hours

but for the first time ever since installing this integration my BlueLink app just told me I’ve exceeded my daily updates check
I opened the BlueLink app to unlock my car


Can it have anything to do with this?
Configuration is set to 60 minute scan interval 
And 240 force refresh

**Comment by cdnninja** [comment]
It could be an extended blue link outage.  Could you try again today.  And if still an issue @fuatakgun can you look into this?

**Comment by holdestmade** [comment]
I switched back to 1.8.0 and all works fine

**Comment by cdnninja** [comment]
> Different error, v2.0.1
> 
> ```
> Logger: custom_components.kia_uvo.coordinator
> Source: custom_components/kia_uvo/coordinator.py:104
> Integration: Kia Uvo / Hyundai Bluelink ([documentation](https://github.com/fuatakgun/kia_uvo), [issues](https://github.com/fuatakgun/kia_uvo/issues))
> First occurred: 11:19:23 am (98 occurrences)
> Last logged: 0:55:22 pm
> 
> Unexpected error fetching kia_uvo data: expected string or bytes-like object
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
>     self.data = await self._async_update_data()
>   File "/config/custom_components/kia_uvo/coordinator.py", line 81, in _async_update_data
>     await self.async_check_and_refresh_token()
>   File "/config/custom_components/kia_uvo/coordinator.py", line 104, in async_check_and_refresh_token
>     await self.hass.async_add_executor_job(
>   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 88, in check_and_refresh_token
>     self.initialize()
>   File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 51, in initialize
>     self.update_all_vehicles_with_cached_state()
>   File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 58, in update_all_vehicles_with_cached_state
>     self.update_vehicle_with_cached_state(self.get_vehicle(vehicle_id))
>   File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 61, in update_vehicle_with_cached_state
>     self.api.update_vehicle_with_cached_state(self.token, vehicle)
>   File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 319, in update_vehicle_with_cached_state
>     self.get_last_updated_at(get_child_value(state, "vehicleLocation.time")),
>   File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 165, in get_last_updated_at
>     m = re.match(r"(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})", value)
>   File "/usr/local/lib/python3.10/re.py", line 190, in match
>     return _compile(pattern, flags).match(string)
> TypeError: expected string or bytes-like object
> ```

This looks like a mapping issue.  Could I get the logs proceeding it?  Should have a dump about the car with a field named vehicleLocation.time in it.

**Comment by holdestmade** [comment]
That was the only thing in the logs

**Comment by cdnninja** [comment]
You will need to turn debug on for this.  Outlined here at the very bottom: https://github.com/fuatakgun/kia_uvo/tree/v2.0

**Comment by cdnninja** [comment]
I also think v2.0.15 solves this.

**Comment by holdestmade** [comment]
I tried v2.0.15, still the same. Debug logs below:

**Comment by cdnninja** [comment]
Ahh I see what is happening.  For some reason get location saying the API can't do this.  After that we crash because we don't see what the time was since we didn't get a response.   Thanks for this. Exactly the detail we need.

**Comment by cdnninja** [comment]
I have release v2.0.16 that is my first attempt to fix this. I can't test easily as I am not in EU. It did pass our integrated EU test which uses someone's car in the EU.

**Comment by holdestmade** [comment]
Still not working for me this is in the logs

This error originated from a custom integration.

Logger: custom_components.kia_uvo.coordinator
Source: custom_components/kia_uvo/coordinator.py:82
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 19:30:59 (2 occurrences)
Last logged: 20:16:50

Unexpected error fetching kia_uvo data: string indices must be integers
Unexpected error fetching kia_uvo data: 'vehicleStatusInfo'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/kia_uvo/coordinator.py", line 82, in _async_update_data
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 73, in check_and_force_update_vehicles
    self.force_refresh_vehicle_state(vehicle)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 83, in force_refresh_vehicle_state
    self.api.force_refresh_vehicle_state(self.token, vehicle)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 185, in force_refresh_vehicle_state
    state = self._get_forced_vehicle_state(token, vehicle)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 398, in _get_forced_vehicle_state
    return response["resMsg"]["vehicleStatusInfo"]
TypeError: string indices must be integers

**Comment by holdestmade** [comment]
Scrap that, it works with a reinstall. Option for mi. and km is gone though and a few other sensors missing.

**Comment by cdnninja** [comment]
> Scrap that, it works with a reinstall. Option for mi. and km is gone though and a few other sensors missing. 

Any sensors that were listed above?  The mi and km option will return. Just need time to work on it.  Right now it should follow your home assistant settings.

**Comment by holdestmade** [comment]
It does but in the UK we are metric but still use miles so its wrong.  Same as above I think. I'll have to roll back to 1.8 and see. Thanks.

**Comment by holdestmade** [comment]
Woke up to a few errors in the log this morning:
```

Logger: hyundai_kia_connect_api.KiaUvoApiEU
Source: /usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py:379
First occurred: November 5, 2022, 8:32:55 PM (3 occurrences)
Last logged: 9:47:58 AM

hyundai_kia_connect_api - _get_location failed
```

```
Logger: custom_components.kia_uvo.coordinator
Source: custom_components/kia_uvo/coordinator.py:82
Integration: Hyundai / Kia Connect (documentation, issues)
First occurred: 12:34:50 AM (18 occurrences)
Last logged: 9:35:45 AM

Unexpected error fetching kia_uvo data: string indices must be integers
Unexpected error fetching kia_uvo data: 'vehicleStatusInfo'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/kia_uvo/coordinator.py", line 82, in _async_update_data
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 73, in check_and_force_update_vehicles
    self.force_refresh_vehicle_state(vehicle)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 83, in force_refresh_vehicle_state
    self.api.force_refresh_vehicle_state(self.token, vehicle)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 185, in force_refresh_vehicle_state
    state = self._get_forced_vehicle_state(token, vehicle)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 398, in _get_forced_vehicle_state
    return response["resMsg"]["vehicleStatusInfo"]
TypeError: string indices must be integers
```

```
Logger: homeassistant.components.number
Source: components/number/__init__.py:117
Integration: Number (documentation, issues)
First occurred: November 5, 2022, 8:32:55 PM (3 occurrences)
Last logged: November 5, 2022, 8:32:55 PM

custom_components.kia_uvo.number is setting deprecated attributes on an instance of NumberEntityDescription, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
custom_components.kia_uvo.number::HyundaiKiaChargingLimitNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
```

**Comment by holdestmade** [comment]
For info, sensors with 18.0:

Air Conditioner
Back Window Heater
Car Battery
Data
Defroster
Door - Front Left
Door - Front Right
Door - Rear Left
Door - Rear Right
Engine
Hood
Last Update
Low Fuel Light
Odometer
Range by Fuel
Set Temperature
Steering Wheel Heater
Tire Pressure - All
Tire Pressure - Front Left
Tire Pressure - Front Right
Tire Pressure - Rear Left
Tire Pressure - Rear Right
Trunk

And with 2.0.16:
Air Conditioner
Back Left Door
Back Right Door
Back Window Heater
Car Battery Level
Defrost
Engine
Front Left Door
Front Right Door
Fuel Low Level
Last Updated At
Odometer
Set Temperature
Steering Wheel Heater
Trunk

**Comment by cdnninja** [comment]
Tires, and hood have been added. Can't remember if hood is released yet but fixed for next.  

As for the "string indices must be integers".  Looks like the EU API is unreliable.   I will need to adjust the code to handle this and ignore it until next polling cycle.

**Comment by cdnninja** [comment]
Lets track this over in #424. Could you report back on if this is fixed and how things have been in the last release? Thinking I close this thread out as initial issue and a few posted after have been fixed. 

I will close this some time tomorrow or Saturday.

**Comment by holdestmade** [comment]
Just tried 2.0.26, Failed to set up. Will post in #424

**Comment by cdnninja** [comment]
20.
