### ISSUE TITLE
Start climate control?

### ISSUE THREAD

**Issue by elektrinis** [fuatakgun/kia_uvo#394]
I have an IONIQ 5 and currently can only lock/unlock the car through HA, all other entities ar read only.
I would like to also have the option to enable climate control with a single tap. Is this possible?
This would also give us many options for automation, like activating climate control based on weather.

**Comment by cdnninja** [comment]
Other actions are services.  If you want one touch you can add that with config with the correct options for your car.  I'm not comfortable doing one touch out of the box for safety reasons.

**Comment by elektrinis** [comment]
This could be useful as well. I didn't know there are services. Just checked and see it's doable. Thank you!
