### ISSUE TITLE
Fuel level

### ISSUE THREAD

**Issue by CVHvisuals** [fuatakgun/kia_uvo#395]
Missing fuel level for 2022 Tucson
V2.0.5

**Comment by cdnninja** [comment]
Which region?

**Comment by cdnninja** [comment]
Could you try out v2.0.7?

**Comment by CVHvisuals** [comment]
Fuel level populated and shows the current level. Thank you!On Nov 2, 2022, at 10:18, cdnninja ***@***.***> wrote:﻿
Could you try out v2.0.7?

**Comment by cdnninja** [comment]
Thanks for reporting this and testing our alpha/ beta!
