### ISSUE TITLE
Force Update button and second account

### ISSUE THREAD

**Issue by Mkay505** [fuatakgun/kia_uvo#396]
Would be great getting a "force update" button.
I want to create an automation while the vehicle is charging.
So I could cyclically query the state of charge.

And a parallel account login would be awesome for our second KIA car.

**Comment by cdnninja** [comment]
You can add a force update button that calls the service. As well version 2.0 supports multiple accounts.

**Comment by Mkay505** [comment]
Found the service - thank you. :)
