### ISSUE TITLE
Looks great !

### ISSUE THREAD

**Issue by realfire23** [fuatakgun/kia_uvo#4]
Hi,

looks good, integration was super easy !

Thank you very much for your great work !!! 1111 👍 

Is there any reason the integration "only" creates 10 entities? e.g. on your screenshot it shows the 12 v battery but the entity wasnt created in Homeassitant when I installed it.

Thank you again !

**Comment by fuatakgun** [comment]
I believe it is because of different configuration of cars. 
You can share the niro data entity from developer tools and we can work out together. 
But, if I am not mistaken, EV vehicles does not have 12v battery, I own a PHEV (plugin hybrid) so mine has one

**Comment by realfire23** [comment]
Hi 👍 

I know its a pitty but yes EV also have 12V batteries and the niro really has some issues with it. As a result I want to make some automationes based on it. Basically I am interessted in the same values as you PHEV from your screenshot (https://github.com/fuatakgun/kia_uvo)

Cant thank you enough for that integration !

Here 

`vehicle_data:
  vehicleLocation:
    coord:
      lat: 
      lon: 
      alt: 7
      type: 0
    head: 167
    speed:
      value: 0
      unit: 1
    accuracy:
      hdop: 10
      pdop: 10
    time: '20210411084930'
  vehicleStatus:
    airCtrlOn: false
    engine: false
    doorLock: true
    doorOpen:
      frontLeft: 0
      frontRight: 0
      backLeft: 0
      backRight: 0
    trunkOpen: false
    airTemp:
      value: 14H
      unit: 0
      hvacTempType: 1
    defrost: false
    acc: false
    evStatus:
      batteryCharge: false
      batteryStatus: 69
      batteryPlugin: 0
      remainTime2:
        etc1:
          value: 20
          unit: 1
        etc2:
          value: 235
          unit: 1
        etc3:
          value: 55
          unit: 1
        atc:
          value: 85
          unit: 1
      drvDistance:
        - rangeByFuel:
            evModeRange:
              value: 270
              unit: 1
            totalAvailableRange:
              value: 270
              unit: 1
          type: 2
      reservChargeInfos:
        reservChargeInfo:
          reservChargeInfoDetail:
            reservInfo:
              day:
                - 4
              time:
                time: '0530'
                timeSection: 0
            reservChargeSet: false
            reservFatcSet:
              defrost: false
              airTemp:
                value: 0CH
                unit: 0
              airCtrl: 0
              heating1: 0
        offpeakPowerInfo:
          offPeakPowerTime1:
            starttime:
              time: '1200'
              timeSection: 0
            endtime:
              time: '1200'
              timeSection: 0
          offPeakPowerFlag: 0
        reserveChargeInfo2:
          reservChargeInfoDetail:
            reservInfo:
              day:
                - 4
              time:
                time: '1200'
                timeSection: 0
            reservChargeSet: false
            reservFatcSet:
              defrost: false
              airTemp:
                value: 0CH
                unit: 0
              airCtrl: 0
              heating1: 0
        reservFlag: 0
        ect:
          start:
            day: 9
            time:
              time: '1200'
              timeSection: 0
          end:
            day: 9
            time:
              time: '1200'
              timeSection: 0
        targetSOClist:
          - targetSOClevel: 80
            dte:
              rangeByFuel:
                evModeRange:
                  value: 314
                  unit: 1
                totalAvailableRange:
                  value: 314
                  unit: 1
              type: 2
            plugType: 0
          - targetSOClevel: 80
            dte:
              rangeByFuel:
                evModeRange:
                  value: 314
                  unit: 1
                totalAvailableRange:
                  value: 314
                  unit: 1
              type: 2
            plugType: 1
    ign3: true
    hoodOpen: false
    transCond: true
    steerWheelHeat: 0
    sideBackWindowHeat: 0
    tirePressureLamp:
      tirePressureLampAll: 0
      tirePressureLampFL: 0
      tirePressureLampFR: 0
      tirePressureLampRL: 0
      tirePressureLampRR: 0
    battery:
      batSoc: 62
      batState: 0
    time: '20210411084931'
  odometer:
    value: 1764
    unit: 1
friendly_name: NIRO EV 19 Data
`

**Comment by badguy99** [comment]
This is probably a duplicate of #3 that has been resolved.

**Comment by realfire23** [comment]
mega!!! thank you.

GJ
