### ISSUE TITLE
Forced update "Not enrolled" error and subsequent exception

### ISSUE THREAD

**Issue by Linwood-F** [fuatakgun/kia_uvo#418]
Region: USA
Kai EV6 Wind with Technology Package 

Fresh install on HA 2022.10.3 running V2.0.17 via HACS. 

It is creating the device and 29 entities, mostly correct. While testing I have done a service call of update (which appears to do nothing, though it succeeds) and Forced Update, which gives an error every time. 

Debug showing data normally returned upon HA server restart is in issue 410 posted for unrelated reasons.

[DebugLog.txt](https://github.com/fuatakgun/kia_uvo/files/9947783/DebugLog.txt)

**Comment by cdnninja** [comment]
Can you confirm a force refresh works in the native app?

**Comment by Linwood-F** [comment]
To be sure I understand the terminology (sorry, only 2nd day with car) this is the app "Kia Access" (on Android) and hitting the refresh icon at the top, yes, it says "Updating vehicle information" for about 10 seconds then shows refreshed data and "Updated: Now".

**Comment by Linwood-F** [comment]
I can also see the car on [https://owners.kia.com/content/owners/en/dashboard.html/](url)

**Comment by Linwood-F** [comment]
An update on this.  I left it running overnight.  After first setting up the integration I had 29 sensors reporting data.  By morning they all went to "not available" and no data, and it appears to be the same "Not enrolled" error but after a (I think) successful signin.  Here's a sample of that log from the wee hours.

I did change the time of polling to be 24hrs (set both start/end to zero). 

[DebugLog.txt](https://github.com/fuatakgun/kia_uvo/files/9951903/DebugLog.txt)

I did a developer/yaml/restart of HA and did not get them back.  I believe (based on some testing I did when i first set up) if I delete the integration and re-add they will come back with values.

**Comment by cdnninja** [comment]
This one is somewhat complicated.   I think the tokens are expiring and not refreshing.  The old version 1.8.X should work but for some reason it isn't refreshing for 2.0.  If able to develop feel free to give it a look and tinker:
https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/master/hyundai_kia_connect_api/KiaUvoAPIUSA.py

It may take me a bit - not easy since I can't test myself.

**Comment by Linwood-F** [comment]
This went south pretty badly.  I had a theory that the issue was credentials.  Kia somehow has me set up with a phone number as an ID, and a email as an ID (same email is on both accounts, as is same phone number; really poor software there!).  One of those has the car labeled "not linked" and the other has the car with connect activated. 

So I went back to see which account I used, and noticed a new version.  I downloaded, updated, and restarted HA.  The entities all came back and were active, but I wanted to check the credentials in use, and there is where it went south -- HA's Settings, Devices & Services, Integrations did not show it.  Just not on the page.  HACS still showed it, and the devices and entities still had everything.

I tried removing from HACS with the GUI without success (said it was still in use).  I tried a lot of things, many reboots, never came visible.  I finally SSH'd into the HA server and deleted it entirely from custom components.  

A couple restarts and removal from HACS GUI and it seemed like I was back to the beginning, so added it and restarted -- not on the integration screen (correct, it wasn't configured) but when I hit add integration it hung -- no list of brands.  Hung forever.  Went back to HACS and deleted it (worked this time) and now add integration pops up a list of brands.

So it's doing something wacky, at least on my system.  But it is POSSIBLE that the issue with not enrolled is related to the fact I somehow ended up with two accounts.   My guess is one created from the android app and one from the web.

But I think I will not install again, either I have introduced some corruption or it is not working and playing well with my configuration and HACS there.

**Comment by cdnninja** [comment]
The home assistant DB most likely still has entries in it for this integration.  That can cause strange behavior if force changes occur.  If you do decide to install again and have that hang again just post the logs.  We could probably find a way to handle setup if the data exists even though it isn't configured.   If calling it quits all good.  

Other option is we get you up and running on version 1.8X(Stable release).

**Comment by Linwood-F** [comment]
I decided to try this again.

I removed the alternative Kia integration I was using (dahlb/ha_kia_hyundai) that seemed to be working OK, mostly.

I deleted all the state information (with SQL) from your integration and that integration.

So at this point HACS had neither one.  I then added this integration, set the allow beta, after adding it showed update available, did the update. 

Then I went to add the integration itself, and when i did, I got the same problem --- the drop down lists of integrations just never completes, no list at all. 

So there's something weird, at least on my system, with the 2.x version.  I removed it in HACS, added back the alternative above, it appears properly in the integration/add dialog. 

I did get the logs when this happened, it has the following: 

`2022-11-09 16:24:25.080 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140154544355072] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 755, in handle_integration_descriptions
connection.send_result(msg["id"], await async_get_integration_descriptions(hass))
File "/usr/src/homeassistant/homeassistant/loader.py", line 287, in async_get_integration_descriptions
custom_flows[integration.integration_type][integration.domain] = metadata
KeyError: 'hub'`

**Comment by cdnninja** [comment]
Looks like this was a 2022.11.0 and .1 issue: https://community.home-assistant.io/t/unable-to-add-integrations-from-ui/482612/5

Have you tried with .2 of HACS?

**Comment by Linwood-F** [comment]
I'm on HACS 1.28.3 running HA 2022.11.2 now.  I honestly don't recall whether I last tried this before or after I upgraded to 2022.11.2 (I skilled .1 and .0). 

But yes, I think it may be fixed.  I downloaded your 2.0.24 and it no longer hangs.  I'm not sure i want to run it, as I've started accumulating data with a similar integration and not keen to start over.  I don't suppose there is a way to change the vehicle name, e.g. instead of everything starting with EV6_ to provide a different prefix overriding it?  Then I could run both, compare, etc.  Right now they step on each others names (and end up with _2, etc. but only on some). 

But to the point of this issue I think it may be fixed.  I think this also may explain the original issue -- I installed the 1.x version, configured, then upgraded to 2.x.  If  2.x couldn't be processed on the integrations screen it would explain why I couldn't remove it.

**Comment by cdnninja** [comment]
If you rename a device it should rename all child items.  Can't promise anything. :)  The other integration you are referencing is a fork of this one.  That person did write most of the USA Kia portion of this integration.  Happy with whichever way you want to go.  Just glad the issue is sorted out.

**Comment by Linwood-F** [comment]
Good to know, but it's going to create all the devices before I get a chance to rename the device, as best I can tell.  Anyway, I think this issue is done.
