### ISSUE TITLE
v2.0.21 (potentially earlier) - all services missing

### ISSUE THREAD

**Issue by DJBenson** [fuatakgun/kia_uvo#425]
I am not sure when this happened but I'm guessing as HA has just started throwing the error of an unknown service being used in a script that it appeared in .21 but I have no services at all.

**Comment by cdnninja** [comment]
When you say you have no services you mean when going into the developer service menu and search Kia it is blank?

**Comment by cdnninja** [comment]
Could you also restart to confirm this isn't a HA loading issue?

**Comment by DJBenson** [comment]
Yes indeed, the services are not available.
![image](https://user-images.githubusercontent.com/1013909/201070202-ea450fa2-29a5-41d7-ad1a-c831e84e3bfc.png)

I have restarted HA several times and the integration is loaded (i.e. the rest of the sensors are showing data).

**Comment by DJBenson** [comment]
This was the first I knew about it...
![image](https://user-images.githubusercontent.com/1013909/201070477-edf2230c-d59e-4598-b209-cf4a9d44b16a.png)

**Comment by DJBenson** [comment]
I've installed 2.0.23 just now and the services are back.
