### ISSUE TITLE
Set Temperature 02H °C

### ISSUE THREAD

**Issue by rindlerblabla** [fuatakgun/kia_uvo#427]
**Region and Brand of car**
EU Kia

**Describe the bug**
Since 2.0 the default set temperature is "02H" °C. Before it was 15°C.

![Screenshot_20221110-211438_Home Assistant.jpg](https://user-images.githubusercontent.com/28257974/201197030-b719aca2-75fa-4b18-94a5-b191b4a11c37.jpg)

**Comment by cdnninja** [comment]
Please re-download v2.0.24. It should resolve.  May take a redownload if already on that version.  Had a release issue.

**Comment by rindlerblabla** [comment]
Can confirm it is now working.
