### ISSUE TITLE
No module named 'homeassistant.util.unit_conversion'

### ISSUE THREAD

**Issue by spacecowboy** [fuatakgun/kia_uvo#429]
**Region and Brand of car**

EU, Kia E-Niro

**Describe the bug**
So I just updated the plugin and got this message:

    Unable to prepare setup for platform kia_uvo.sensor: Platform not found (No module named 'homeassistant.util.unit_conversion').

Is there a minimum required version of home assistant maybe that has changed?

**Comment by cdnninja** [comment]
The old unit conversion was deprecated in 2022.10.  So we moved to that ('homeassistant.util.unit_conversion').  I do not know when that was added though. So if on an old version of home assistant you will need to downgrade this integration.

**Comment by cdnninja** [comment]
Just checked.  The file in the home assistant core github was created in September in Dev.  So a very fast migration.  I will update our minimum requirements.

**Comment by spacecowboy** [comment]
ok cool thanks for checking.  i have no trouble with upgrading its just a bit of a hassle.
