### ISSUE TITLE
Duplicate devices created for a single vehicle

### ISSUE THREAD

**Issue by davidski** [fuatakgun/kia_uvo#430]
**Region and Brand of car**

US, Ioniq 5 2022

**Describe the bug**

Updating to v2.0.24 beta via HACS from v1.x (latest stable release) results in two devices with the same name being available. One device has no entities associated with it while the second has all the expected entities. I am unable to delete the zero entity device, but can rename it. The zero entity device had the area associated with my device under 1.x, so I assume this is a migration issue.

**Debug logs if an error occurred**

No errors.

**To Reproduce**

Presumably have a 1.x US vehicle configured then migrate over to 2.0.34,

**Expected behavior**

Just one device per vehicle.

**Comment by cdnninja** [comment]
I am not sure if historical data carries over.  If not are you okay to remove the integration and readd to confirm this is a migration issue?   We do use different entities because the old model didn't support multiple cars.  We needed to re-ID them to do so.

**Comment by davidski** [comment]
Sure thing! Deleting the integration, then re-adding (with fresh credentials) results in just a single device being created, as expected. This looks like a migration hiccup!

**Comment by cdnninja** [comment]
I am thinking this is a specific bug related to USA's integration.  If someone else has this occur for a different region please let me know as it changes my approach on figuring this one out.

**Comment by cdnninja** [comment]
I can't seem to replicate and no one else has come here to report this.  From what I can tell we have atleast 25-30 people on 2.X could you try replicate this again?

**Comment by cdnninja** [comment]
I am going to close this out.  If something has this happen again please let us know.
