### ISSUE TITLE
Add a second account and car association 

### ISSUE THREAD

**Issue by pretori** [fuatakgun/kia_uvo#431]
Hi

in our family we have two Kia’s. Is it possible to add the second account and also get information from the car associated to that account?

**Comment by cdnninja** [comment]
Should work with the new beta 2.0 branch.

**Comment by pretori** [comment]
Reinstalled with v. 2.0.26, can't see how i can add a second account.

**Comment by cdnninja** [comment]
I haven't tested this since I only have a single car.  

Two ways exist for two cars:

1. Go through the setup flow a second time.  So add the integration again. 
2.  Use a single account and it should detect the two cars on it.

**Comment by pretori** [comment]
It's not possible to go through the setup flow a second time, I just get an empty Kia Uvo / Hyundai Bluelink screen.
![pic](https://user-images.githubusercontent.com/80861039/201483401-678e19ef-7320-4d58-8731-f89781c435ea.JPG)

**Comment by cdnninja** [comment]
I confirmed on my side that it shows up correctly. I just don't have a second set of creds to enter.   Could you check for errors in the logs and reboot?  Home assistant integration gui is known to be buggy.

**Comment by pretori** [comment]
Ahh worked alot better :-)

**Comment by cdnninja** [comment]
Awesome! Keep us posted on how this goes.  Would love to hear if it goes well.  2.0 is a full rewrite partially to support multiple brands and cars.  Unfortunately hard for me to test.

**Comment by pretori** [comment]
Yes, i posted a new issue :-) With pictures :-)
