### ISSUE TITLE
Sensors showing off - 2.0.26

### ISSUE THREAD

**Issue by pretori** [fuatakgun/kia_uvo#434]
2.0.26

**Region and Brand of car**
Europe
E-Niro
Niro PHEV 

**Describe the bug**
Doors and Trunk show Off instead of Closed
Tyre pressure on all sensor show off instead of Ok.

Niro Phev car battery shows 255%

**Screenshots**
Niro PHEV
![Niro PHEV 2019](https://user-images.githubusercontent.com/80861039/201484870-5ce52afd-5a35-4b54-9cbc-8e93cc840e30.JPG)

E-Niro
![E-Niro](https://user-images.githubusercontent.com/80861039/201484890-61bf74af-d2e5-480c-a4dc-2da9aac5112a.JPG)

**Comment by cdnninja** [comment]
For the binary sensors showing off we moved these to binary instead of plain text.  It should make it easier to drive automation on them as they are standardized.  Unfortunately we can't adjust the text displayed for state.  Maybe we rename them so it would be "Tire Pressure Warning - All": Off.  Or "Hood Open": Off  Thoughts? 

As for the battery could you enable debug logs and post that cars data? Interested to see what it is showing. How to enable debug logs are here at the very bottom: https://github.com/fuatakgun/kia_uvo/tree/v2.0

**Comment by cdnninja** [comment]
As well are you okay if we use one of these pictures for documentation in github? Our current picture is pretty outdated on what we offer and my little ICE doesn't show much.

**Comment by cdnninja** [comment]
Actually let me dig in further on the door topic. I may be able to fix.

**Comment by pretori** [comment]
> As well are you okay if we use one of these pictures for documentation in github? Our current picture is pretty outdated on what we offer and my little ICE doesn't show much.

It OK :-)

**Comment by cdnninja** [comment]
All but battery are fixed in the next release.  I will dig in once I have logs from you on that one.

**Comment by pretori** [comment]
Accualy the PHEV is going to the workshop this week due to a battery problem, so I accually dont know if the car is report wrong value or no. It has been in and out of the workshop since it was new..... Same error. I enabled the logger as instructed in the configuration.yaml. 

Values from PHEV

![bild](https://user-images.githubusercontent.com/80861039/201523837-7dfc4f0e-cbdd-40d4-9f59-5d05223abb79.png)

Values from E-niro

![bild](https://user-images.githubusercontent.com/80861039/201523949-27766430-756b-49b2-a21a-b614f5f0c426.png)

**Comment by cdnninja** [comment]
Interestingly enough bat State is 1. I don't know what that means.  What does you app show?

**Comment by pretori** [comment]
The Kia app doesn’t show the car battery 🙂

**Comment by cdnninja** [comment]
So either this 1. Normal and we should actually look at bat state. If 1 don't report on it.  Or 2.  Your car is broken.   

hard for me to know which is the case until another PHEV Niro user from your region comes around.

**Comment by pretori** [comment]
Let’s hope someone else can provide the information. I’ll check the bat state after the car has been in the workshop and report.

**Comment by cdnninja** [comment]
Sounds good!

**Comment by cdnninja** [comment]
Have you heard from the shop?

**Comment by pretori** [comment]
Car is still in shop, worked for 9 hours after the shop fitted a new battery.....then it was back to the shop. It won't come home until they have found the fault.

**Comment by pretori** [comment]
A can accually se the car in the shop it says {'batSoc': 50, 'batState': 0} now, so batState one is strange.

**Comment by cdnninja** [comment]
How about we close for now since it looks like now the sensor is reporting correctly?   This seems to be something with the car, we could probably force the data to not show outside of 0-100 but not sure if worth it when this is what the car reports.
