### ISSUE TITLE
"Login failed into Kia Uvo EU Servers." upon (re-)adding the integration

### ISSUE THREAD

**Issue by ManCaveMedia** [fuatakgun/kia_uvo#45]
After updating HA to 2021.6 (not sure if it's related) I can't login to the EU server anymore.

After getting error messages (not documented, sorry) I decided to re-add the integration, but now I receive an error:
`Login failed into Kia Uvo EU Servers. Please use official Kia Uvo app to logout and log back in and try again!`

I did as suggested, but I still receive the same error while trying to add the integration.

**Comment by romix63** [comment]
same error

**Comment by fuatakgun** [comment]
Same error for me without HA upgrade, will fix tonight and hopefully come with a long term solution.

**Comment by fuatakgun** [comment]
please get the latest changes and restart your HA instance. I am not expecting you to remove and add integration. In case, it is still not working after HA restart, please remove and add integration and let me know the results.

With latest change, I am fetching latest stamps over here: https://raw.githubusercontent.com/neoPix/bluelinky-stamps/master/kia.json
But they are not all valid, I am trying 10 times to find a valid one and i am using the found stamp for 1 day.

**Comment by ValQuev** [comment]
Hi @fuatakgun,

With the previous version, I was unable to login due to an error 4071 from Kia if I remember correctly.

With this new version, only after removing and installing your integration, I am now able to use it.

Thank you for your work :)

**Comment by Reidar6** [comment]
Works perfectly now, thanks
