### ISSUE TITLE
ABRP Integration

### ISSUE THREAD

**Issue by stimmerman** [fuatakgun/kia_uvo#48]
Hi!

First of all, thanks for creating this integration, it works out of the box 💯 

I wonder if you could integrate sending the data to ABRP. I'm currently using Tronity to do this, but is has some disadvantages:

- It does not retrieve live data if the car is driving, I have to open the UVO app, hit refresh and then wait for Tronity to pick up that data from the UVO servers and send it to ABRP.
- It costs 4 eur a month..

I think this integration can make a difference there because:

- There isn't a plugin for home-assistant that does this for Kia Uvo (there is for homey I think)
- You already have all the metrics from the car
- You could for example increase the polling to 15/30 minutes if it's detected the car is driving.
- You already integrate with the config flow, setting it up would be a bliss.

I have some examples to might help to estimate if this is something you might consider:
- [ABRP example used in a plugin for the old Kia app](https://github.com/TheBazeman/MijnKia/blob/master/MijnKia.py)
- [ABRP API docs in python](https://documenter.getpostman.com/view/7396339/SWTK5a8w?version=latest)

As a suggesting on how to set it up:

- Make it optional during configuration, users only have to enter their ABRP API key to send the data.
- Make it configurable to send the data in 30 minutes interval when driving is detected (maybe with an switch so you could turn it on/off)

Think it would be great! Going on a long trip, flip the switch in home-assistant and voila, ABRP gets the data every 30 minutes and updates the routing plan 😎

**Comment by fuatakgun** [comment]
Thanks for feedback and very detailed request. 

Overall, I see that we can find a solution here within existing integration or a separate integration, on the other hand, I am a bit confused on this part `You could for example increase the polling to 15/30 minutes if it's detected the car is driving.`. Let me give you some background, this integration is only reading from cached data from Kia servers and this cached data will be updated by car automatically in every 10-15 minutes if you are driving or integration will call `force_update` command, which is imitating `Refresh` button in Uvo app.

So, I am not clear why you need to click Refresh button in Uvo app, it should be done automatically in background. On the other hand, there are other issues as you mentioned;
- Tronity needs to pick up this data in next cycle (by the way, I am totally unfamiliar with Tronity).
- You have to pay monthly fee.

I am more inclined to have a separate integration between home assistant and ABRP like;
- set the integration with API key
- match api data template with your existing sensors 
- set the interval

This would enable all other existing smart cart integrations to get benefit from this, what do you think?

P.S.: I own a Kia Niro PHEV and ABRP apparently doesn't support it, you need to commit on testing this.

**Comment by danieldotnl** [comment]
Did you see this thread: https://community.home-assistant.io/t/build-rest-command-to-send-data-to-abetterrouteplanner-com/307380 ?

**Comment by fuatakgun** [comment]
Thanks for sharing @danieldotnl , this is good enough to resolve this
