### ISSUE TITLE
Integration doesn't start without region configured

### ISSUE THREAD

**Issue by lars-viklund** [fuatakgun/kia_uvo#50]
After updating to 2c0853f the integration doesn't start:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/kia_uvo/__init__.py", line 123, in async_setup_entry
    await update(dt_util.utcnow())
  File "/config/custom_components/kia_uvo/__init__.py", line 110, in update
    event_time_local = event_time_utc.astimezone(getTimezoneByRegion(vehicle.kia_uvo_api.region))
  File "/config/custom_components/kia_uvo/utils.py", line 17, in getTimezoneByRegion
    if REGIONS[region] == REGION_CANADA:
KeyError: False
```

**Comment by Reynders1** [comment]
Same here. Even after removing the integration and installing it new with EU region, the problem remains, with the same error.

**Comment by lars-viklund** [comment]
> Same here. Even after removing the integration and installing it new with EU region, the problem remains, with the same error.

Thanks for confirming that you can reproduce the issue I'm seeing. I didn't try reinstalling the integration. Then the title is somewhat misleading.

**Comment by fuatakgun** [comment]
sorry for the problem, i am on it

**Comment by fuatakgun** [comment]
reverted back latest changes, please update your local installation, it should work fine.

**Comment by lars-viklund** [comment]
> reverted back latest changes, please update your local installation, it should work fine.

Confirmed

**Comment by Reynders1** [comment]
Having problems with the login, also with the UVO app. Receiving error 500. Seems having a problem on Kia servers. I'll keep trying.

**Comment by Reynders1** [comment]
Confirmed. It's also working fine for me.
