### ISSUE TITLE
Exception kia_uvo login : 'redirectUrl' - migrated account (UK=EU?!)

### ISSUE THREAD

**Issue by DJBenson** [fuatakgun/kia_uvo#51]
Hi

I'm trying to log into my migrated account, assuming that the UK is still classed as the EU as far as Kia are concerned (the website url I see to log in is eu-account.kia.com so I presume so) but is throwing the same error as #22.

Username and password are copied from keychain (the exact details used to log into the app on my iPhone) so certain they are correct.

**Comment by fuatakgun** [comment]
Nothing comes to my mind other then;
- you either create me a test account and share your car
- you share your login credentials


sorry

**Comment by fuatakgun** [comment]
we found a solution with someone;
- create a new account and share your car with it
- test with new accounr
