### ISSUE TITLE
Integration Battery

### ISSUE THREAD

**Issue by eximo84** [fuatakgun/kia_uvo#54]
The battery on the integration screen defaults to the 12v battery where as this would be better showing the EV battery

![image](https://user-images.githubusercontent.com/25502878/128667513-0a15bf72-b051-4a5a-bc49-a74bff3709cf.png)

**Comment by cdnninja** [comment]
Do you know an icon that would be a better fit?  Only one I could find doesn't show charge level in the icon.

**Comment by eximo84** [comment]
What do you mean?

**Comment by cdnninja** [comment]
I thought you meant the icon was wrong.  Or are you saying the value is not your ev battery?

**Comment by cdnninja** [comment]
Gotcha.  I can't seem to find a spot this is set in code.  The 12v is declared first though so I may switch the order.

**Comment by fuatakgun** [comment]
Yep, there is no easy way to do this, maybe we can switch the ordering?

**Comment by fuatakgun** [comment]
OOO for 2 weeks.

**Comment by fuatakgun** [comment]
thanks to @cdnninja , this should be resolved.

**Comment by fuatakgun** [comment]
pushed a follow up commit to fix the indentation issue

**Comment by fuatakgun** [comment]
actually, none of them had fixed it, apparently this is related to naming of entities.

I have renamed `sensor.niro_car_battery` sensor into `sensor.niro_z_car_battery` and it worked.

I would keep this resolved.
