### ISSUE TITLE
Battery Incorrect Report - Drops to zero randomly

### ISSUE THREAD

**Issue by eximo84** [fuatakgun/kia_uvo#55]
Odd issue where the battery for a period of time showed 0% despite showing 90% previously. 

This actually reflected the app until i forced a refresh to get the value back to normal. I've noticed this a few times with the bluelink app?

Maybe some logic to check for instant recharge of battery which couldn't happen unless the odometer increases or something is left on but even then it wouldn't be 90%-0%

![image](https://user-images.githubusercontent.com/25502878/128667741-3274fbd9-1820-47f1-ad53-9e0b34fd0c77.png)

**Comment by fuatakgun** [comment]
Checking sudden changes might look suitable for EVs but not suitable for PHEV, they have a range of 50km (9kwh) and decrease can happen so quickly. But I noticed that this is happening when car is still / not moving. If you can confirm this too, I can come up with a solution;
- if car was not running and is not running now and
- if EV battery decreased to 0% and previous value was not 0%
- initiate force_update.

**Comment by eximo84** [comment]
Yep car was stationary and hadn't moved.  Logic sounds good.

**Comment by fuatakgun** [comment]
OOO for 2 weeks.

**Comment by cdnninja** [comment]
Maybe we either

1. Force a rescan if a 0 value occurs.  I would think most people don't run a car to 0%. 
2. Force a rescan when the value changes by more than X percentage from last value.    

First one may be an easy approach but based on the above chart 0% doesn't seem to be the only issue as I assume your car didn't go from 35 to 100 in a single scan.

**Comment by dahlb** [comment]
I'm going to try to put this logic into a pr tomorrow

- if car was not running and is not running now and
- if EV battery decreased to 0% and previous value was not 0%
- initiate force_update.

**Comment by dahlb** [comment]
https://github.com/fuatakgun/kia_uvo/pull/144 should fix this, extra testers needed as it takes a while to repro, I'll be running for a few days and expect to see no errors and no more 0 logs
