### ISSUE TITLE
Non integer mile conversion

### ISSUE THREAD

**Issue by gadgetshed** [fuatakgun/kia_uvo#61]
When using miles for default units the Range Total and Range by EV fields have a full converted value e.g. 223.68932 miles.  Can this be rounded down to nearest mile to give 223.  So it displays better in homeassistant.
![Screenshot 2021-09-10 134913](https://user-images.githubusercontent.com/47116236/132855783-5fad35da-5060-4b76-a2e4-adf6056d58be.png)

**Comment by fuatakgun** [comment]
I prefer to keep same experience between KM and Miles. By default, KM shows 1 decimal point as `11,293.7 km`

Is this format fine for you?

**Comment by gadgetshed** [comment]
Yeah that's fine just not multiple decimal places

**Comment by fuatakgun** [comment]
what values do you see in UVO, miles or KM? because, if conversion is happening through integration, the result of conversion should be INTEGER (bad on me). Check example screenshot below given that UVO shows values in KM and I have picked MILES in integration configuration;
![image](https://user-images.githubusercontent.com/11085566/133605104-7424bb2b-d2cc-44df-8658-6145acd23b76.png)

**Comment by gadgetshed** [comment]
Still subject to the UVO bug where when it loads initially it shows kms but when you refresh it switches to miles in the app. The app preferences are set to miles.

**Comment by fuatakgun** [comment]
can you dump your `E-NIRO Data` sensor here after removing sensitive information?

**Comment by gadgetshed** [comment]
Vehicle data
vehicleLocation:
coord:
lat: 0
lon: 0
alt: 0
type: 0
head: 89
speed:
value: 0
unit: 0
accuracy:
hdop: 10
pdop: 10
time: '20210916220552'
geocodedLocation:
place_id: 111
licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
osm_type: way
osm_id: 42741566
lat: ’51’.0
lon: ‘-1.0
display_name: >-
hidden
address:
road:  Crescent
suburb: C
village: North A
county: aa
state_district: South West England
state: England
postcode: XXx xXX
country: United Kingdom
country_code: gb
boundingbox:
- '51'
- '51'
- '-1.7'
- '-1.7'
vehicleStatus:
airCtrlOn: false
engine: false
doorLock: true
doorOpen:
frontLeft: 0
frontRight: 0
backLeft: 0
backRight: 0
trunkOpen: false
airTemp:
value: 02H
unit: 0
hvacTempType: 1
defrost: false
acc: false
evStatus:
batteryCharge: false
batteryStatus: 81
batteryPlugin: 0
remainTime2:
etc1:
value: 53
unit: 1
etc2:
value: 430
unit: 1
etc3:
value: 105
unit: 1
atc:
value: 60
unit: 1
drvDistance:
- rangeByFuel:
evModeRange:
value: 230.52427
unit: 3
totalAvailableRange:
value: 230.52427
unit: 3
type: 2
reservChargeInfos:
reservChargeInfo:
reservChargeInfoDetail:
reservInfo:
day:
- 9
time:
time: '1200'
timeSection: 0
reservChargeSet: false
reservFatcSet:
defrost: false
airTemp:
value: 00H
unit: 0
airCtrl: 0
heating1: 0
offpeakPowerInfo:
offPeakPowerTime1:
starttime:
time: '1200'
timeSection: 0
endtime:
time: '1200'
timeSection: 0
offPeakPowerFlag: 0
reserveChargeInfo2:
reservChargeInfoDetail:
reservInfo:
day:
- 9
time:
time: '1200'
timeSection: 0
reservChargeSet: false
reservFatcSet:
defrost: false
airTemp:
value: 00H
unit: 0
airCtrl: 0
heating1: 0
reservFlag: 0
ect:
start:
day: 9
time:
time: '1200'
timeSection: 0
end:
day: 9
time:
time: '1200'
timeSection: 0
targetSOClist:
- targetSOClevel: 100
dte:
rangeByFuel:
evModeRange:
value: 287
unit: 3
totalAvailableRange:
value: 287
unit: 3
type: 2
plugType: 1
- targetSOClevel: 100
dte:
rangeByFuel:
evModeRange:
value: 287
unit: 3
totalAvailableRange:
value: 287
unit: 3
type: 2
plugType: 0
ign3: true
hoodOpen: false
transCond: true
steerWheelHeat: 0
sideBackWindowHeat: 0
tirePressureLamp:
tirePressureLampAll: 0
tirePressureLampFL: 0
tirePressureLampFR: 0
tirePressureLampRL: 0
tirePressureLampRR: 0
battery:
batSoc: 76
batState: 0
sleepModeCheck: false
time: '20210916220553'
remoteWaitingTimeAlert:
remoteControlAvailable: 1
remoteControlWaitingTime: 168
elapsedTime: '02:48:21'
systemCutOffAlert: 0
tailLampStatus: 0
hazardStatus: 0
odometer:
value: 397.9
unit: 1
Vehicle name
E-NIRO

**Comment by gadgetshed** [comment]
As a further development this morning it shows as follows:
![image](https://user-images.githubusercontent.com/47116236/133754301-c8b41995-e9af-4a6b-9f03-a4abdacd8511.png)

And Data shows as this

evModeRange:
value: 366
unit: 1
totalAvailableRange:
value: 366
unit: 1
type: 2

odometer:
value: 401
unit: 1

**Comment by gadgetshed** [comment]
Then after I do a force update it updates to the following

evModeRange:
value: 227.41748
unit: 3
totalAvailableRange:
value: 227.41748
unit: 3
type: 2

odometer:
value: 401
unit: 1
Vehicle name

So looks like the figures are always km for odometer and correct for range as long as you take the unit field into account

**Comment by fuatakgun** [comment]
get the latest changes and give it a try

**Comment by fuatakgun** [comment]
just to be sure, now it had created a bug in your setup which did not exist earlier?

**Comment by fuatakgun** [comment]
i had simplified overall process but code changes should not impact anything on unit conversion

**Comment by gadgetshed** [comment]
Not new when I looked the other day it did it too but not always. So was existing intermittent one.

**Comment by gadgetshed** [comment]
Just loaded latest update and it looks correct at the moment, I'll check it over the next few updates and see anything changes.

**Comment by gadgetshed** [comment]
- rangeByFuel:
evModeRange:
value: 223.06796
unit: 3
totalAvailableRange:
value: 223.06796
unit: 3
type: 2

<img width="481" alt="Screenshot 2021-09-17 at 18 43 41" src="https://user-images.githubusercontent.com/47116236/133831432-78a47daf-1ab1-45fb-b76c-86c8b70f639f.png">

**Comment by fuatakgun** [comment]
I am resolving this, let's track conversion issue seperately.
