### ISSUE TITLE
Unable to login using a Europe (NL) Kia account

### ISSUE THREAD

**Issue by HA-TB303** [fuatakgun/kia_uvo#68]
I have a (new) Kia account which works fine with the European Kia Uvo app:

![IMG_5205](https://user-images.githubusercontent.com/9609805/133922683-e1c1ab63-e8d6-46e6-9432-1bd3edfa876e.PNG)

![IMG_5206](https://user-images.githubusercontent.com/9609805/133922686-d4cf47a9-870a-46e4-8d23-3d9e422d618b.PNG)

![image](https://user-images.githubusercontent.com/9609805/133922759-e74af405-8e0e-4ca9-a550-0767b5a2390e.png)

But when trying to login in HA,
![image](https://user-images.githubusercontent.com/9609805/133922622-8fbedf3f-fece-4256-8e36-a2d7abd6a1c1.png)

I get: 
![image](https://user-images.githubusercontent.com/9609805/133922937-7be56462-4ce1-4c4f-948b-0b6e62cfbcd1.png)

HA version: core-2021.9.6
Kia_uvo version: 
![image](https://user-images.githubusercontent.com/9609805/133922816-74aaf17e-db98-470a-8dcc-f4a33b291273.png)

A bug, or Am I doing something wrong?

**Comment by fuatakgun** [comment]
When i am trying to set the integration from scratch, this happens to mw randomly, did you try couple of times?

There is an algorithm by Kia, they are looking for a predefined list of shared keys (tokens). I am using daily updated list but some of them might not be valid, please try again and let me know the output.

As a second try, can you share your car with a different email and try to login with it? This fixes most of the login issues.

**Comment by HA-TB303** [comment]
I have tried numerous times, but no such luck.

I'll try the sharing, but it's not that easy as you say it is since the Kia system is not really straight forward to set up. I have had loads of issues getting the Uvo app to work in the first place and had to call Kia numerous times for support.

**Comment by HA-TB303** [comment]
That went smooither then expected. The shared account works. :)

Not ideal, but for now a working solution.

**Comment by fuatakgun** [comment]
Kia somehow mixed a lot between uvo account and kia account, so, that is the only way i know. Feel free to resolve
