### ISSUE TITLE
CA - Only getting 3 entities

### ISSUE THREAD

**Issue by YeloMelo95** [fuatakgun/kia_uvo#69]
When adding the integration, I am able to login however only 3 entities appear.

binary_sensor.car_data (shows On)
sensor.car_last_update (shows Invalid Timestamp)
device_tracker.car_location (shows unavailable)

Tried removing the integration and repo from HACS, rebooting the host, re-adding the repo, restarting HA and re-adding. Only getting the above 3 entities instead of the 10+ previously. Also tried logging out and in to the UVO app and site during the above steps, no change.

Also the binary_sensor.car_data vehicle_data attribute is empty (state is {}).

Found the following two error logs right after adding the integration:

Logger: custom_components.kia_uvo.Vehicle
Source: custom_components/kia_uvo/Vehicle.py:62
Integration: Kia Uvo / Hyundai Bluelink (documentation)
First occurred: 9:28:30 PM (1 occurrences)
Last logged: 9:28:30 PM

kia_uvo - Exception in update : 'result' - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/Vehicle.py", line 54, in update self.vehicle_data = await self.hass.async_add_executor_job(self.kia_uvo_api.get_cached_vehicle_status, self.token) File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiCA.py", line 127, in get_cached_vehicle_status vehicle_status["vehicleLocation"] = self.get_location(token) File "/config/custom_components/kia_uvo/KiaUvoApiCA.py", line 144, in get_location return response["result"] KeyError: 'result'

And:

Logger: homeassistant.components.lock
Source: custom_components/kia_uvo/lock.py:38
Integration: Lock (documentation, issues)
First occurred: 9:28:30 PM (2 occurrences)
Last logged: 9:28:30 PM

Error adding entities for domain lock with platform kia_uvo
Error while setting up kia_uvo platform for lock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 503, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/kia_uvo/lock.py", line 42, in icon
    return "mdi:lock" if self.is_locked else "mdi:lock-open-variant"
  File "/config/custom_components/kia_uvo/lock.py", line 38, in is_locked
    return self.vehicle.vehicle_data["vehicleStatus"]["doorLock"]
KeyError: 'vehicleStatus'

**Comment by cdnninja** [comment]
Could you update your configuration.yaml with 👍 
`logger:
  default: warning
  logs:
    custom_components.kia_uvo: debug`

Once done your core logs will return what you API is responding with.  I suspect the response doesn't align to what we anticipate. 

To confirm this is a car located in Canada that doesn't work?  What model?

**Comment by YeloMelo95** [comment]
My car is a 2019 Kia Optima and I am in Canada. Strangely enough while re-adding the integration this morning, my 3 entities turned into 19 entities. I was consistently seeing 3 entities yesterday. 

I don't see any errors at all in the core logs. Wondering if, in cases such as these, we need to start the car and allow it to update the server? I did try forcing updates yesterday a few times at different intervals, nothing seemed to make a difference.

I've attached the logs just removed whatever private info I could find, hope it helps. I did notice in the logs that I was hitting the API limit while re-adding the integration a few times yesterday, wondering if that could be it?

[corelogs.txt](https://github.com/fuatakgun/kia_uvo/files/7194780/corelogs.txt)

**Comment by fuatakgun** [comment]
I am worried that we are hitting the limits of APIs because it needs 3
different calls to get status/location/odometer readings.

**Comment by cdnninja** [comment]
Location is a lower API limit than the other calls.  I don't hit this issue when not restarting etc.  This is where I was playing with the try catch on the get location as this allows the rest to keep functioning regardless of the API being maxed on location.  I assume location is what caught @YeloMelo95 on API calls.

**Comment by fuatakgun** [comment]
Ok, let's go with try/catch proposal inside location function as you
suggested.

**Comment by cdnninja** [comment]
#70 should resolve this issue. @YeloMelo95  how has it been since?  This is a pretty recent addition to interested in feedback, items missing or other issues.

**Comment by YeloMelo95** [comment]
This morning all of the entities were "Unavailable" except for the three mentioned in the original post, and had been for 1 day. I re-added the integration and everything was still "Unavailable" for about 30 seconds or so before pulling the latest data. If there is a force update whenever adding/re-adding the integration then that would account for the entities updating once more. So far it has been stable otherwise. I do have an issue with locking / unlocking however I will open a new issue for that.

I would say this issue can be closed off, since I am able to consistently get 19 entities on re-add now.
