### ISSUE TITLE
Low fuel and tyre pressure binary sensors

### ISSUE THREAD

**Issue by holdestmade** [fuatakgun/kia_uvo#7]
Could you add the low fuel and tyre pressure binary sensors please ? The overall tyre pressure warning would be enough for me but each tyre is available as well.

**Comment by fuatakgun** [comment]
I am on it

**Comment by badguy99** [comment]
#8 will add low fuel, as I added it while adding the charging cable plugged in and charging binary sensors, as I was testing that they'd only be added if they existed - i.e. a pure electric doesn't have the low fuel sensor, and a gas only vehicle won't have the ev related sensors.

**Comment by fuatakgun** [comment]
Looks good to me, tested and merged it.

**Comment by fuatakgun** [comment]
This has been implemented on this commit: https://github.com/fuatakgun/kia_uvo/commit/b7caae61294145b435c3b7d8344aa0c241c40f06

you can get latest version.
please close the issue if it is fixed

**Comment by holdestmade** [comment]
Thanks, Low fuel works great, but there are no tyre sensors

**Comment by fuatakgun** [comment]
Can you double check if you have the latest code?

My entities are like this: ![Screenshot_2021-04-11-23-12-19-158_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/11085566/114321518-75efbc80-9b1b-11eb-8c2e-1895aee382b3.jpg)

**Comment by badguy99** [comment]
It's working for me. I've changed the icon for tyre pressure sensor in the front-end to use mdi:car-tire-alert, looks good though.

**Comment by fuatakgun** [comment]
> It's working for me. I've changed the icon for tyre pressure sensor in the front-end to use mdi:car-tire-alert, looks good though.

I had used that icon when it is on state. We can update icon and rely on coloring

**Comment by holdestmade** [comment]
Brilliant, all sensors now showing up
