### ISSUE TITLE
Any plans to integrate this into HomeAssistant Core?

### ISSUE THREAD

**Issue by andygrunwald** [fuatakgun/kia_uvo#71]
Hey @fuatakgun,
thanks a lot for your hard work on this.

Are there any plans to apply this Home Assistant Integration into Home Assistant Core to list as an official integration?
If yes, do you know what is missing or where support is needed?

**Comment by fuatakgun** [comment]
hey, thanks for good wishes, regarding to integration as official integration, I have some doubts like;
- having an custom integration gives an opportunity to release any bug fixes independent of release calendar. Moreover, if it is merged into core, it is still up to codeowners to fix the issues, it will not be taken care of by `everyone` :)
- integration is still in early stage, there are some small issues here and there. 
- i am not able to find out the real benefit of doing so. I see that everyone is somehow aware of HACS and using it.

I would like to know more about your thoughts.

**Comment by cdnninja** [comment]
I would like to see it merge at some point - I think it would get much larger exposure.  I do think a bit more work is needed first though.

**Comment by andygrunwald** [comment]
@fuatakgun That makes totally sense.

I was searching in the Home Assistant Developer docs for exactly these kinds of constraints, but I was not able to find them. Do you have a source for me on this?

One opposite is to keep up with new releases and API changes.

**Comment by cdnninja** [comment]
As a note on this,  this integration is now a native repo for HACS so this should make it a bit easier for others to add this.   Also have moved to Black styling and releases which works us closer to home assistant standards.

**Comment by fuatakgun** [comment]
We had started working on this.

It is taking time, but hopefully we will see this as part of core, some day :-)
