### ISSUE TITLE
Exception in update: string indices must be integers [EU]

### ISSUE THREAD

**Issue by TazUk** [fuatakgun/kia_uvo#74]
Love the integration - using it with a 2021 Stonic in the UK.
I'm running HomeAssistant Container in docker on Ubuntu 18.04 with version e873526 installed via HACS.

I've seen this error reported occasionally in the HA logs for quite some time (persisting through repository version updates), reported several times on a daily basis.

`kia_uvo - Exception in update : string indices must be integers - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/Vehicle.py", line 54, in update self.vehicle_data = await self.hass.async_add_executor_job(self.kia_uvo_api.get_cached_vehicle_status, self.token) File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 257, in get_cached_vehicle_status return response["resMsg"]["vehicleStatusInfo"] TypeError: string indices must be integers`

**Comment by fuatakgun** [comment]
i have also the same problem, but not much bothered on it :-)

Sometimes, Kia/Hyundai servers are not responding as expected but it is not a show stopper. 

We can emit the error and just capture it on logs.

**Comment by fuatakgun** [comment]
This should not be happening anymore.
