### ISSUE TITLE
Working in Norway?

### ISSUE THREAD

**Issue by trondtorsoe** [fuatakgun/kia_uvo#78]
Hi

You wrote users outside EU was welcome to become testers for other regions.....

Can you add Norway?

Thanks

Trond

**Comment by fuatakgun** [comment]
Hey, Norway should be part of Europe right? I also live in Europe so all should be working, go ahead and test it. I specifically asked for testers outside of Europe because i don't have a chance to test myself.

**Comment by trondtorsoe** [comment]
OK.  Yes Norway is par of Europe - but not member og EU :-)

I will test!

Trond
