### ISSUE TITLE
kia_uvo Exception in kia_uvo login : 'redirectUrl' - traceback: Traceback (most recent call last):

### ISSUE THREAD

**Issue by Gotanius** [fuatakgun/kia_uvo#79]
I get this error while trying to login. 
It's a UVO to Kia migrated account (migrated a while back). 
I checked the credentials and they are correct.

**Comment by fuatakgun** [comment]
Can you try this;
- create a new account from scratch
- share your car with that account
- try to login with the new account

**Comment by FransHalsjes** [comment]
I have the same problem. Created a brand new account, got it verified through phone number, but when installing the integration i keep getting:
'''
Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:169
Integration: Kia Uvo / Hyundai Bluelink (documentation)
First occurred: 14:33:42 (2 occurrences)
Last logged: 14:34:22

kia_uvo Exception in kia_uvo login : 'redirectUrl' - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/config_flow.py", line 154, in async_step_user self.token = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 151, in login parsed_url = urlparse(response.json()["redirectUrl"]) KeyError: 'redirectUrl'
'''

**Comment by alfredkrohmer** [comment]
Same problem here with Hyundai Bluelink. Account created last week.

**Comment by jeroenkl** [comment]
> I need to setup local debugging environment and login into one problematic account (i have one) but it is clear that there is a problem between old and new accounts

Hope you can fix it soon

**Comment by arjanschepers** [comment]
Same issue here:

kia_uvo Exception in kia_uvo login : 'redirectUrl' - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/config_flow.py", line 154, in async_step_user self.token = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 151, in login parsed_url = urlparse(response.json()["redirectUrl"]) KeyError: 'redirectUrl'

I have my car (and account) only for 2 weeks so it's a "new" account. Tried logigng out and in on the Kia Connect and UVO app, to no avail. Let me know if I can do something to help testing.

**Comment by hans99** [comment]
Can we help here in any way?
What debug/traces do you need?

**Comment by randriksen** [comment]
I think I might be having the same issue:

kia_uvo Exception in kia_uvo login : 'redirectUrl' - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/config_flow.py", line 154, in async_step_user self.token = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 151, in login parsed_url = urlparse(response.json()["redirectUrl"]) KeyError: 'redirectUrl'

the account it new. made yesterday on bluelink, so it shouldn't be on an old server. 
The account works in the app and on the hyundai web pages.

**Comment by cdnninja** [comment]
Looks like this is how bluelinky fixed the issue. 

https://github.com/Hacksore/bluelinky/pull/168

If I get a chance in the next few days I'll see if I can do something similar.  Also looks like a manual workaround may exist by putting the redirect into a browser and accepting it.

**Comment by fuatakgun** [comment]
This cannot be in issue for us because our issue is happening even after acknowledging this consent

**Comment by cdnninja** [comment]
Gotcha - that is unfortunate.

**Comment by fuatakgun** [comment]
I will try to replicate new login strategy here: https://github.com/Hacksore/bluelinky/blob/7336aca9296d988e808083da68c711806a2b80a9/src/controllers/authStrategies/european.brandAuth.strategy.ts

**Comment by fuatakgun** [comment]
I am able to login with new flow (it is dumb hell), I will work with @Flight777 to test changes locally before publishing them

**Comment by fuatakgun** [comment]
EU Kia and Hyundai users, please give latest version a try and report back

**Comment by hans99** [comment]
Great work! I could login now and integrate with hass!

**Comment by HMvdZijden** [comment]
Could not login to my kia account:
version cc2046d
log:
kia_uvo Exception in kia_uvo login : can only concatenate str (not "NoneType") to str - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/config_flow.py", line 154, in async_step_user self.token = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 108, in login ) = self.get_access_token() File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 312, in get_access_token "grant_type=authorization_code&redirect_uri=https%3A%2F%2F" TypeError: can only concatenate str (not "NoneType") to str

does anyone know what I can do to resolve it?

**Comment by fuatakgun** [comment]
I was able to test with a Hyundai account, i might need a kia account to debug this. If we can do this together, you can share your car with me in agreed times and i can debug.

Otherwise, i don't have a solution to debug, sorry.

**Comment by HMvdZijden** [comment]
L.S.

I have no problem sharing my car to make it possible to debug.
Send me the neccesary accountdata and ik wil make the account and share.

Met vriendelijke groet,

Herman v.d. Zijden
  ***@***.***

**Comment by RubenKremer** [comment]
> EU Kia and Hyundai users, please give latest version a try and report back

New version worked like a charm - I can login now and am getting _all the _data_.

**Comment by fuatakgun** [comment]
> New version worked like a charm - I can login now and am getting _all the _data_.
Hyundai or Kia?

**Comment by RubenKremer** [comment]
> @RubenKremer is it Kia or Hyundai?

Sorry - forget to mention - Hyundai Europe

**Comment by fuatakgun** [comment]
@HMvdZijden , please write an email to me `fuatakgun@gmail.com`

Apparently, all is working for Hyundai Europe but failing for Kia Europe.

**Comment by Cevendir** [comment]
> @HMvdZijden , please write an email to me `fuatakgun@gmail.com`
> 
> Apparently, all is working for Hyundai Europe but failing for Kia Europe.

Sounds about right.

"kia_uvo Exception in kia_uvo login : can only concatenate str (not "NoneType") to str - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/config_flow.py", line 154, in async_step_user self.token = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures"

**Comment by HMvdZijden** [comment]
The subject is getting quit long.

Op ma 15 nov. 2021 15:34 schreef Cevendir ***@***.***>:

**Comment by fuatakgun** [comment]
I am fine if this is getting long, we have nailed down Hyundai EU problem, I need someone to email me so we can discuss about car sharing for Kia EU.

my email `fuatakgun@gmail.com`

**Comment by fuatakgun** [comment]
EU Kia users, please give this a try

**Comment by fuatakgun** [comment]
Had received multiple success stories over email, resolving now, comment if you face any issue

**Comment by alfredkrohmer** [comment]
Another success report here, thanks a lot for the effort :tada:

**Comment by arjanschepers** [comment]
Fixed for me as well! (EU/Kia). Thank you very much!

**Comment by riksarchen** [comment]
Not working for me. Kia Sweden. Same error as previous. Do I need to add car before login?

**Comment by alfredkrohmer** [comment]
@riksarchen This is *not* the same error that has been reported in this issue. And yes, the stack trace looks like you need to add a car with the app first.
