### ISSUE TITLE
Hyundai USA Support

### ISSUE THREAD

**Issue by TarheelGrad1998** [fuatakgun/kia_uvo#80]
I tried the integration using Canada region, but it does not accept my login.  I'm guessing my region is not supported yet, based on documentation.  

Anyway I have a new Hyundai in the US and am willing to test.  Just let me know what I need to do.

**Comment by cdnninja** [comment]
Sounds good! It will take some time to write the support for the US side.  It looks to be a different than both CAD and EU.  I have one more feature I am working on before I can take a stab at it.   It may be painful since I don't have a car to test against myself.  Is you car a EV or ICE?

**Comment by mbbush** [comment]
I'm in the US, my car is an EV, I'm also a developer by trade, and I'd like to help.

I have a little bit of experience reverse engineering/traffic sniffing mobile apps.

Bluelinky doesn't currently work with kia cars in the US.

**Comment by cdnninja** [comment]
This is great!  Help is greatly appreciated.  The big thing I need a hand with is figuring out how to find what data.  I am no developer by trade but @fuatakgun is. I just like to tinker.  I will create a branch for us to play with.  One of the questions will be if the Kia integration is the same give or take to Hyundai in USA.   It is for other regions.  Changes how we approach this.  

Does USA have a regular website for Hyundai or Kia?  Or is it only mobile app?

**Comment by cdnninja** [comment]
I have updated the USA branch to separate the two APIs for now.  I created a kia account and on the website getting different URLs than what you have above, based on what I am seeing authentication doesn't use oauth. We can merge if required. @mbbush  I am also going to create a second issue for this to keep this thread focused on Hyundai with the new one focused on KIA.

**Comment by bvlaicu** [comment]
@cdnninja Yes, that's how I got the response json :)

**Comment by cdnninja** [comment]
Awesome!  Any errors from home assistant?  If not I’ll move on to the next part.

**Comment by TarheelGrad1998** [comment]
Put in a pull request with that change.  Feel free to edit or let me know if I didn't do something correctly.

**Comment by bvlaicu** [comment]
I have PR https://github.com/fuatakgun/kia_uvo/pull/91 with fixes for Hyundai USA. 

All sensors are created successfully except `temperatureSetpoint` which for the USA API is not a number, I see a value of `LO`, so I guess it's a LO, HI rather than a C or F degree number. So I added code to skip this sensor for region USA.

<img width="458" alt="image" src="https://user-images.githubusercontent.com/26512965/138176839-ce5da788-04a0-477e-bf6d-f0498ec553f8.png">

**Comment by TarheelGrad1998** [comment]
Nice!  I was aiming to get back to this, but work picked up.  I'll give this a try in a day or two.

**Comment by bvlaicu** [comment]
Is there a way to apply the code changes (reload the integration) without a full HA restart?

**Comment by cdnninja** [comment]
Not that I am aware of.  You can do “just” core but that doesn’t help much.

**Comment by TarheelGrad1998** [comment]
FWIW, I run a second docker container with base HA while I'm deving, helps a lot with quicker restarts and not messing with my main instance.

Anyway, I have the basics working but haven't had much time to clean/finish up.  We need to add the regId to the token.  I'm slow, but making progress.

**Comment by bvlaicu** [comment]
@TarheelGrad1998 Did you start working on start/stop? I might be able to spend some time this weekend and implement those two. I'm more interested in those than lock/unlock.

**Comment by bvlaicu** [comment]
I implemented the engine start/stop in PR https://github.com/fuatakgun/kia_uvo/pull/97
It includes a global change to add the vehicle registration id to the Token class.

**Comment by TarheelGrad1998** [comment]
> @TarheelGrad1998 Did you start working on start/stop? I might be able to spend some time this weekend and implement those two. I'm more interested in those than lock/unlock.

If you have time, do it.  If you don't have time, I can, but it's going to take me more than 5 days.  Sorry.

**Comment by TarheelGrad1998** [comment]
Hrm, not sure if it's me or what, but in my testing I'm getting a lot of token expiration errors, or error 502, "We're sorry, but we could not complete your request. Please try again later."  

But I think it's working, mostly.  It's also hard to tell because the mirrors do not fold/unfold, and unlock commands are slow and seem to lock back in under a minute if you don't open the door.  But I can see the commands in the Hyundai website....when i don't get one of the above errors.

**Comment by TarheelGrad1998** [comment]
...created a PR with the changes, if someone else wants to try:  https://github.com/fuatakgun/kia_uvo/pull/98

It is dependent on @bvlaicu PR 97.

**Comment by cdnninja** [comment]
Just merged everyone's hard work.  Would appreciate testing away!

**Comment by cdnninja** [comment]
Closing this since most features have been built. Please open a new issue for anything further.
