### ISSUE TITLE
Sensors for targetSOClevel

### ISSUE THREAD

**Issue by LuckyTriple7** [fuatakgun/kia_uvo#84]
Hello, great Integration, works very good.
Is there a way for adding 2 Sensors:

Range Target SOC Level AC, in this case 494km (100% Target SOC)
Range Target SOC Level DC, in this case 386km (80% Target SOC)

![image](https://user-images.githubusercontent.com/60685158/137087968-c4015d5d-13cc-4e06-a7bf-4f35045c63a6.png)

**Comment by LuckyTriple7** [comment]
OK, is update the senspr.py file and restartet HA.
But i cannot see the Sensors ...


`    INSTRUMENTS = []

    if vehicle.engine_type is VEHICLE_ENGINE_TYPE.EV or vehicle.engine_type is VEHICLE_ENGINE_TYPE.PHEV:
        INSTRUMENTS.append(("evBatteryPercentage", "EV Battery", "vehicleStatus.evStatus.batteryStatus", PERCENTAGE, "mdi:car-electric", DEVICE_CLASS_BATTERY))
        INSTRUMENTS.append(("evDrivingDistance", "Range by EV", "vehicleStatus.evStatus.drvDistance.0.rangeByFuel.evModeRange.value", DYNAMIC_DISTANCE_UNIT, "mdi:road-variant", None))
        INSTRUMENTS.append(("totalDrivingDistance", "Range Total", "vehicleStatus.evStatus.drvDistance.0.rangeByFuel.totalAvailableRange.value", DYNAMIC_DISTANCE_UNIT, "mdi:road-variant", None))
        INSTRUMENTS.append(("estimatedCurrentChargeDuration", "Estimated Current Charge Duration", "vehicleStatus.evStatus.remainTime2.atc.value", TIME_MINUTES, "mdi:ev-station", None))
        INSTRUMENTS.append(("estimatedFastChargeDuration", "Estimated Fast Charge Duration", "vehicleStatus.evStatus.remainTime2.etc1.value", TIME_MINUTES, "mdi:ev-station", None))
        INSTRUMENTS.append(("estimatedPortableChargeDuration", "Estimated Portable Charge Duration", "vehicleStatus.evStatus.remainTime2.etc2.value", TIME_MINUTES, "mdi:ev-station", None))
        INSTRUMENTS.append(("estimatedStationChargeDuration", "Estimated Station Charge Duration", "vehicleStatus.evStatus.remainTime2.etc3.value", TIME_MINUTES, "mdi:ev-station", None))
        INSTRUMENTS.append(("targetSOCAC", "Target State of Charge AC", "vehicleStatus.targetSOClist.0.targetSOClevel.dte.totalAvailableRange.value", DYNAMIC_DISTANCE_UNIT, "mdi:ev-station", None))
        INSTRUMENTS.append(("targetSOCDC", "Target State of Charge DC", "vehicleStatus.targetSOClist.1.targetSOClevel.dte.totalAvailableRange.value", DYNAMIC_DISTANCE_UNIT, "mdi:ev-station", None))`

**Comment by cdnninja** [comment]
Give this a try: 

`        INSTRUMENTS.append(("targetSOCAC", "Target State of Charge AC", "vehicleStatus.evStatus.targetSOClist.0.dte.totalAvailableRange.value", DYNAMIC_DISTANCE_UNIT, "mdi:ev-station", None))
        INSTRUMENTS.append(("targetSOCDC", "Target State of Charge DC", "vehicleStatus.evStatus.targetSOClist.1.dte.totalAvailableRange.value", DYNAMIC_DISTANCE_UNIT, "mdi:ev-station", None))
`

**Comment by LuckyTriple7** [comment]
Hello, that didn't work either.

**Comment by fuatakgun** [comment]
I do not think we can assume the order will be fixed between all requests, we need to resolve it through plugType to differentiate AC/DC. I will take a look today

**Comment by cdnninja** [comment]
Thanks @fuatakgun  I agree the above can't be used in the standard branch.   Much easier for someone to do this who has an EV so I really appreciate you doing this.

**Comment by dahlb** [comment]
looks like plugType attribute can tell type, at least in US 0 is DC and 1 is AC

							"targetSOC": [{
								"plugType": 0,
								"targetSOClevel": 80,
								"dte": {
									"type": 2,
									"rangeByFuel": {
										"gasModeRange": {
											"value": 0,
											"unit": 3
										},
										"evModeRange": {
											"value": 229,
											"unit": 3
										},
										"totalAvailableRange": {
											"value": 229,
											"unit": 3
										}
									}
								}
							}, {
								"plugType": 1,
								"targetSOClevel": 90,
								"dte": {
									"type": 2,
									"rangeByFuel": {
										"gasModeRange": {
											"value": 0,
											"unit": 3
										},
										"evModeRange": {
											"value": 229,
											"unit": 3
										},
										"totalAvailableRange": {
											"value": 229,
											"unit": 3
										}
									}
								}
							}]

**Comment by dahlb** [comment]
this might work https://github.com/fuatakgun/kia_uvo/pull/154 might have to move the sort to state instead of init, I'm not sure of life span of the sensor, is it long lived or recreated when values change?

**Comment by dahlb** [comment]
verified #154 fixes this with my own data, though unlike your sample response my distance from the api is garbage, both 80% and 100% returns the same distance, I'd be happy with just the percentage and dropping the distance for soc given the usa api results, which might be because the service that would pair with this would only set percentage not the distance (which isn't displayed in our official app). But we can leave both if generally wanted.

**Comment by cdnninja** [comment]
@LuckyTriple7  could you test out this pull request?

**Comment by LuckyTriple7** [comment]
Good Morning, thanks for the Information.
How can I test this? Is there a possibility to download the changed files in the Pull Request ?

**Comment by dahlb** [comment]
@LuckyTriple7 I'm not sure how you installed it but you can download a full zip of all the integration files from the pr at https://github.com/dahlb/kia_uvo/archive/refs/heads/feat_soc_sensors.zip and unzip to install, if you installed with git instead let me know and I can provide commands to update your files to the pr version another way.

**Comment by dahlb** [comment]
@cdnninja any objection to merging this? I already tested it with my EV and it looks like lucky's has the same structure, if lucky does have a problem we could open it as a bug and it would be much easier for lucky to verify on master since it's already been verified.
