### ISSUE TITLE
KIA Connect

### ISSUE THREAD

**Issue by nordan70** [fuatakgun/kia_uvo#85]
It seems that Kia want us users to start using the new app Kia Connect. 
Will this be a problem for this implementation?

https://connect.kia.com/

**Comment by fuatakgun** [comment]
They are twins :-) with a slight difference

![IMG_20211014_113557.jpg](https://user-images.githubusercontent.com/11085566/137292051-a4a4fc8a-27b9-41b7-9e98-6ca4c27b3c2f.jpg)
