### ISSUE TITLE
Door icons

### ISSUE THREAD

**Issue by holdestmade** [fuatakgun/kia_uvo#9]
Not sure if you have seen this icon but seems more suited to the car doors ?

mdi:car-door

**Comment by fuatakgun** [comment]
I have seen them but couldn't find any option to have open/close variants. Do you think this would be more suitable?

**Comment by holdestmade** [comment]
Yes, I am using them with Customize. They change colour when open. If it's just me then no problem to just use customize in HA

**Comment by fuatakgun** [comment]
fixed with latest version
