### ISSUE TITLE
Missing Description and Topics

### ISSUE THREAD

**Issue by cdnninja** [fuatakgun/kia_uvo#94]
I don't think I can edit this to resolve.  To add as a HACS integration default repo the following needs to be done: 

The repository is missing topics 
The repository is missing a description
Missing information file (I think this is config since readme.md is allowed) 

Are you able to add these?

**Comment by cdnninja** [comment]
I resolved the missing info file in the PR.    Just the topic and description remain.

**Comment by fuatakgun** [comment]
What is needed here?

**Comment by cdnninja** [comment]
A description and topic needs to be configured on the repo in the top right of github main page.  This will pass the checks and this description will show in HACS.

**Comment by cdnninja** [comment]
To help this out here are some topics as a starting point: homeassistant kia hyundai hyundai-bluelink homeassistant-integration uvo kiauvo

Description: A Home Assistant HACS integration that supports Kia Connect(Uvo) and Hyundai Bluelink.  The integration supports the EU, Canada and the USA.

**Comment by fuatakgun** [comment]
done
